Repository google/knative-gcp, pull requests merged in 2019-10, with the labels that each got.

#314 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/main.go
Labels: approved, lgtm, ok-to-test, size/S

#315 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/kmeta/accessor.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/main.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/testutils/clustermanager/client.go
  vendor/knative.dev/pkg/testutils/clustermanager/gke.go
  vendor/knative.dev/pkg/tracker/enqueue.go
Labels: approved, lgtm, ok-to-test, size/L

#316 E2E test for Storage Metrics
  Gopkg.lock
  pkg/apis/events/v1alpha1/storage_types.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types.go
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/storage.go
  test/e2e-common.sh
  test/e2e/README.md
  test/e2e/constants.go
  test/e2e/e2e_test.go
  test/e2e/lifecycle.go
  test/e2e/metrics/stackdriver.go
  test/e2e/test_pull_subscription.go
  test/e2e/test_storage.go
Labels: approved, lgtm, size/L

#323 Format markdown
  test/e2e/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#322 golang format tools
  test/e2e/metrics/stackdriver.go
  test/e2e/test_pubsub.go
  test/e2e/test_pull_subscription.go
Labels: approved, lgtm, ok-to-test, size/XS

#320 PubSub E2E Test + Test Refactoring
  cmd/controller/main.go
  cmd/pubsub/receive_adapter/main.go
  pkg/apis/events/v1alpha1/pubsub_types.go
  pkg/pubsub/adapter/adapter.go
  test/e2e-common.sh
  test/e2e/constants.go
  test/e2e/e2e_test.go
  test/e2e/lifecycle.go
  test/e2e/metrics/stackdriver.go
  test/e2e/test_channel.go
  test/e2e/test_pubsub.go
  test/e2e/test_pull_subscription.go
  test/e2e/test_storage.go
  test/e2e/topics.go
Labels: approved, lgtm, size/L

#292 Add ClusterRole to get, list and watch pullsubscriptions and storages
  config/201-clusterrole.yaml
Labels: approved, lgtm, ok-to-test, size/M

#337 Add secret finalizer for PullSubscription
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
Labels: approved, lgtm, size/L

#339 Add secret finalizer for Topic
  pkg/reconciler/topic/topic.go
  pkg/reconciler/topic/topic_test.go
Labels: approved, lgtm, size/L

#342 Add unit test - fail Topic validation for invalid propagation policy
  pkg/apis/pubsub/v1alpha1/topic_validation_test.go
Labels: approved, lgtm, size/S

#329 Set ProjectID on Notification Delete Operations.
  pkg/operations/storage/notification.go
  pkg/operations/storage/notification_test.go
  pkg/reconciler/storage/storage.go
  pkg/reconciler/storage/storage_test.go
  pkg/reconciler/testing/storage.go
Labels: approved, lgtm, ok-to-test, size/L

#341 Propagate pubsub subscription/topic failure reason from job pod
  pkg/operations/pubsub/subscription.go
  pkg/operations/pubsub/topic.go
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
  pkg/reconciler/testing/pullsubscription.go
  pkg/reconciler/testing/topic.go
  pkg/reconciler/topic/topic.go
  pkg/reconciler/topic/topic_test.go
Labels: approved, lgtm, size/L

#338 Updating EventTypes
  config/300-pubsub.yaml
  config/300-pullsubscription.yaml
  config/300-scheduler.yaml
  config/300-storage.yaml
  docs/storage/README.md
  pkg/apis/events/v1alpha1/storage_defaults.go
  pkg/apis/events/v1alpha1/storage_defaults_test.go
  pkg/apis/events/v1alpha1/storage_types.go
  pkg/operations/storage/notification.go
  pkg/pubsub/adapter/converters/converters.go
  pkg/pubsub/adapter/converters/storage.go
Labels: approved, lgtm, size/M

#345 Add unit tests for pubsub adapter
  pkg/pubsub/adapter/adapter_test.go
  pkg/pubsub/adapter/converters/storage.go
Labels: approved, lgtm, size/L

#346 Fixing pubsub type
  docs/pullsubscription/README.md
  docs/scheduler/README.md
  pkg/apis/events/v1alpha1/pubsub_types.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types.go
Labels: approved, lgtm, size/XS

#348 Adding nachocano to approvers list
  OWNERS
Labels: approved, lgtm, size/XS

#349 Use Semantic.DeepEqual instead of cmp.Diff in topic reconciler
  pkg/reconciler/topic/topic.go
Labels: approved, lgtm, size/XS

#355 Format markdown
  config/monitoring/metrics/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#356 golang format tools
  test/e2e/test_pubsub.go
  test/e2e/test_pull_subscription.go
Labels: approved, lgtm, ok-to-test, size/XS

#365 Adding standard duck label on CRD to signal this resource adheres to Addressable.
  config/300-channel.yaml
  config/300-topic.yaml
Labels: approved, lgtm, size/S

#370 Handle subscriber already exists error gracefully for pubsub channel
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
Labels: approved, lgtm, size/L

#371 Updating pkg to latest for 0.10 release.
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/XS

#372 golang format tools
  pkg/apis/events/v1alpha1/storage_lifecycle.go
Labels: approved, lgtm, ok-to-test, size/XS

#377 Updating registry annotation
  config/300-pubsub.yaml
  config/300-pullsubscription.yaml
  config/300-scheduler.yaml
  config/300-storage.yaml
Labels: approved, lgtm, size/S

#380 Switch deocrator to use the shared SourceSpec duck type.
  pkg/apis/messaging/v1alpha1/decorator_lifecycle.go
  pkg/apis/messaging/v1alpha1/decorator_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/decorator_types.go
  pkg/apis/messaging/v1alpha1/decorator_validation.go
  pkg/apis/messaging/v1alpha1/decorator_validation_test.go
  pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/decorator/controller.go
  pkg/reconciler/decorator/decorator.go
  pkg/reconciler/decorator/resources/decorator.go
  pkg/reconciler/decorator/resources/decorator_test.go
Labels: approved, lgtm, size/L

#379 Add slash to secret finalizer name
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
  pkg/reconciler/topic/topic.go
  pkg/reconciler/topic/topic_test.go
Labels: approved, lgtm, size/M

#382 golang format tools
  pkg/reconciler/decorator/controller.go
Labels: approved, lgtm, ok-to-test, size/XS

#384 Fix how to check Job termination status
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/scheduler/scheduler.go
  pkg/reconciler/scheduler/scheduler_test.go
  pkg/reconciler/storage/storage.go
  pkg/reconciler/storage/storage_test.go
Labels: approved, lgtm, size/M

#376 Allow cloud-run-events service account to patch secrets
  config/201-clusterrole.yaml
Labels: approved, lgtm, size/XS

#393 Update pkg to 0.10 release and fix webhook
  Gopkg.lock
  cmd/webhook/main.go
  config/500-webhook-configuration.yaml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/README.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/gcp_metadata.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/knative.dev/pkg/webhook/config_validation_controller.go
  vendor/knative.dev/pkg/webhook/resource_admission_controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, size/XL
