Repository google/knative-gcp, pull requests merged in 2019-12, with the labels that each got.

#433 Create a script to set up a default broker for a given namespace
  hack/shortcuts/setup_ns_broker.sh
Labels: approved, lgtm, size/M

#439 Updating pkg to 0.11 to prepare for the release
  Gopkg.lock
  Gopkg.toml
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics_batcher.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics_proto.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics_test_utils.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/aws_identity_doc_utils.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/gcp_metadata_config.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/resource.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stackdriver.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stats.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/trace.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/duck/const.go
  vendor/knative.dev/pkg/apis/duck/interface.go
  vendor/knative.dev/pkg/apis/duck/unstructured.go
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/monitored_resources_eventing.go
  vendor/knative.dev/pkg/metrics/monitored_resources_serving.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/testing/duck/doc.go
  vendor/knative.dev/pkg/testing/duck/register.go
  vendor/knative.dev/pkg/testing/duck/testbindable.go
  vendor/knative.dev/pkg/testing/duck/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/webhook/psbinding/README.md
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/doc.go
  vendor/knative.dev/pkg/webhook/psbinding/index.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/testing/listers.go
Labels: approved, lgtm, size/XXL

#437 CloudEvents v1 events
  Gopkg.lock
  docs/channel/README.md
  docs/pullsubscription/README.md
  docs/scheduler/README.md
  docs/storage/README.md
  pkg/pubsub/adapter/adapter_test.go
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/pubsub_test.go
  pkg/pubsub/adapter/converters/storage.go
  pkg/pubsub/adapter/converters/storage_test.go
  pkg/pubsub/publisher/publisher.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/configuration_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/route_validation.go
Labels: approved, lgtm, size/L

#443 Updating eventing and serving to release-0.11
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_validation.go
Labels: approved, lgtm, size/S

#448 E2E to v1.0
  Gopkg.lock
  Gopkg.toml
  test/cmd/receiver/main.go
  test/cmd/sender/main.go
  vendor/github.com/cloudevents/sdk-go/alias.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/defaulters.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/pubsub/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/pubsub/codec_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/pubsub/codec_v1.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/pubsub/encoding.go
Labels: approved, lgtm, size/L

#449 Comment SDK change to Master
  Gopkg.toml
Labels: approved, lgtm, size/XS

#453 modified owners
  OWNERS
Labels: approved, lgtm, size/XS

#458 Updating install documentation
  README.md
  docs/install/README.md
Labels: approved, lgtm, size/L

#461 Updated PullSubscription and other docs
  docs/README.md
  docs/channel/README.md
  docs/channel/event-display.yaml
  docs/install/README.md
  docs/install/managing-multiple-projects.md
  docs/install/pubsub-service-account.md
  docs/pubsub/README.md
  docs/pullsubscription/README.md
  docs/pullsubscription/event-display.yaml
  docs/scheduler/README.md
  docs/scheduler/event-display.yaml
  docs/storage/README.md
  docs/storage/event-display.yaml
  docs/topic/README.md
Labels: approved, lgtm, size/L

#466 Add missed secret for performance test setup
  test/performance/performance-tests.sh
Labels: approved, lgtm, size/S
