Repository google/knative-gcp, pull requests merged in 2019-08, with the labels that each got.

#116 Updates to README
  docs/pullsubscription/README.md
  docs/pullsubscription/event-display.yaml
Labels: approved, lgtm, size/S

#120 Use knative.dev/test-infra
  Gopkg.lock
  Gopkg.toml
  hack/release.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/update-knative.sh
  hack/verify-codegen.sh
  test/presubmit-tests.sh
  vendor/knative.dev/test-infra/LICENSE
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/dummy.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/knative.dev/test-infra/tools/dep-collector/README.md
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
  vendor/knative.dev/test-infra/tools/dep-collector/main.go
Labels: approved, lgtm, size/L

#119 golang format tools
  pkg/apis/messaging/v1alpha1/channel_validation.go
  pkg/apis/messaging/v1alpha1/register_test.go
  pkg/apis/pubsub/v1alpha1/register_test.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/channel/resources/names.go
  pkg/reconciler/channel/resources/pullsubscription_test.go
  pkg/reconciler/testing/channel.go
Labels: approved, lgtm, ok-to-test, size/S

#122 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/hack/verify-codegen.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
Labels: approved, lgtm, ok-to-test, size/M

#121 Format markdown
  docs/pullsubscription/README.md
Labels: approved, lgtm, ok-to-test, size/S

#125 Minor updates to yaml.
  config/istio/600-istioegress.yaml
  config/transformers/pubsub-push.yaml
Labels: approved, lgtm, size/XS

#124 Update pubsub to use secrets and fix serving version to v1alpha1.
  Gopkg.lock
  pkg/apis/pubsub/v1alpha1/topic_lifecycle.go
  pkg/pubsub/operations/pod.go
  pkg/pubsub/operations/subscription.go
  pkg/pubsub/operations/topic.go
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/topic/controller.go
  pkg/reconciler/topic/controller_test.go
  pkg/reconciler/topic/resources/names.go
  pkg/reconciler/topic/resources/publisher.go
  pkg/reconciler/topic/resources/publisher_test.go
  pkg/reconciler/topic/topic.go
  pkg/reconciler/topic/topic_test.go
  vendor/knative.dev/serving/pkg/client/injection/informers/serving/v1alpha1/service/fake/fake.go
  vendor/knative.dev/serving/pkg/client/injection/informers/serving/v1alpha1/service/service.go
Labels: approved, lgtm, size/XL

#128 golang format tools
  pkg/pubsub/operations/pod.go
  pkg/reconciler/topic/controller.go
  pkg/reconciler/topic/controller_test.go
  pkg/reconciler/topic/resources/names.go
  pkg/reconciler/topic/topic_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#129 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/vegeta/pacers/combined_pacer.go
  vendor/knative.dev/pkg/test/vegeta/pacers/steady_up_pacer.go
Labels: approved, lgtm, ok-to-test, size/L

#126 Fix update deps to run on linux and prow.
  hack/update-codegen.sh
Labels: approved, lgtm, size/XS

#130 adding mattmoor to owners.
  OWNERS
Labels: approved, lgtm, size/XS

#133 add a terrible hack for even more terrible hack
  hack/update-codegen.sh
Labels: approved, lgtm, size/XS

#136 Updating pkg to latest for 0.8 release
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/XS

#138 Add registry property to PullSubscription CRD
  config/300-pullsubscription.yaml
  pkg/apis/pubsub/v1alpha1/pull_subscription_types.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types_test.go
Labels: approved, lgtm, size/S

#139 update test-infra: fixing E2E_PROJECT_ID env var problem
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: size/XS

#141 golang format tools
  test/e2e/pull_subscription.go
  test/e2e/smoke.go
Labels: approved, lgtm, ok-to-test

#142 Fix spelling errors
  test/e2e/pull_subscription.go
Labels: approved, lgtm, ok-to-test

#147 no need for sed hack anymore
  hack/update-codegen.sh
Labels: approved, lgtm, size/S

#145 Updating pkg to latest for 0.9 work.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/calculator.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/coveragedata.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/ignorefields.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/arraykindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/basictypekindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/node.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/otherkindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/ptrkindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/resourceforest.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/resourcetree.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/rule.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/structkindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/test_util.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/timetypenode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/tools.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/html_display.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/rule.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/apicoverage_recorder.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/webhook.go
Labels: approved, lgtm, size/XXL

#150 adding storage converter files
  pkg/pubsub/adapter/adapter.go
  pkg/pubsub/adapter/converters/converters.go
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/storage.go
  pkg/reconciler/pullsubscription/resources/receive_adapter.go
Labels: approved, lgtm, size/L

#151 Updating Storage Converter
  pkg/pubsub/adapter/converters/storage.go
Labels: approved, lgtm, ok-to-test, size/M

#155 Fixing Storage CRD
  config/300-storage.yaml
Labels: needs-ok-to-test, size/XS

#157 Conversion to GCS EventTypes
  pkg/reconciler/storage/storage.go
Labels: approved, lgtm, ok-to-test, size/S

#158 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1beta1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/v1alpha1/destination.go
  vendor/knative.dev/pkg/apis/v1alpha1/doc.go
  vendor/knative.dev/pkg/apis/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/testutils/OWNERS
  vendor/knative.dev/pkg/testutils/README.md
  vendor/knative.dev/pkg/testutils/clustermanager/boskos/boskos.go
  vendor/knative.dev/pkg/testutils/clustermanager/client.go
  vendor/knative.dev/pkg/testutils/clustermanager/doc.go
  vendor/knative.dev/pkg/testutils/clustermanager/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/util.go
  vendor/knative.dev/pkg/testutils/common/common.go
Labels: approved, lgtm, ok-to-test, size/XL

#159 Adding CloudEvents Overrides to PullSubscription. (API Only)
  Gopkg.lock
  config/300-pullsubscription.yaml
  pkg/apis/pubsub/v1alpha1/implements_test.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation_test.go
  pkg/apis/pubsub/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/channel/resources/pullsubscription.go
  pkg/reconciler/channel/resources/pullsubscription_test.go
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/storage/resources/pullsubscription.go
  pkg/reconciler/testing/pullsubscription.go
Labels: approved, lgtm, size/L

#160 pullSubscriptionSecret is optional.
  config/300-storage.yaml
Labels: approved, lgtm, size/XS

#161 Removing unnecessary storage attributes
  pkg/pubsub/adapter/converters/converters.go
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/storage.go
Labels: approved, lgtm, ok-to-test, size/S

#163 Make it so that ops use short labels.
  pkg/operations/labels.go
Labels: approved, lgtm, size/XS

#165 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/apis/v1alpha1/destination.go
  vendor/knative.dev/pkg/testutils/README.md
  vendor/knative.dev/pkg/testutils/clustermanager/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/util.go
  vendor/knative.dev/pkg/testutils/common/common.go
Labels: approved, lgtm, ok-to-test, size/L

#164 Initial schema for Storage events
  config/300-storage.yaml
  pkg/pubsub/adapter/converters/storage.go
  schemas/storage/schema.json
Labels: approved, lgtm, ok-to-test, size/L

#166 Don't set container name in ksvc podspecs
  pkg/reconciler/decorator/resources/decorator.go
  pkg/reconciler/decorator/resources/decorator_test.go
  pkg/reconciler/topic/resources/publisher.go
  pkg/reconciler/topic/resources/publisher_test.go
Labels: approved, lgtm, size/S

#167 Updates to PubSub CloudEvent
  config/300-pullsubscription.yaml
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/storage.go
  schemas/storage/schema.json
Labels: approved, lgtm, ok-to-test, size/M

#170 Use shorter human friendly topic names for topic backed channels.
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/channel/resources/labels.go
  pkg/reconciler/channel/resources/labels_test.go
  pkg/reconciler/channel/resources/names.go
  pkg/reconciler/channel/resources/names_test.go
  pkg/reconciler/channel/resources/topic_test.go
  pkg/reconciler/topic/resources/names.go
Labels: approved, lgtm, size/L

#171 Default the GCS secret if not provided.
  pkg/apis/events/v1alpha1/storage_defaults.go
  pkg/apis/pubsub/v1alpha1/google_cloud_secret_defaults.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults_test.go
  pkg/apis/pubsub/v1alpha1/topic_defaults.go
Labels: approved, lgtm, size/S

#169 Storage follows the duck type for attribute overrides.
  pkg/apis/events/v1alpha1/storage_types.go
  pkg/apis/events/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/storage/storage.go
Labels: approved, lgtm, size/XS

#173 Format markdown
  config/monitoring/metrics/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#176 golang format tools
  pkg/apis/events/v1alpha1/storage_defaults.go
  pkg/apis/messaging/v1alpha1/decorator_validation.go
  pkg/decorator/decorator.go
  pkg/operations/labels.go
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/storage.go
  pkg/reconciler/channel/resources/names.go
  pkg/reconciler/channel/resources/names_test.go
  pkg/reconciler/storage/storage.go
Labels: approved, lgtm, ok-to-test, size/S

#162 Adding CloudEvents Extensions to PullSubscription.
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation.go
  pkg/pubsub/adapter/adapter.go
  pkg/reconciler/decorator/resources/decorator.go
  pkg/reconciler/decorator/resources/decorator_test.go
  pkg/reconciler/pullsubscription/resources/receive_adapter.go
  pkg/reconciler/pullsubscription/resources/receive_adapter_test.go
Labels: approved, lgtm, size/L

#178 Make Channel implement Channelable
  pkg/apis/messaging/v1alpha1/channel_types.go
  pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/testing/channel.go
Labels: approved, lgtm, ok-to-test, size/M

#180 Update release labels in release.sh
  config/201-addressable-resolvers-clusterrole.yaml
  config/201-channelable-manipulator-clusterrole.yaml
  config/transformers/pubsub-push.yaml
  hack/release.sh
Labels: approved, lgtm, size/S

#181 Updating Subscriber's Channel Status based on PullSubscription Status
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/channel/resources/names.go
Labels: approved, lgtm, ok-to-test, size/M

#182 Storage requires bucket
  pkg/apis/events/v1alpha1/storage_types.go
  pkg/apis/events/v1alpha1/storage_validation.go
Labels: approved, lgtm, size/S

#184 Fixing Update PullSubscription
  pkg/reconciler/channel/channel.go
Labels: approved, lgtm, ok-to-test, size/XS

#185 Better Descriptions for Storage schema
  schemas/storage/schema.json
Labels: approved, lgtm, ok-to-test, size/M

#188 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/testutils/clustermanager/boskos/boskos.go
  vendor/knative.dev/pkg/testutils/clustermanager/gke.go
Labels: approved, lgtm, ok-to-test, size/L

#190 Actually default gcsSecret.
  pkg/apis/events/v1alpha1/storage_defaults.go
  pkg/apis/events/v1alpha1/storage_defaults_test.go
Labels: approved, lgtm, size/M

#191 Adding kmeta.ChildName to ops job names.
  pkg/operations/pubsub.go
  pkg/operations/pubsub/names.go
  pkg/operations/pubsub/subscription.go
  pkg/operations/storage/names.go
Labels: approved, lgtm, size/M

#192 Use CloudEventOverrides from Storage and pass down to PullSubscription.
  config/300-storage.yaml
  pkg/apis/events/v1alpha1/storage_types.go
  pkg/operations/storage/notification.go
  pkg/reconciler/storage/resources/pullsubscription.go
  pkg/reconciler/storage/resources/pullsubscription_test.go
  pkg/reconciler/storage/resources/topic.go
  pkg/reconciler/storage/resources/topic_test.go
  pkg/reconciler/storage/storage.go
Labels: approved, lgtm, size/L

#194 Format markdown
  pkg/operations/storage/README.md
Labels: approved, lgtm, ok-to-test, size/S

#193 golang format tools
  cmd/operations/notification/main.go
  cmd/operations/subscription/main.go
  cmd/operations/topic/main.go
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
  pkg/reconciler/storage/storage.go
  pkg/reconciler/topic/topic_test.go
Labels: approved, lgtm, ok-to-test, size/S

#195 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/zipkin.go
Labels: approved, lgtm, ok-to-test, size/M

#197 Fix the document inconsistencies
  config/300-storage.yaml
  pkg/apis/events/v1alpha1/storage_types.go
Labels: approved, lgtm, size/S

#199 Project in topic status
  pkg/operations/job.go
  pkg/operations/pod.go
  pkg/operations/pubsub/subscription.go
  pkg/operations/pubsub/topic.go
  pkg/operations/storage/notification.go
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/storage/storage.go
  pkg/reconciler/topic/topic.go
Labels: approved, lgtm, size/L

#198 Enable installing of eventing for e2e tests.
  test/e2e-common.sh
  test/lib.sh
Labels: approved, lgtm, size/M

#201 Updates to storage schema
  pkg/pubsub/adapter/converters/storage.go
  schemas/storage/schema.json
Labels: approved, lgtm, ok-to-test, size/L

#202 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/testing/zipkin.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, lgtm, ok-to-test, size/L

#203 make Storage conform to duckv1beta1.Source duck type
  pkg/apis/events/v1alpha1/implements_test.go
  pkg/apis/events/v1alpha1/storage_types.go
  pkg/apis/events/v1alpha1/storage_types_test.go
  pkg/apis/events/v1alpha1/storage_validation.go
  pkg/apis/events/v1alpha1/storage_validation_test.go
  pkg/apis/events/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/storage/controller_test.go
  pkg/reconciler/storage/resources/pullsubscription.go
  pkg/reconciler/storage/resources/pullsubscription_test.go
  pkg/reconciler/storage/resources/topic_test.go
  pkg/reconciler/storage/storage.go
Labels: approved, lgtm, size/XL

#206 Storage schema fix
  schemas/storage/schema.json
Labels: approved, lgtm, ok-to-test, size/S

#209 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/test/mako/README.md
  vendor/knative.dev/pkg/test/mako/analyzer.go
  vendor/knative.dev/pkg/test/mako/benchmark.go
  vendor/knative.dev/pkg/test/mako/config.go
  vendor/knative.dev/pkg/test/mako/environment.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/mako/testdata/config-mako.yaml
  vendor/knative.dev/pkg/test/mako/time.go
  vendor/knative.dev/pkg/testutils/clustermanager/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/util.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, ok-to-test, size/XL

#208 Update storage schema
  pkg/pubsub/adapter/converters/storage.go
  schemas/storage/schema.json
Labels: approved, lgtm, ok-to-test, size/L

#210 Controller unit tests
  pkg/apis/events/v1alpha1/storage_lifecycle.go
  pkg/apis/events/v1alpha1/storage_types.go
  pkg/operations/storage/notification.go
  pkg/reconciler/storage/resources/pullsubscription.go
  pkg/reconciler/storage/resources/pullsubscription_test.go
  pkg/reconciler/storage/resources/topic.go
  pkg/reconciler/storage/resources/topic_test.go
  pkg/reconciler/storage/storage.go
  pkg/reconciler/storage/storage_test.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/pullsubscription.go
  pkg/reconciler/testing/storage.go
  pkg/reconciler/testing/topic.go
Labels: approved, lgtm, size/XXL

#211 golang format tools
  test/e2e/test_pull_subscription.go
Labels: approved, lgtm, ok-to-test, size/XS

#212 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/configmap/informed_watcher.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/configmap/static_watcher.go
  vendor/knative.dev/pkg/configmap/watcher.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/mako/README.md
Labels: approved, lgtm, ok-to-test, size/L

#223 golang format tools
  cmd/webhook/main.go
Labels: approved, lgtm, ok-to-test, size/XS

#218 first cut of storage notification example usage
  docs/storage/README.md
  docs/storage/event-display.yaml
  docs/storage/storage.yaml
Labels: approved, lgtm, size/L

#225 Storage notification ut
  pkg/apis/events/v1alpha1/storage_defaults.go
  pkg/apis/events/v1alpha1/storage_defaults_test.go
  pkg/operations/storage/notification.go
  pkg/operations/storage/notification_test.go
  pkg/reconciler/storage/storage.go
  pkg/reconciler/storage/storage_test.go
  pkg/reconciler/testing/storage.go
Labels: approved, lgtm, size/XL

#219 Wire in Logging and Metrics config maps to PullSubscription RA
  Gopkg.lock
  cmd/pubsub/receive_adapter/main.go
  pkg/pubsub/adapter/adapter.go
  pkg/reconciler/pullsubscription/controller.go
  pkg/reconciler/pullsubscription/controller_test.go
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/pullsubscription/resources/config.go
  pkg/reconciler/pullsubscription/resources/config_test.go
  pkg/reconciler/pullsubscription/resources/receive_adapter.go
  pkg/reconciler/pullsubscription/resources/receive_adapter_test.go
Labels: approved, lgtm, size/L

#228 Format markdown
  docs/scheduler/README.md
  docs/storage/README.md
  pkg/operations/scheduler/README.md
Labels: approved, lgtm, ok-to-test, size/M

#227 golang format tools
  pkg/pubsub/adapter/adapter.go
  pkg/reconciler/pullsubscription/controller.go
  pkg/reconciler/pullsubscription/controller_test.go
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/pullsubscription/resources/config.go
  pkg/reconciler/pullsubscription/resources/config_test.go
Labels: approved, lgtm, ok-to-test, size/S

#229 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/doc.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/main.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/third_party/mako/LICENSE
  vendor/knative.dev/pkg/third_party/mako/README.md
  vendor/knative.dev/pkg/third_party/mako/proto/quickstore.proto
  vendor/knative.dev/pkg/third_party/mako/proto/quickstore_go_proto/quickstore.pb.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, lgtm, ok-to-test, size/XXL

#234 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/metrics/gcp_metadata.go
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/metricskey/constants_eventing.go
  vendor/knative.dev/pkg/metrics/metricskey/constants_serving.go
  vendor/knative.dev/pkg/metrics/monitored_resources.go
  vendor/knative.dev/pkg/metrics/monitored_resources_eventing.go
  vendor/knative.dev/pkg/metrics/monitored_resources_serving.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
Labels: approved, lgtm, ok-to-test, size/XL
