Repository google/knative-gcp, pull requests merged in 2019-06, with the labels that each got.

#8 fixing exe on test scripts.
  test/e2e-tests.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#9 Integrate with Injection Informers from knative/pkg
  Gopkg.lock
  Gopkg.toml
  cmd/controller/main.go
  pkg/reconciler/pubsubsource/controller.go
  pkg/reconciler/pubsubsource/controller_test.go
  pkg/reconciler/pubsubsource/pubsubsource_test.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/stats_reporter.go
  pkg/reconciler/testing/factory.go
  vendor/github.com/knative/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/github.com/knative/pkg/codegen/cmd/injection-gen/generators/factory.go
  vendor/github.com/knative/pkg/codegen/cmd/injection-gen/generators/fakeclient.go
  vendor/github.com/knative/pkg/codegen/cmd/injection-gen/generators/fakefactory.go
  vendor/github.com/knative/pkg/codegen/cmd/injection-gen/generators/fakeinformer.go
  vendor/github.com/knative/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/github.com/knative/pkg/injection/README.md
  vendor/github.com/knative/pkg/injection/controllers.go
  vendor/github.com/knative/pkg/injection/doc.go
  vendor/github.com/knative/pkg/injection/interface.go
  vendor/github.com/knative/pkg/injection/sharedmain/main.go
Labels: approved, size/XL

#18 Adjust the dependencies for cloud-run-events.
  Gopkg.lock
  Gopkg.toml
  hack/update-deps.sh
  vendor/github.com/knative/pkg/.github/PULL_REQUEST_TEMPLATE/breaking-change.md
  vendor/github.com/knative/pkg/.github/PULL_REQUEST_TEMPLATE/bug-fix.md
  vendor/github.com/knative/pkg/.github/PULL_REQUEST_TEMPLATE/normal-change.md
  vendor/github.com/knative/pkg/.github/pull-request-template.md
  vendor/github.com/knative/pkg/Gopkg.lock
  vendor/github.com/knative/pkg/hack/update-deps.sh
Labels: approved, lgtm, size/M

#22 Format markdown
  README.md
  docs/pullsubscription/README.md
Labels: approved, lgtm, ok-to-test, size/S

#23 golang format tools
  cmd/pubsub/subscription/main.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
  pkg/reconciler/pullsubscription/resources/names.go
  pkg/reconciler/pullsubscription/resources/receive_adapter.go
  pkg/reconciler/pullsubscription/resources/subscription_ops.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/testing/factory.go
Labels: approved, lgtm, ok-to-test, size/S

#25 golang format tools
  cmd/pubsub/topic/main.go
  pkg/apis/pubsub/v1alpha1/channel_types_test.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types_test.go
Labels: approved, lgtm, ok-to-test, size/S

#30 Format markdown
  pkg/pubsub/operations/README.md
Labels: approved, lgtm, ok-to-test, size/S

#33 moving to api.Status
  pkg/apis/pubsub/v1alpha1/pull_subscription_lifecycle.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_lifecycle_test.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation_test.go
Labels: approved, lgtm, size/L

#36 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/pkg/Gopkg.lock
  vendor/github.com/knative/pkg/kmeta/names.go
  vendor/github.com/knative/pkg/test/helpers/name.go
  vendor/github.com/knative/pkg/test/logstream/doc.go
  vendor/github.com/knative/pkg/test/logstream/interface.go
  vendor/github.com/knative/pkg/test/logstream/kubelogs.go
  vendor/github.com/knative/pkg/test/logstream/null.go
  vendor/github.com/knative/pkg/test/request.go
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-and-episodic-pr-contributors.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-contributors-table.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-companies-histogram.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-histogram.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors.json
  vendor/github.com/knative/test-infra/devstats/metrics/shared/episodic_contributors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/hist_pr_authors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors_data.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/prs_authors.sql
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/knative/test-infra/tools/dep-collector/README.md
Labels: approved, lgtm, ok-to-test, size/XXL

#32 Adding exists to pubsubs base.
  cmd/pubsub/subscription/main.go
  cmd/pubsub/topic/main.go
  config/201-addressable-resolvers-clusterrole.yaml
  config/201-clusterrole.yaml
  config/300-pullsubscription.yaml
  config/500-controller.yaml
  pkg/pubsub/adapter/adapter.go
  pkg/pubsub/operations/actions.go
  pkg/pubsub/operations/names.go
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/pullsubscription/pullsubscription.go
Labels: approved, lgtm, size/L

#41 golang format tools
  pkg/apis/pubsub/v1alpha1/pull_subscription_lifecycle_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#44 Make sure the receive adapter restarts if spec changes.
  pkg/pubsub/adapter/adapter.go
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
Labels: approved, lgtm, size/M

#47 golang format tools
  pkg/apis/pubsub/v1alpha1/topic_types_test.go
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#48 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, ok-to-test, size/S

#49 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/pkg/Gopkg.lock
  vendor/github.com/knative/pkg/configmap/store.go
  vendor/github.com/knative/pkg/configmap/testing/configmap.go
  vendor/github.com/knative/pkg/injection/informers/kubeinformers/rbacv1/role/fake/fake.go
  vendor/github.com/knative/pkg/injection/informers/kubeinformers/rbacv1/role/role.go
  vendor/github.com/knative/pkg/metrics/gcp_metadata.go
  vendor/github.com/knative/pkg/test/logstream/kubelogs.go
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, lgtm, ok-to-test, size/L

#53 Moving topic ops to testable place.
  cmd/pubsub/topic/main.go
  pkg/pubsub/operations/topic.go
Labels: approved, lgtm, size/L

#52 Move subscription job to a testable place.
  cmd/pubsub/subscription/main.go
  pkg/pubsub/operations/subscription.go
Labels: approved, lgtm, size/L

#55 golang format tools
  cmd/pubsub/topic/main.go
  pkg/pubsub/operations/topic.go
Labels: approved, lgtm, ok-to-test, size/XS

#56 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/pkg/Gopkg.lock
  vendor/github.com/knative/pkg/apis/interfaces.go
  vendor/github.com/knative/pkg/testing/resource.go
  vendor/github.com/knative/pkg/webhook/user_info.go
  vendor/github.com/knative/pkg/webhook/webhook.go
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-and-episodic-pr-contributors.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-contributors-table.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-companies-histogram.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-histogram.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors.json
  vendor/github.com/knative/test-infra/devstats/metrics/shared/episodic_contributors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/hist_pr_authors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors_data.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/prs_authors.sql
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, ok-to-test, size/XXL

#54 Adding a wrapper interface to pubsub to allow us to test the pubsub client.
  Gopkg.lock
  cmd/pubsub/subscription/main.go
  pkg/pubsub/client.go
  pkg/pubsub/interfaces.go
  pkg/pubsub/operations/pubsub.go
  pkg/pubsub/operations/subscription.go
  pkg/pubsub/subsciption.go
  pkg/pubsub/test/client.go
  pkg/pubsub/test/subsciption.go
  pkg/pubsub/test/topic.go
  pkg/pubsub/topic.go
Labels: approved, lgtm, size/L

#60 Migrate to knative.dev/pkg
  Gopkg.lock
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/cloudevents/README.md
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/test/README.md
Labels: approved, lgtm, size/M

#61 golang format tools
  cmd/pubsub/push_transformer/main.go
  cmd/pubsub/receive_adapter/main.go
  cmd/pubsub/subscription/main.go
  pkg/pubsub/adapter/adapter.go
Labels: approved, lgtm, ok-to-test, size/XS

#62 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, ok-to-test, size/M

#63 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/DEVELOPMENT.md
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  vendor/knative.dev/pkg/apis/istio/authentication/v1alpha1/policy_types.go
  vendor/knative.dev/pkg/apis/istio/authentication/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/register.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/virtualservice_types.go
  vendor/knative.dev/pkg/apis/testing/conditions.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/main.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/testing/inner_default_resource.go
  vendor/knative.dev/pkg/testing/resource.go
  vendor/knative.dev/pkg/tracing/opencensus.go
Labels: approved, lgtm, ok-to-test, size/M

#65 Allow for sink and transformer to be updated.
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation_test.go
Labels: approved, lgtm, size/L

#66 Adding send mode to Receive Adapter for PullSubscription.
  cmd/pubsub/push_transformer/main.go
  cmd/pubsub/receive_adapter/main.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults_test.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types_test.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation_test.go
  pkg/pubsub/adapter/adapter.go
  pkg/pubsub/adapter/adapter_test.go
  pkg/pubsub/adapter/push.go
  pkg/pubsub/adapter/push_test.go
  pkg/pubsub/transformer/transformer.go
  pkg/reconciler/pullsubscription/resources/receive_adapter.go
  pkg/reconciler/pullsubscription/resources/receive_adapter_test.go
Labels: approved, lgtm, size/XL
