Repository google/knative-gcp, pull requests merged in 2019-11, with the labels that each got.

#385 Do not attempt to create job to delete topic/subscription if they don't exist
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
  pkg/reconciler/topic/topic.go
  pkg/reconciler/topic/topic_test.go
Labels: approved, lgtm, size/L

#396 Adding Span From TraceParent only for Channels
  pkg/pubsub/adapter/adapter.go
  pkg/pubsub/adapter/adapter_test.go
Labels: approved, lgtm, size/M

#397 Adding Span From TraceParent only for Channels (#396)
  pkg/pubsub/adapter/adapter.go
  pkg/pubsub/adapter/adapter_test.go
Labels: approved, lgtm, size/M

#398 Add kodata to all commands
  cmd/controller/kodata/HEAD
  cmd/controller/kodata/LICENSE
  cmd/controller/kodata/VENDOR-LICENSE
  cmd/controller/kodata/refs
  cmd/decorator/kodata/HEAD
  cmd/decorator/kodata/LICENSE
  cmd/decorator/kodata/VENDOR-LICENSE
  cmd/decorator/kodata/refs
  cmd/operations/notification/kodata/HEAD
  cmd/operations/notification/kodata/LICENSE
  cmd/operations/notification/kodata/VENDOR-LICENSE
  cmd/operations/notification/kodata/refs
  cmd/operations/scheduler/kodata/HEAD
  cmd/operations/scheduler/kodata/LICENSE
  cmd/operations/scheduler/kodata/VENDOR-LICENSE
  cmd/operations/scheduler/kodata/refs
  cmd/operations/subscription/kodata/HEAD
  cmd/operations/subscription/kodata/LICENSE
  cmd/operations/subscription/kodata/VENDOR-LICENSE
  cmd/operations/subscription/kodata/refs
  cmd/operations/topic/kodata/HEAD
  cmd/operations/topic/kodata/LICENSE
  cmd/operations/topic/kodata/VENDOR-LICENSE
  cmd/operations/topic/kodata/refs
  cmd/pubsub/publisher/kodata/HEAD
  cmd/pubsub/publisher/kodata/LICENSE
  cmd/pubsub/publisher/kodata/VENDOR-LICENSE
  cmd/pubsub/publisher/kodata/refs
  cmd/pubsub/receive_adapter/kodata/HEAD
  cmd/pubsub/receive_adapter/kodata/LICENSE
  cmd/pubsub/receive_adapter/kodata/VENDOR-LICENSE
  cmd/pubsub/receive_adapter/kodata/refs
  cmd/webhook/kodata/HEAD
  cmd/webhook/kodata/LICENSE
  cmd/webhook/kodata/VENDOR-LICENSE
  cmd/webhook/kodata/refs
Labels: approved, lgtm, size/M

#395 Set up performance test infra
  Gopkg.lock
  Gopkg.toml
  test/performance/benchmarks/broker-pubsub/cluster.yaml
  test/performance/benchmarks/broker-pubsub/continuous/100-broker-pubsub-setup.yaml
  test/performance/benchmarks/broker-pubsub/continuous/200-broker-pubsub.yaml
  test/performance/benchmarks/broker-pubsub/dev.config
  test/performance/benchmarks/channel-pubsub/cluster.yaml
  test/performance/benchmarks/channel-pubsub/continuous/100-channel-perf-setup.yaml
  test/performance/benchmarks/channel-pubsub/continuous/200-channel-perf.yaml
  test/performance/benchmarks/channel-pubsub/dev.config
  test/performance/performance-tests.sh
  vendor/google.golang.org/api/container/v1beta1/container-gen.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XXL

#335 Switch to desugared logger.
  cmd/webhook/main.go
Labels: approved, lgtm, size/S

#387 E2E tests of Knative Serving as eventing consumer
  Gopkg.lock
  test/cmd/receiver/main.go
  test/cmd/sender/main.go
  test/e2e-common.sh
  test/e2e/config/istio-patch/istio-knative-extras.yaml
  test/e2e/config/pubsub_broker/100-broker.yaml
  test/e2e/config/pubsub_broker/200-trigger.yaml
  test/e2e/config/pubsub_sender/sender.yaml
  test/e2e/e2e_test.go
  test/e2e/test_broker_pubsub.go
Labels: approved, lgtm, size/XL

#400 Update OWNERS to remove xooglers
  OWNERS
Labels: approved, lgtm, ok-to-test, size/XS

#403 Setting "application/octet-stream" as ContentType for PubSub
  pkg/pubsub/adapter/adapter_test.go
  pkg/pubsub/adapter/converters/pubsub.go
Labels: approved, lgtm, size/XS

#404 Setting "application/octet-stream" as ContentType for PubSub
  pkg/pubsub/adapter/adapter_test.go
  pkg/pubsub/adapter/converters/pubsub.go
Labels: approved, lgtm, size/XS

#405 Fix performance tests
  test/performance/benchmarks/broker-pubsub/continuous/200-broker-pubsub.yaml
  test/performance/benchmarks/channel-pubsub/continuous/200-channel-perf.yaml
  test/performance/performance-tests.sh
Labels: approved, lgtm, size/L

#407 Rename clusterrole in 201-channelable-manipulator-clusterrole.yaml
  config/201-channelable-manipulator-clusterrole.yaml
Labels: approved, lgtm, size/XS

#408 Rename clusterrole in 201-channelable-manipulator-clusterrole.yaml(cherry-pick)
  config/201-channelable-manipulator-clusterrole.yaml
Labels: approved, lgtm, size/XS

#409 Add kodata to all commands
  cmd/controller/kodata/HEAD
  cmd/controller/kodata/LICENSE
  cmd/controller/kodata/VENDOR-LICENSE
  cmd/controller/kodata/refs
  cmd/decorator/kodata/HEAD
  cmd/decorator/kodata/LICENSE
  cmd/decorator/kodata/VENDOR-LICENSE
  cmd/decorator/kodata/refs
  cmd/operations/notification/kodata/HEAD
  cmd/operations/notification/kodata/LICENSE
  cmd/operations/notification/kodata/VENDOR-LICENSE
  cmd/operations/notification/kodata/refs
  cmd/operations/scheduler/kodata/HEAD
  cmd/operations/scheduler/kodata/LICENSE
  cmd/operations/scheduler/kodata/VENDOR-LICENSE
  cmd/operations/scheduler/kodata/refs
  cmd/operations/subscription/kodata/HEAD
  cmd/operations/subscription/kodata/LICENSE
  cmd/operations/subscription/kodata/VENDOR-LICENSE
  cmd/operations/subscription/kodata/refs
  cmd/operations/topic/kodata/HEAD
  cmd/operations/topic/kodata/LICENSE
  cmd/operations/topic/kodata/VENDOR-LICENSE
  cmd/operations/topic/kodata/refs
  cmd/pubsub/publisher/kodata/HEAD
  cmd/pubsub/publisher/kodata/LICENSE
  cmd/pubsub/publisher/kodata/VENDOR-LICENSE
  cmd/pubsub/publisher/kodata/refs
  cmd/pubsub/receive_adapter/kodata/HEAD
  cmd/pubsub/receive_adapter/kodata/LICENSE
  cmd/pubsub/receive_adapter/kodata/VENDOR-LICENSE
  cmd/pubsub/receive_adapter/kodata/refs
  cmd/webhook/kodata/HEAD
  cmd/webhook/kodata/LICENSE
  cmd/webhook/kodata/VENDOR-LICENSE
  cmd/webhook/kodata/refs
Labels: approved, lgtm, size/M

#410 Fix performance tests setup
  test/e2e-common.sh
  test/lib.sh
  test/performance/benchmarks/broker-pubsub/cluster.yaml
  test/performance/benchmarks/channel-pubsub/cluster.yaml
  test/performance/benchmarks/channel-pubsub/continuous/100-channel-perf-setup.yaml
  test/performance/performance-tests.sh
Labels: approved, lgtm, size/L

#412 Update vendor/knative.dev/test-infra
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, lgtm, size/M

#420 Adding templates for creating bugs and new features
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/issue-template.md
  .github/pull-request-template.md
Labels: approved, lgtm, size/M
