Repository google/knative-gcp, pull requests merged in 2019-07, with the labels that each got.

#74 Auto-update dependencies
  Gopkg.lock
Labels: approved, lgtm, ok-to-test, size/XS

#75 Use desugared loggers in the pubsub main.go files
  cmd/pubsub/receive_adapter/main.go
  cmd/pubsub/subscription/main.go
  cmd/pubsub/topic/main.go
Labels: approved, lgtm, size/S

#81 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
Labels: approved, lgtm, ok-to-test, size/XS

#84 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/limitrange/fake/fake.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/limitrange/limitrange.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/resourcequota/fake/fake.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/resourcequota/resourcequota.go
Labels: approved, lgtm, ok-to-test, size/L

#90 Fix a minor typo and update a comment for finalizers.
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/topic/topic.go
Labels: approved, lgtm, size/S

#93 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, ok-to-test, size/L

#94 Moving pull sub mode annotation into spec.
  config/300-pullsubscription.yaml
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults_test.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types_test.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation_test.go
  pkg/pubsub/adapter/adapter.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
  pkg/reconciler/pullsubscription/resources/receive_adapter.go
Labels: approved, lgtm, size/L

#96 Remove service account from PullSubscription
  cmd/webhook/main.go
  config/300-pullsubscription.yaml
  pkg/apis/pubsub/v1alpha1/pull_subscription_types.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation_test.go
  pkg/pubsub/operations/pod.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
  pkg/reconciler/pullsubscription/resources/receive_adapter.go
  pkg/reconciler/pullsubscription/resources/receive_adapter_test.go
Labels: approved, lgtm, size/L

#95 Default Secret in webhook, not controller.
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults_test.go
  pkg/pubsub/operations/pod.go
  pkg/reconciler/pullsubscription/resources/receive_adapter.go
Labels: approved, lgtm, size/M

#51 Adding subscription config into subscription job.
  cmd/pubsub/topic/main.go
  config/300-pullsubscription.yaml
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults_test.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation.go
  pkg/apis/pubsub/v1alpha1/zz_generated.deepcopy.go
  pkg/pubsub/interfaces.go
  pkg/pubsub/operations/subscription.go
  pkg/pubsub/operations/topic.go
  pkg/pubsub/subsciption.go
  pkg/pubsub/test/subsciption.go
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
  pkg/reconciler/testing/pullsubscription.go
Labels: approved, lgtm, size/L

#99 Adding OpenAPI enum for Topic, default for PullSubscription.
  config/300-pullsubscription.yaml
  config/300-topic.yaml
Labels: approved, lgtm, size/XS

#103 Update to new breaking change for stats reporter in webhook.
  Gopkg.lock
  cmd/webhook/main.go
  vendor/knative.dev/pkg/webhook/user_info.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, lgtm, size/M

#107 Updated the vendored test-infra repo
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/M

#91 always use equality.Semantic.DeepEqual
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/topic/topic.go
Labels: approved, lgtm, size/XS

#108 Enable Sink and Transformer to be URIs in the spec.
  Gopkg.lock
  config/300-pullsubscription.yaml
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults_test.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types_test.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation_test.go
  pkg/apis/pubsub/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
  pkg/reconciler/pullsubscription/resources/names.go
  pkg/reconciler/testing/pullsubscription.go
Labels: approved, lgtm, size/XL

#110 golang format tools
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_defaults_test.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types_test.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_validation_test.go
  pkg/reconciler/pullsubscription/resources/names.go
Labels: approved, lgtm, ok-to-test, size/S

#115 Adding a LICENSE.
  LICENSE
Labels: approved, lgtm, size/L
