Repository google/knative-gcp, pull requests merged in 2019-09, with the labels that each got.

#237 golang format tools
  pkg/apis/events/v1alpha1/scheduler_types.go
  pkg/operations/pod_test.go
  pkg/reconciler/pubsub_reconciler.go
Labels: approved, lgtm, ok-to-test, size/XS

#238 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/injection/informers/kubeinformers/batchv1beta1/cronjob/cronjob.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/batchv1beta1/cronjob/fake/fake.go
  vendor/knative.dev/pkg/reconciler/OWNERS
  vendor/knative.dev/pkg/reconciler/testing/table.go
Labels: approved, lgtm, ok-to-test, size/L

#236 Update to duck/v1 for status.
  Gopkg.lock
  pkg/apis/duck/v1alpha1/pubsub_types.go
  pkg/apis/events/v1alpha1/scheduler_types.go
  pkg/apis/events/v1alpha1/scheduler_validation_test.go
  pkg/apis/events/v1alpha1/storage_types.go
  pkg/apis/events/v1alpha1/storage_validation_test.go
  pkg/apis/messaging/v1alpha1/channel_lifecycle.go
  pkg/apis/messaging/v1alpha1/channel_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/channel_types.go
  pkg/apis/messaging/v1alpha1/decorator_lifecycle.go
  pkg/apis/messaging/v1alpha1/decorator_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/decorator_types.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_types.go
  pkg/apis/pubsub/v1alpha1/topic_types.go
  pkg/reconciler/resources/pullsubscription_test.go
  pkg/reconciler/resources/topic_test.go
  pkg/reconciler/topic/topic_test.go
  test/e2e/lifecycle.go
Labels: approved, lgtm, size/L

#239 Auto-update dependencies
  Gopkg.lock
  pkg/client/injection/informers/events/factory/eventsfactory.go
  pkg/client/injection/informers/events/factory/fake/fake.go
  pkg/client/injection/informers/messaging/factory/fake/fake.go
  pkg/client/injection/informers/messaging/factory/messagingfactory.go
  pkg/client/injection/informers/pubsub/factory/fake/fake.go
  pkg/client/injection/informers/pubsub/factory/pubsubfactory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakefactory.go
  vendor/knative.dev/pkg/injection/context.go
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/injection/informers/apiextinformers/factory/factory.go
  vendor/knative.dev/pkg/injection/informers/apiextinformers/factory/fake/fake.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/factory/factory.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/factory/fake/fake.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
Labels: approved, lgtm, ok-to-test, size/L

#240 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/client/injection/informers/authentication/factory/authenticationfactory.go
  vendor/knative.dev/pkg/client/injection/informers/authentication/factory/fake/fake.go
  vendor/knative.dev/pkg/client/injection/informers/istio/factory/fake/fake.go
  vendor/knative.dev/pkg/client/injection/informers/istio/factory/istiofactory.go
Labels: approved, lgtm, ok-to-test, size/M

#241 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/ghutil/fakeghutil/fakeghutil.go
  vendor/knative.dev/pkg/test/ghutil/issue.go
  vendor/knative.dev/pkg/test/ghutil/pullrequest.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/knative.dev/pkg/test/mako/alerter/slack/message.go
  vendor/knative.dev/pkg/test/prometheus/prometheus.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/slackutil/messaging.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
Labels: approved, lgtm, ok-to-test, size/XXL

#242 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/reconciler/testing/context.go
Labels: approved, lgtm, ok-to-test, size/S

#244 fix json error injection.
  pkg/decorator/decorator.go
  pkg/pubsub/adapter/adapter.go
  pkg/reconciler/decorator/decorator.go
  pkg/reconciler/decorator/resources/decorator.go
  pkg/reconciler/decorator/resources/decorator_test.go
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
  pkg/reconciler/pullsubscription/resources/receive_adapter.go
  pkg/reconciler/pullsubscription/resources/receive_adapter_test.go
Labels: approved, lgtm, size/L

#246 Storage control plane metrics
  pkg/reconciler/stats_reporter.go
Labels: approved, lgtm, ok-to-test, size/XS

#247 pubsub reconciler and pod_test unit tests
  pkg/operations/pod_test.go
  pkg/reconciler/pubsub_controller.go
  pkg/reconciler/pubsub_reconciler.go
  pkg/reconciler/pubsub_reconciler_test.go
Labels: approved, lgtm, size/XL

#245 Fix minor doc issue, update to enable apis.
  docs/scheduler/README.md
  docs/storage/README.md
Labels: approved, lgtm, size/S

#251 Adding Storage and PullSubscription event types descriptions
  config/300-pullsubscription.yaml
  config/300-storage.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#253 Pubsubable into an interface for easier use.
  pkg/apis/events/v1alpha1/scheduler_types.go
  pkg/apis/events/v1alpha1/storage_types.go
  pkg/duck/pubsubable.go
  pkg/reconciler/pubsub_reconciler.go
  pkg/reconciler/pubsub_reconciler_test.go
  pkg/reconciler/scheduler/scheduler.go
  pkg/reconciler/storage/storage.go
Labels: approved, lgtm, size/L

#262 golang format tools
  cmd/pubsub/receive_adapter/main.go
  pkg/pubsub/adapter/adapter.go
  pkg/pubsub/adapter/stats_reporter.go
Labels: approved, lgtm, ok-to-test, size/S

#263 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/openzipkin/zipkin-go/LICENSE
  vendor/github.com/openzipkin/zipkin-go/model/annotation.go
  vendor/github.com/openzipkin/zipkin-go/model/doc.go
  vendor/github.com/openzipkin/zipkin-go/model/endpoint.go
  vendor/github.com/openzipkin/zipkin-go/model/kind.go
  vendor/github.com/openzipkin/zipkin-go/model/span.go
  vendor/github.com/openzipkin/zipkin-go/model/span_id.go
  vendor/github.com/openzipkin/zipkin-go/model/traceid.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/source/source_stats_reporter.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/README.md
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/boskos/boskos.go
  vendor/knative.dev/pkg/testutils/clustermanager/boskos/fake/fake.go
  vendor/knative.dev/pkg/testutils/clustermanager/gke.go
  vendor/knative.dev/pkg/tracing/opencensus.go
Labels: approved, lgtm, ok-to-test, size/XL

#265 better errors, return err instead of nil on failures
  pkg/reconciler/pubsub/reconciler.go
Labels: approved, lgtm, size/S

#264 Updating pkg to latest for 0.9 release.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
Labels: approved, lgtm, size/S

#266 Metrics: passing the ResourceGroup to ReceiveAdapter
  pkg/pubsub/adapter/adapter.go
  pkg/pubsub/adapter/converters/converters.go
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/storage.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/channel/resources/annotations.go
  pkg/reconciler/channel/resources/annotations_test.go
  pkg/reconciler/channel/resources/pullsubscription.go
  pkg/reconciler/pubsub_reconciler.go
  pkg/reconciler/pubsub_reconciler_test.go
  pkg/reconciler/pullsubscription/resources/receive_adapter.go
  pkg/reconciler/pullsubscription/resources/receive_adapter_test.go
  pkg/reconciler/resources/pullsubscription.go
  pkg/reconciler/resources/pullsubscription_test.go
  pkg/reconciler/scheduler/scheduler.go
  pkg/reconciler/scheduler/scheduler_test.go
  pkg/reconciler/storage/storage.go
  pkg/reconciler/storage/storage_test.go
  pkg/reconciler/testing/pullsubscription.go
Labels: approved, lgtm, size/L

#267 CloudEvents SDK version
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/pubsub/codec.go
Labels: approved, lgtm, size/S

#270 adding a top README.md level link to the new sources.
  README.md
Labels: approved, lgtm, size/S

#271 Adding Title to Source Registry
  config/300-pullsubscription.yaml
  config/300-scheduler.yaml
  config/300-storage.yaml
Labels: approved, lgtm, size/S

#274 Only fail if the project ID is missing when doing create
  pkg/operations/storage/notification.go
  pkg/operations/storage/notification_test.go
Labels: approved, lgtm, ok-to-test, size/M

#277 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, lgtm, ok-to-test, size/S

#276 golang format tools
  pkg/operations/storage/notification_test.go
Labels: approved, lgtm, ok-to-test, size/S

#279 fix markdown to be correctly formatted.
  config/monitoring/metrics/README.md
  docs/pubsub/README.md
Labels: approved, lgtm, size/L

#278 force events to be v03 in channel.
  pkg/pubsub/publisher/publisher.go
Labels: approved, lgtm, size/XS

#284 updated Status.ObservedGeneration for pullsubscription and storage
  pkg/reconciler/pullsubscription/pullsubscription.go
  pkg/reconciler/pullsubscription/pullsubscription_test.go
  pkg/reconciler/storage/storage.go
  pkg/reconciler/storage/storage_test.go
  pkg/reconciler/testing/pullsubscription.go
  pkg/reconciler/testing/storage.go
Labels: approved, lgtm, ok-to-test, size/L

#285 unpin pkg, point back to master now that the release is cut.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/client.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/metrics.go
  vendor/knative.dev/pkg/metrics/metricskey/constants_eventing.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/monitored_resources_eventing.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/metrics/workqueue.go
  vendor/knative.dev/pkg/reconciler/testing/generate_name_reactor.go
  vendor/knative.dev/pkg/source/source_stats_reporter.go
  vendor/knative.dev/pkg/testutils/clustermanager/boskos/fake/fake.go
  vendor/knative.dev/pkg/testutils/clustermanager/client.go
  vendor/knative.dev/pkg/testutils/clustermanager/doc.go
  vendor/knative.dev/pkg/testutils/clustermanager/gke.go
Labels: approved, lgtm, size/XL

#282 ban the importing of aliased repos.
  test/banned_deps_test.go
Labels: approved, lgtm, size/M

#286 golang format tools
  pkg/reconciler/pullsubscription/pullsubscription_test.go
  pkg/reconciler/storage/storage_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#283 E2E test for the storage source/importer
  Gopkg.lock
  test/cmd/storage_target/main.go
  test/e2e-common.sh
  test/e2e/config/storage_test/storage.yaml
  test/e2e/config/storage_test/target.yaml
  test/e2e/e2e_test.go
  test/e2e/test_storage.go
Labels: approved, lgtm, ok-to-test, size/L

#293 golang format tools
  test/e2e/test_storage.go
Labels: approved, lgtm, ok-to-test, size/XS

#296 install instructions without ko
  docs/install/README.md
Labels: approved, lgtm, size/S

#299 remove skip to run E2E test for storage source
  test/e2e/e2e_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#300 Format markdown
  config/monitoring/metrics/README.md
Labels: approved, lgtm, ok-to-test, size/S

#305 Source Registry
  config/300-pullsubscription.yaml
  config/300-scheduler.yaml
  config/300-storage.yaml
Labels: approved, lgtm, size/L

#307 Fix misleading storage op error.
  pkg/operations/storage/notification.go
Labels: approved, lgtm, ok-to-test, size/XS
