Repository google/knative-gcp, pull requests merged in 2020-10, with the labels that each got.

#1703 Finalize resource as best effort and always mark topic as ready
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#1791 Add danyinggu to reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1795 Add danyinggu to approver list
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1793 Add zhongduo Jimmy Lin as an approver
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1794 Add tommyreddad to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1790 Adjusting the large payload unit test to prevent occasional timeouts
  pkg/broker/ingress/handler_test.go
Labels: approved, cla: yes, lgtm, size/S

#1792 Code cleanup in trigger and broker controller
  pkg/reconciler/broker/controller.go
  pkg/reconciler/trigger/controller.go
  pkg/utils/metadata.go
Labels: approved, cla: yes, lgtm, size/M

#1761 Remove gpubsub in sources
  pkg/reconciler/intevents/pullsubscription/keda/controller.go
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/intevents/pullsubscription/reconciler.go
  pkg/reconciler/intevents/pullsubscription/static/controller.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription_test.go
  pkg/reconciler/intevents/topic/controller.go
  pkg/reconciler/intevents/topic/topic.go
  pkg/reconciler/intevents/topic/topic_test.go
  pkg/reconciler/testing/pstest.go
  pkg/reconciler/utils/pubsub/types.go
Labels: approved, cla: yes, lgtm, size/XXL

#1802 [Automated] Fix misspellings
  pkg/reconciler/testing/pstest.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1809 Add test with data residency configuration to topic_test.go
  pkg/reconciler/intevents/topic/topic_test.go
Labels: approved, cla: yes, lgtm, size/M

#1805 Unpin github.com/jmespath/go-jmespath
  go.mod
  go.sum
  vendor/github.com/jmespath/go-jmespath/.travis.yml
  vendor/github.com/jmespath/go-jmespath/README.md
  vendor/github.com/jmespath/go-jmespath/api.go
  vendor/github.com/jmespath/go-jmespath/go.mod
  vendor/github.com/jmespath/go-jmespath/go.sum
  vendor/github.com/jmespath/go-jmespath/parser.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1816 Add tayarani as approver
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1798 Report event_count metric in Broker Ingress for invalid events
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
  pkg/metrics/tags.go
  pkg/metrics/tags_test.go
Labels: approved, cla: yes, lgtm, size/M

#1806 Fix prerequisite section of CloudBuildSource doc
  docs/examples/cloudbuildsource/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1817 Fix typo in flag name, workloadIndentity -> workloadIdentity.
  test/e2e-wi-tests.sh
  test/e2e/README.md
  test/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/XS

#1818 [Automated] Format markdown
  docs/examples/cloudbuildsource/README.md
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1799 Use single function to resolve project ID
  cmd/broker/fanout/main.go
  cmd/broker/ingress/main.go
  cmd/broker/retry/main.go
  cmd/pubsub/publisher/main.go
  cmd/pubsub/receive_adapter/main.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/events/scheduler/scheduler.go
  pkg/reconciler/events/storage/storage.go
  pkg/reconciler/identity/reconciler.go
  pkg/reconciler/intevents/pullsubscription/reconciler.go
  pkg/reconciler/intevents/topic/topic.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/trigger.go
  pkg/utils/metadata.go
  pkg/utils/metadata_test.go
  test/test_images/probe_helper/main.go
Labels: approved, cla: yes, lgtm, size/L

#1823 added missing source observer role in knative-gcp
  config/201-source-observer-clusterrole.yaml
  config/core/roles/clusterrole.yaml
  config/core/roles/clusterrolebinding.yaml
  config/core/roles/source-observer-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/M

#1825 added missing source obersever role in knative-gcp in 0.17(cherry pick #1823)
  config/201-source-observer-clusterrole.yaml
  config/core/roles/clusterrole.yaml
  config/core/roles/clusterrolebinding.yaml
  config/core/roles/source-observer-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/M

#1826 added missing source obersever role in knative-gcp in 0.18(cherry pick #1823)
  config/201-source-observer-clusterrole.yaml
  config/core/roles/clusterrole.yaml
  config/core/roles/clusterrolebinding.yaml
  config/core/roles/source-observer-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/M

#1831 Include rustemb to the list of reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1828 Adjust default brokercell parameters to match latest performance target
  cmd/broker/fanout/main.go
  cmd/broker/retry/main.go
  pkg/apis/intevents/v1alpha1/brokercell_defaults.go
  pkg/reconciler/brokercell/testingdata/fanout_deployment.yaml
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_restart_annotation.yaml
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_restart_annotation.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/retry_hpa.yaml
Labels: approved, cla: yes, lgtm, size/M

#1834 Fix KO_FLAGS parameter issue in hack/release.sh
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1836 added e2e test for trigger dependency annotation
  test/e2e/e2e_test.go
  test/e2e/test_trigger_dependency_annotation.go
Labels: approved, cla: yes, lgtm, size/L

#1838 Update documentation for using MTBroker with Pub/Sub channel
  docs/install/config-br-default-channel.yaml
  docs/install/install-broker-with-pubsub-channel.md
Labels: approved, cla: yes, lgtm, size/S

#1840 Allow the unit test to run locally.
  test/test_images/probe_helper/probe_helper_test.go
Labels: approved, cla: yes, lgtm, size/L

#1845 Skip conformance tests
  test/e2e-conformance-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1843 Lower retry cpu request to 1G
  pkg/apis/intevents/v1alpha1/brokercell_defaults.go
  pkg/reconciler/brokercell/testingdata/retry_deployment.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_restart_annotation.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_status.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1848 Remove deprecated test images
  hack/tools.go
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
  vendor/knative.dev/eventing/test/test_images/transformevents/pod.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1847 Enable conformance tests
  test/e2e-conformance-tests.sh
  test/e2e-tests.sh
  test/e2e-wi-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1830 Properly cleanup test server and client in ingress TestHandler
  pkg/broker/ingress/handler_test.go
Labels: approved, cla: yes, lgtm, size/S

#1853 Remove v1alpha1 support for Channel
  cmd/webhook/main.go
  config/core/configmaps/br-default-channel.yaml
  config/core/resources/channel.yaml
  hack/update-codegen.sh
  pkg/apis/messaging/v1alpha1/channel_conversion.go
  pkg/apis/messaging/v1alpha1/channel_conversion_test.go
  pkg/apis/messaging/v1alpha1/channel_defaults.go
  pkg/apis/messaging/v1alpha1/channel_defaults_test.go
  pkg/apis/messaging/v1alpha1/channel_lifecycle.go
  pkg/apis/messaging/v1alpha1/channel_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/channel_types.go
  pkg/apis/messaging/v1alpha1/channel_types_test.go
  pkg/apis/messaging/v1alpha1/channel_validation.go
  pkg/apis/messaging/v1alpha1/channel_validation_test.go
  pkg/apis/messaging/v1alpha1/doc.go
  pkg/apis/messaging/v1alpha1/register.go
  pkg/apis/messaging/v1alpha1/register_test.go
  pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/channel.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/fake/fake_channel.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/fake/fake_messaging_client.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/messaging_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/messaging/interface.go
  pkg/client/informers/externalversions/messaging/v1alpha1/channel.go
  pkg/client/informers/externalversions/messaging/v1alpha1/interface.go
  pkg/client/injection/informers/messaging/v1alpha1/channel/channel.go
  pkg/client/injection/informers/messaging/v1alpha1/channel/fake/fake.go
  pkg/client/listers/messaging/v1alpha1/channel.go
  pkg/client/listers/messaging/v1alpha1/expansion_generated.go
  test/conformance/main_test.go
  test/e2e-conformance-tests.sh
  test/e2e-tests.sh
  test/e2e/main_test.go
  test/lib/resources/constants.go
  test/lib/typemetas.go
Labels: approved, cla: yes, lgtm, size/XXL

#1855 Update KSA annotation in Identity reconciler
  pkg/reconciler/identity/reconciler.go
  pkg/reconciler/identity/reconciler_test.go
  pkg/reconciler/testing/service_account.go
Labels: approved, cla: yes, lgtm, size/M

#1861 Remove v1alpha1 versions from CRDs
  config/core/resources/channel.yaml
  config/core/resources/cloudauditlogssource.yaml
  config/core/resources/cloudbuildsource.yaml
  config/core/resources/cloudpubsubsource.yaml
  config/core/resources/cloudschedulersource.yaml
  config/core/resources/cloudstoragesource.yaml
  config/core/resources/pullsubscription.yaml
  config/core/resources/topic.yaml
Labels: approved, cla: yes, lgtm, size/L

#1864 Add rollout restart time annotation to Brokercell and update Brokercell deployments
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/brokercell/resources/args.go
  pkg/reconciler/brokercell/resources/deployments.go
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_restart_annotation.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment_with_restart_annotation.yaml
  pkg/reconciler/brokercell/testingdata/read_yaml.go
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_restart_annotation.yaml
Labels: approved, cla: yes, lgtm, size/L

#1869 Fix a typo when checking duplicate events in upgrade test
  test/upgrade/prober/verify.go
Labels: approved, cla: yes, lgtm, size/XS

#1870 Automatically succeed on conformance tests (release-0.18)
  test/e2e-conformance-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1874 [release-0.18] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/broker/v1beta1/broker/reconciler.go
  pkg/client/injection/reconciler/broker/v1beta1/trigger/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudauditlogssource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudbuildsource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudpubsubsource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudschedulersource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudstoragesource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudauditlogssource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudbuildsource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudpubsubsource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudschedulersource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudstoragesource/reconciler.go
  pkg/client/injection/reconciler/intevents/v1/pullsubscription/reconciler.go
  pkg/client/injection/reconciler/intevents/v1/topic/reconciler.go
  pkg/client/injection/reconciler/intevents/v1alpha1/brokercell/reconciler.go
  pkg/client/injection/reconciler/intevents/v1beta1/pullsubscription/reconciler.go
  pkg/client/injection/reconciler/intevents/v1beta1/topic/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_types.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/parallel_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/sequence_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/trigger_no_broker_test_helper.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/dropevents/receiver.go
  vendor/knative.dev/eventing/test/lib/k8s_events.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_log.go
  vendor/knative.dev/eventing/test/lib/recordevents/logger_vent/logger.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/observer.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/reply.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/doc.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/recorder.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/resources/kube.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/eventing/test/test_images/recordevents/eventstore.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#1877 Leverage test-infra go_update_deps
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/M

#1871 Automatically succeed on conformance tests (release-0.17)
  test/e2e-conformance-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1872 Automatically succeed on conformance tests (release-0.16)
  test/e2e-conformance-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1873 Automatically succeed on conformance tests (release-0.15b)
  test/e2e-conformance-tests.sh
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/M

#1878 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/gke/client.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/main.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1881 Explicitly depend on knative.dev/hack
  go.mod
  hack/tools.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS
