Repository google/knative-gcp, pull requests merged in 2020-05, with the labels that each got.

#949 Add broker ingress metrics
  cmd/broker/ingress/main.go
  config/broker/deployments/broker.yaml
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
  pkg/broker/ingress/stats_reporter.go
  pkg/broker/ingress/stats_reporter_test.go
Labels: approved, cla: yes, lgtm, size/L

#987 Change CronJobSource to PingSource.
  docs/examples/channel/README.md
  docs/examples/channel/source.yaml
Labels: approved, cla: yes, lgtm, size/S

#985 Update stackdriver e2e testing
  test/e2e/e2e_test.go
  test/e2e/lib/broker.go
  test/e2e/lib/constants.go
  test/e2e/lib/lifecycle.go
  test/e2e/test_broker_pubsub.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#993 [master] Format markdown
  docs/examples/channel/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#979 Update installation instructions for v0.14.0
  docs/install/install-knative-gcp.md
  docs/install/pubsub-service-account.md
Labels: approved, cla: yes, lgtm, size/S

#999 [master] Format markdown
  docs/install/install-knative-gcp.md
  docs/install/pubsub-service-account.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1001 Skip TestCloudAuditLogsSource and TestCloudStorageSource in e2e-wi-tests
  test/e2e/e2e_test.go
Labels: approved, cla: yes, lgtm, size/XS

#973 added e2e for gcp broker which sends and forwards events, refactored …
  hack/init_cloud_storage_source.sh
  hack/init_control_plane.sh
  hack/init_control_plane_gke.sh
  hack/init_data_plane.sh
  hack/lib.sh
  test/e2e-common.sh
  test/e2e-secret-tests.sh
  test/e2e-tests.sh
  test/e2e-wi-tests.sh
  test/e2e/e2e_test.go
  test/e2e/test_gcp_broker.go
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/XXL

#989 Prefix PullSubscription and Topic testing functions with PubSub
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/build/build_test.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/messaging/channel/channel_test.go
  pkg/reconciler/pubsub/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/pubsub/pullsubscription/keda/resources/scaled_object_test.go
  pkg/reconciler/pubsub/pullsubscription/static/pullsubscription_test.go
  pkg/reconciler/pubsub/reconciler_test.go
  pkg/reconciler/pubsub/topic/topic_test.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/pubsub_pullsubscription.go
  pkg/reconciler/testing/pubsub_topic.go
  test/e2e/test_pullsubscription.go
Labels: approved, cla: yes, lgtm, size/XXL

#892 update the docs of how to run e2e tests
  docs/examples/cloudschedulersource/README.md
  docs/install/patch-config-tracing-configmap-with-zipkin.yaml
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, size/L

#1007 [master] Format markdown
  docs/examples/cloudschedulersource/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1010 Update knative.dev/eventing
  go.mod
  go.sum
  pkg/apis/messaging/v1alpha1/channel_conversion_test.go
  pkg/reconciler/messaging/channel/channel.go
  pkg/reconciler/messaging/channel/channel_test.go
  pkg/reconciler/testing/channel.go
  test/e2e/test_broker_pubsub.go
  vendor/github.com/google/go-containerregistry/pkg/name/README.md
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_combined_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1alpha1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1alpha1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/test_helpers.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/channel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_types.go
  vendor/knative.dev/eventing/pkg/kncloudevents/utils.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/channel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/inmemorychannel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_dls_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_with_config_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/parallel_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/sequence_test_helper.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_defaults.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/service_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1014 Register stats in NewStatsReporter instead of init
  cmd/broker/ingress/wire_gen.go
  pkg/broker/ingress/handler_test.go
  pkg/broker/ingress/stats_reporter.go
  pkg/broker/ingress/stats_reporter_test.go
Labels: approved, cla: yes, lgtm, size/M

#995 Make deployment controller listen to 'Create' and 'Delete' events of Secret
  pkg/reconciler/deployment/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1011 Update cluster version for e2e-wi-tests.
  go.mod
  go.sum
  test/e2e-wi-tests.sh
  test/e2e/e2e_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1017 Add the x bit for e2e-secret-tests.sh
  test/e2e-secret-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1015 Use wire to initialize fanout and retry SyncPools
  cmd/broker/fanout/main.go
  cmd/broker/fanout/wire.go
  cmd/broker/fanout/wire_gen.go
  cmd/broker/retry/main.go
  cmd/broker/retry/wire.go
  cmd/broker/retry/wire_gen.go
  pkg/broker/handler/pool/fanout.go
  pkg/broker/handler/pool/fanout_test.go
  pkg/broker/handler/pool/options.go
  pkg/broker/handler/pool/options_test.go
  pkg/broker/handler/pool/providers.go
  pkg/broker/handler/pool/retry.go
  pkg/broker/handler/pool/retry_test.go
  pkg/broker/handler/pool/wire.go
  pkg/broker/handler/pool/wire_gen.go
Labels: approved, cla: yes, lgtm, size/XL

#1009 Unpin k8s.io/gengo
  go.mod
  go.sum
  vendor/k8s.io/gengo/args/args.go
  vendor/k8s.io/gengo/examples/import-boss/generators/import_restrict.go
  vendor/k8s.io/gengo/generator/default_package.go
  vendor/k8s.io/gengo/generator/execute.go
  vendor/k8s.io/gengo/generator/generator.go
  vendor/k8s.io/gengo/generator/transitive_closure.go
  vendor/k8s.io/gengo/namer/order.go
  vendor/k8s.io/gengo/namer/plural_namer.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/k8s.io/gengo/types/types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#996 Add event TTL (hops) to broker
  pkg/broker/eventutil/hops.go
  pkg/broker/eventutil/hops_test.go
  pkg/broker/handler/pool/fanout_test.go
  pkg/broker/handler/pool/retry.go
  pkg/broker/handler/pool/retry_test.go
  pkg/broker/handler/pool/testing/helper.go
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
Labels: approved, cla: yes, lgtm, size/XL

#991 Bump go version to 1.14
  go.mod
  go.sum
  hack/update-deps.sh
  pkg/client/injection/reconciler/broker/v1beta1/broker/reconciler.go
  pkg/client/injection/reconciler/broker/v1beta1/trigger/reconciler.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudauditlogssource/reconciler.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudbuildsource/reconciler.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudpubsubsource/reconciler.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudschedulersource/reconciler.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudstoragesource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudauditlogssource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudpubsubsource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudschedulersource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudstoragesource/reconciler.go
  pkg/client/injection/reconciler/intevents/v1alpha1/brokercell/reconciler.go
  pkg/client/injection/reconciler/intevents/v1alpha1/pullsubscription/reconciler.go
  pkg/client/injection/reconciler/intevents/v1alpha1/topic/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  pkg/client/injection/reconciler/policy/v1alpha1/eventpolicybinding/reconciler.go
  pkg/client/injection/reconciler/policy/v1alpha1/httppolicybinding/reconciler.go
  pkg/client/injection/reconciler/pubsub/v1alpha1/pullsubscription/reconciler.go
  pkg/client/injection/reconciler/pubsub/v1alpha1/topic/reconciler.go
  pkg/client/injection/reconciler/pubsub/v1beta1/pullsubscription/reconciler.go
  pkg/client/injection/reconciler/pubsub/v1beta1/topic/reconciler.go
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1004 updated docs of install knative-gcp and examples of cloudstoragesource
  docs/examples/cloudstoragesource/README.md
  docs/install/install-knative-gcp.md
Labels: approved, cla: yes, lgtm, size/L

#1025 Fix perf tests setup
  test/performance/benchmarks/broker-pubsub/continuous/100-broker-pubsub-setup.yaml
  test/performance/benchmarks/channel-pubsub/continuous/100-channel-perf-setup.yaml
Labels: approved, cla: yes, lgtm, size/M

#1026 Broker returns 202 instead of 200 when events are accepted
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
Labels: approved, cla: yes, lgtm, size/M

#1032 Revert "Replace T.Cleanup with returned cleanup func in createPubsubClient"
  pkg/broker/ingress/handler_test.go
Labels: approved, cla: yes, lgtm, size/M

#1024 Receive messages directly from subscription in the broker handler
  pkg/broker/handler/handler.go
  pkg/broker/handler/handler_test.go
  pkg/broker/handler/pool/fanout.go
  pkg/broker/handler/pool/retry.go
Labels: approved, cla: yes, lgtm, size/L

#891 Use standard pubsub client in Broker controller
  go.mod
  go.sum
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/trigger.go
  pkg/reconciler/broker/trigger_test.go
  pkg/reconciler/testing/pstest.go
  vendor/cloud.google.com/go/pubsub/apiv1/doc.go
  vendor/cloud.google.com/go/pubsub/apiv1/info.go
  vendor/cloud.google.com/go/pubsub/apiv1/publisher_client.go
  vendor/cloud.google.com/go/pubsub/apiv1/subscriber_client.go
  vendor/cloud.google.com/go/pubsub/go.mod
  vendor/cloud.google.com/go/pubsub/go.sum
  vendor/cloud.google.com/go/pubsub/message.go
  vendor/cloud.google.com/go/pubsub/pstest/fake.go
  vendor/cloud.google.com/go/pubsub/subscription.go
  vendor/google.golang.org/appengine/.travis.yml
  vendor/google.golang.org/appengine/internal/api.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1034 Add bskaplan as a reviewer for knative-gcp
  OWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1022 Configure gcp broker test infra to support checking metrics
  test/e2e/e2e_test.go
  test/e2e/test_gcp_broker.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#959 Channel v1beta1 Fixes
  config/core/resources/channel.yaml
  hack/verify-codegen.sh
  pkg/apis/messaging/internal/constants.go
  pkg/apis/messaging/v1alpha1/channel_conversion.go
  pkg/apis/messaging/v1alpha1/channel_conversion_test.go
  pkg/apis/messaging/v1alpha1/channel_defaults.go
  pkg/apis/messaging/v1alpha1/channel_defaults_test.go
  pkg/apis/messaging/v1beta1/channel_defaults.go
  pkg/apis/messaging/v1beta1/channel_defaults_test.go
  pkg/apis/messaging/v1beta1/channel_types.go
  pkg/apis/messaging/v1beta1/channel_validation.go
  pkg/apis/messaging/v1beta1/channel_validation_test.go
  pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  test/e2e-tests.sh
  test/e2e/lib/resources/constants.go
  test/e2e/main_test.go
Labels: approved, cla: yes, lgtm, size/L

#980 Add Deprecation Warnings to Topic and PullSubscription
  pkg/apis/pubsub/internal/deprecated_condition.go
  pkg/apis/pubsub/internal/deprecated_condition_test.go
  pkg/apis/pubsub/v1alpha1/deprecated_condition.go
  pkg/apis/pubsub/v1beta1/deprecated_condition.go
  pkg/reconciler/pubsub/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/pubsub/pullsubscription/reconciler.go
  pkg/reconciler/pubsub/pullsubscription/static/pullsubscription_test.go
  pkg/reconciler/pubsub/topic/topic.go
  pkg/reconciler/pubsub/topic/topic_test.go
  pkg/reconciler/testing/pubsub_pullsubscription.go
  pkg/reconciler/testing/pubsub_topic.go
Labels: approved, cla: yes, lgtm, size/L

#1012 Add mainhelper for common main logic
  cmd/broker/fanout/main.go
  cmd/broker/ingress/main.go
  cmd/broker/retry/main.go
  go.mod
  go.sum
  pkg/observability/observability.go
  pkg/utils/mainhelper/init.go
  pkg/utils/mainhelper/init_test.go
  pkg/utils/mainhelper/options.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1028 added e2e test of gcp broker with four sources and fixed typo of docs
  docs/examples/cloudschedulersource/README.md
  test/e2e/e2e_test.go
  test/e2e/lib/auditlogs.go
  test/e2e/lib/helpers/broker_event_transformation_test_with_source.go
  test/e2e/test_auditlogs.go
  test/e2e/test_broker_pubsub.go
  test/e2e/test_gcp_broker.go
Labels: approved, cla: yes, lgtm, size/XL

#994 Reconcile gcp broker data plane deployments
  cmd/controller/main.go
  config/300-brokercell.yaml
  config/core/deployments/controller.yaml
  config/core/roles/clusterrole.yaml
  go.mod
  pkg/apis/intevents/v1alpha1/brokercell_lifecycle.go
  pkg/apis/intevents/v1alpha1/test_helper.go
  pkg/reconciler/broker/resources/deployments_test.go
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/brokercell/controller.go
  pkg/reconciler/brokercell/controller_test.go
  pkg/reconciler/brokercell/resources/args.go
  pkg/reconciler/brokercell/resources/deployments.go
  pkg/reconciler/brokercell/resources/services.go
  pkg/reconciler/brokercell/testingdata/fanout_deployment.yaml
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/ingress_service.yaml
  pkg/reconciler/brokercell/testingdata/ingress_service_with_status.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/util.go
  pkg/reconciler/helper.go
  pkg/reconciler/helper_test.go
  pkg/reconciler/testing/brokercell.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1036 Add grac3gao to reviewer and approver
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1041 Create trigger span in filter processor
  pkg/broker/handler/processors/filter/processor.go
  pkg/broker/handler/processors/filter/processor_test.go
Labels: approved, cla: yes, lgtm, size/M

#1027 Run shellcheck on all shell scripts
  docs/examples/cloudstoragesource/README.md
  docs/install/install-knative-gcp.md
  hack/init_cloud_storage_source.sh
  hack/init_control_plane.sh
  hack/init_control_plane_gke.sh
  hack/init_data_plane.sh
  hack/lib.sh
  hack/release.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/e2e-common.sh
  test/e2e-secret-tests.sh
  test/e2e-tests.sh
  test/e2e-wi-tests.sh
  test/presubmit-tests.sh
  test/upload-test-images.sh
Labels: approved, cla: yes, lgtm, size/L

#1047 Apply t.Log and t.Helper for e2e tests
  test/e2e/lib/auditlogs.go
  test/e2e/lib/broker.go
  test/e2e/lib/creation.go
  test/e2e/lib/helpers/broker_event_transformation_test_with_source.go
  test/e2e/lib/lifecycle.go
  test/e2e/lib/pubsub.go
  test/e2e/lib/scheduler.go
  test/e2e/lib/secrets.go
  test/e2e/lib/storage.go
  test/e2e/lib/topics.go
  test/e2e/test_broker_pubsub.go
  test/e2e/test_channel.go
  test/e2e/test_gcp_broker.go
  test/e2e/test_pubsub.go
  test/e2e/test_pullsubscription.go
  test/e2e/test_scheduler.go
  test/e2e/test_storage.go
Labels: approved, cla: yes, lgtm, size/L

#1048 Remove pin of cloud.google.com/go/pubsub
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1057 Unip go.uber.org/zap
  go.mod
  go.sum
  vendor/go.uber.org/zap/.gitignore
  vendor/go.uber.org/zap/.readme.tmpl
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/checklicense.sh
  vendor/go.uber.org/zap/config.go
  vendor/go.uber.org/zap/encoder.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/glide.lock
  vendor/go.uber.org/zap/glide.yaml
  vendor/go.uber.org/zap/global.go
  vendor/go.uber.org/zap/global_go112.go
  vendor/go.uber.org/zap/global_prego112.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/increase_level.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/memory_encoder.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1062 Upgrade Knative Dependency Versions
  go.mod
  go.sum
  pkg/broker/ingress/handler.go
  pkg/metrics/delivery_reporter_test.go
  pkg/metrics/ingress_reporter_test.go
  pkg/pubsub/adapter/stats_reporter_test.go
  pkg/reconciler/stats_reporter_test.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1alpha1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/inmemorychannel.go
  vendor/knative.dev/eventing/pkg/tracing/attributes.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/eventing/test/lib/checkevents.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/logexporter.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/eventing/test/lib/validation.go
  vendor/knative.dev/eventing/test/test_images/recordevents/eventstore.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/utils.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/prow/env.go
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1067 Update lib.sh for e2e test running locally in new cluster
  hack/lib.sh
Labels: approved, cla: yes, lgtm, size/XS

#1068 Add dummy packages for go mod
  config/broker/deployments/dummy.go
  config/broker/dummy.go
  config/broker/rbac/dummy.go
  config/broker/services/dummy.go
  config/core/dummy.go
  config/core/resources/dummy.go
  config/core/roles/dummy.go
  config/core/services/dummy.go
  config/core/webhooks/dummy.go
  config/dummy.go
  config/istio/dummy.go
  config/monitoring/metrics/grafana/dummy.go
  config/monitoring/metrics/prometheus/dummy.go
  config/policy/dummy.go
Labels: approved, cla: yes, lgtm, size/L

#1061 Delete remaining policy yamls
  config/policy/100-namespace.yaml
  config/policy/200-serviceaccount.yaml
  config/policy/201-clusterrole.yaml
  config/policy/201-role.yaml
  config/policy/201-webhook-clusterrole.yaml
  config/policy/202-clusterrolebinding.yaml
  config/policy/202-rolebinding.yaml
  config/policy/300-eventpolicy.yaml
  config/policy/300-eventpolicybinding.yaml
  config/policy/300-httppolicy.yaml
  config/policy/300-httppolicybinding.yaml
  config/policy/400-webhook-service.yaml
  config/policy/500-controller.yaml
  config/policy/500-webhook-config-validation.yaml
  config/policy/500-webhook-defaulting.yaml
  config/policy/500-webhook-resource-validation.yaml
  config/policy/500-webhook-secret.yaml
  config/policy/500-webhook.yaml
  config/policy/config-leader-election.yaml
  config/policy/config-logging.yaml
  config/policy/config-observability.yaml
  config/policy/config-tracing.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1049 Add debug guide for gcp broker
  README.md
  docs/install/images/GCPBroker.png
  docs/install/install-gcp-broker.md
Labels: approved, cla: yes, lgtm, size/M

#1065 Switch symlinks to real files
  hack/update-codegen.sh
  pkg/apis/pubsub/v1alpha1/implements_test.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_conversion.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_conversion_test.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_defaults.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_defaults_test.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_lifecycle.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_lifecycle_test.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_types.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_validation.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_validation_test.go
  pkg/apis/pubsub/v1alpha1/topic_conversion.go
  pkg/apis/pubsub/v1alpha1/topic_conversion_test.go
  pkg/apis/pubsub/v1alpha1/topic_defaults.go
  pkg/apis/pubsub/v1alpha1/topic_defaults_test.go
  pkg/apis/pubsub/v1alpha1/topic_lifecycle.go
  pkg/apis/pubsub/v1alpha1/topic_lifecycle_test.go
  pkg/apis/pubsub/v1alpha1/topic_types.go
  pkg/apis/pubsub/v1alpha1/topic_validation.go
  pkg/apis/pubsub/v1alpha1/topic_validation_test.go
  pkg/apis/pubsub/v1beta1/implements_test.go
  pkg/apis/pubsub/v1beta1/pullsubscription_conversion.go
  pkg/apis/pubsub/v1beta1/pullsubscription_conversion_test.go
  pkg/apis/pubsub/v1beta1/pullsubscription_defaults.go
  pkg/apis/pubsub/v1beta1/pullsubscription_defaults_test.go
  pkg/apis/pubsub/v1beta1/pullsubscription_lifecycle.go
  pkg/apis/pubsub/v1beta1/pullsubscription_lifecycle_test.go
  pkg/apis/pubsub/v1beta1/pullsubscription_types.go
  pkg/apis/pubsub/v1beta1/pullsubscription_validation.go
  pkg/apis/pubsub/v1beta1/pullsubscription_validation_test.go
  pkg/apis/pubsub/v1beta1/topic_conversion.go
  pkg/apis/pubsub/v1beta1/topic_conversion_test.go
  pkg/apis/pubsub/v1beta1/topic_defaults.go
  pkg/apis/pubsub/v1beta1/topic_defaults_test.go
  pkg/apis/pubsub/v1beta1/topic_lifecycle.go
  pkg/apis/pubsub/v1beta1/topic_lifecycle_test.go
  pkg/apis/pubsub/v1beta1/topic_types.go
  pkg/apis/pubsub/v1beta1/topic_validation.go
  pkg/apis/pubsub/v1beta1/topic_validation_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1073 added dumps of controller pods in cloud-run-events
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/S

#1075 [master] Format markdown
  docs/install/install-gcp-broker.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1076 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1alpha1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/duck/sinks.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_spec_test_helper.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/addressable/addressable.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1081 Fix nil pointer error in updateTargetsConfig
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_targets_test.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/testing/configmap.go
Labels: approved, cla: yes, lgtm, size/L

#1069 Print metrics from all Pods in the namespace if the test fails.
  test/e2e/lib/helpers/broker_event_transformation_test_with_source.go
  test/e2e/lib/lifecycle.go
  test/e2e/lib/metrics.go
Labels: approved, cla: yes, lgtm, size/L

#1082 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_types.go
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1092 [master] Fix spelling errors
  test/e2e/lib/metrics.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1093 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e/helpers/trigger_no_broker_test_helper.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1087 Respect the delivery timeout option in fanout.
  pkg/broker/handler/pool/fanout.go
Labels: approved, cla: yes, lgtm, size/S

#1064 Broker tracing conventions
  cmd/broker/fanout/wire_gen.go
  cmd/broker/retry/wire_gen.go
  pkg/broker/handler/pool/providers.go
  pkg/broker/handler/processors/filter/processor.go
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
  pkg/tracing/attributes.go
Labels: approved, cla: yes, lgtm, size/L

#1079 Add Delivery Processor Benchmarks
  pkg/broker/handler/processors/deliver/processor_test.go
Labels: approved, cla: yes, lgtm, size/L

#1096 Remove unnecessary draining of HTTP request body from benchmark
  pkg/broker/handler/processors/deliver/processor_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1089 Make a markdown table.
  docs/examples/cloudauditlogssource/README.md
Labels: approved, cla: yes, lgtm, size/S

#1098 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-tests.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/lib/await.go
  vendor/knative.dev/eventing/test/lib/duck/resource_checks.go
  vendor/knative.dev/eventing/test/lib/duck/serving_checks.go
  vendor/knative.dev/eventing/test/lib/resources/constants.go
  vendor/knative.dev/eventing/test/lib/resources/serving.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1091 Properly updating PS and Topic upon changes in spec
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/build/build_test.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/intevents/reconciler.go
  pkg/reconciler/intevents/reconciler_test.go
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/testing/storage.go
Labels: approved, cla: yes, lgtm, size/XXL

#1101 Add yet another dummy.go to make go mod happy
  config/core/configmaps/dummy.go
Labels: approved, cla: yes, lgtm, size/S

#1106 Run ingress deliver processor benchmarks with multiple goroutines
  pkg/broker/handler/processors/deliver/processor_test.go
Labels: approved, cla: yes, lgtm, size/S

#1080 Unpin Cloudevents SDK and Upgrade to v2.0.0-rc4
  go.mod
  go.sum
  pkg/broker/handler/pool/testing/helper.go
  pkg/broker/ingress/handler_test.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/encoding.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/finish_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/format/format.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/transformer/default_metadata.go
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/client/invoker.go
  vendor/github.com/cloudevents/sdk-go/v2/client/options.go
  vendor/github.com/cloudevents/sdk-go/v2/client/receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/client/test/test.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_marshal.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_validation.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/v2/extensions/distributed_tracing_extension.go
  vendor/github.com/cloudevents/sdk-go/v2/go.mod
  vendor/github.com/cloudevents/sdk-go/v2/go.sum
  vendor/github.com/cloudevents/sdk-go/v2/protocol/gochan/receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/gochan/requester.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/gochan/responder.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/gochan/sender.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/options.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_lifecycle.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/inbound.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/lifecycle.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/outbound.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/pubsub/internal/connection.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/pubsub/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/result.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1110 Remove specified cluster version in WI e2e test
  test/e2e-wi-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1090 Give the receiver time to shutdown before stopping the knockdown process.
  test/e2e/lib/auditlogs.go
  test/e2e/lib/scheduler.go
  test/e2e/lib/storage.go
  test/test_images/auditlogs_target/main.go
  test/test_images/internal/knockdown/knockdown.go
  test/test_images/scheduler_target/main.go
  test/test_images/storage_target/main.go
Labels: approved, cla: yes, lgtm, size/L

#1074 Fixes to performance tests
  test/performance/benchmarks/broker-pubsub/continuous/200-broker-pubsub.yaml
  test/performance/benchmarks/channel-pubsub/continuous/200-channel-perf.yaml
  test/performance/performance-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1103 Pubsub converts between Pubsubs, not intevents.
  hack/update-codegen.sh
  pkg/apis/pubsub/v1alpha1/pullsubscription_conversion.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_conversion_test.go
  pkg/apis/pubsub/v1alpha1/topic_conversion.go
  pkg/apis/pubsub/v1alpha1/topic_conversion_test.go
Labels: approved, cla: yes, lgtm, size/S

#1111 Wait for Fanout Test Helpers in Sync Pool Tests
  pkg/broker/handler/pool/fanout_test.go
  pkg/broker/handler/pool/retry_test.go
  pkg/broker/handler/pool/testing/helper.go
Labels: approved, cla: yes, lgtm, size/L

#1109 Add ingress handler benchmark
  pkg/broker/ingress/handler_test.go
Labels: approved, cla: yes, lgtm, size/M

#1115 [master] Format markdown
  docs/examples/cloudauditlogssource/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1114 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/config/channel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/channel_conversion.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_header_single_event_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/traces.go
  vendor/knative.dev/eventing/test/conformance/helpers/uri.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/trigger_no_broker_test_helper.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/performance/infra/receiver/receiver.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1095 Remove TestBrokerTracing.
  test/e2e/e2e_test.go
Labels: approved, cla: yes, lgtm, size/S

#1066 Reconcilers delete old Topics and PullSubscriptions
  pkg/duck/v1alpha1/identifiable.go
  pkg/reconciler/intevents/reconciler.go
  pkg/reconciler/intevents/reconciler_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1112 Set HTTP MaxIdleConnsPerHost to runtime.NumCPU() in benchmarks
  pkg/broker/handler/processors/deliver/processor_test.go
Labels: approved, cla: yes, lgtm, size/S

#1117 Pin knative/pkg and knative/test-infra to release-0.15
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1122 Alias import of k8s.io/api/apps/v1
  pkg/reconciler/helper.go
Labels: approved, cla: yes, lgtm, size/XS

#1125 Pin serving to 0.15
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_defaults.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/broker.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1126 Pin eventing to 0.15
  go.sum
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/S

#1123 Add resync period to brokercell controller
  pkg/reconciler/brokercell/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#1099 Support delivering to a sink in another namespace
  config/core/resources/old_pullsubscription.yaml
  config/core/resources/pullsubscription.yaml
  pkg/reconciler/intevents/pullsubscription/reconciler.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription_test.go
  pkg/reconciler/pubsub/pullsubscription/reconciler.go
Labels: approved, cla: yes, lgtm, size/L

#1131 Add Delivery Processor MicroBenchmarks Using Fake HTTP Clients
  pkg/broker/handler/processors/deliver/processor_test.go
Labels: approved, cla: yes, lgtm, size/L

#1121 Update broker resource limits and add HPA
  cmd/broker/retry/main.go
  config/broker/500-hpa.yaml
  config/broker/deployments/broker.yaml
  config/broker/deployments/hpa.yaml
Labels: approved, cla: yes, lgtm, size/L

#1070 Add some missing pieces in docs and some improvement
  docs/install/install-gcp-broker.md
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, size/M

#1139 Track master branches after release
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/register.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/eventtype.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/config/store.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_lifecycle.go
  vendor/knative.dev/test-infra/scripts/update-test-infra.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1138 [master] Format markdown
  docs/install/install-gcp-broker.md
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1142 Handle broker mutation delete properly
  pkg/broker/config/memory/memory.go
  pkg/broker/config/memory/memory_test.go
Labels: approved, cla: yes, lgtm, size/M

#1151 Expose BrokerCell's status.ingressTemplate
  config/core/resources/brokercell.yaml
  pkg/apis/intevents/v1alpha1/brokercell_types.go
Labels: approved, cla: yes, lgtm, size/XS

#1163 Update to v1beta1 triggers in examples
  docs/examples/gcpbroker/triggers.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1135 Use HTTP Client + CE SDK v2 Bindings in Deliver Processor
  cmd/broker/fanout/wire_gen.go
  cmd/broker/retry/wire_gen.go
  pkg/broker/eventutil/hops.go
  pkg/broker/handler/pool/fanout.go
  pkg/broker/handler/pool/providers.go
  pkg/broker/handler/pool/retry.go
  pkg/broker/handler/pool/testing/helper.go
  pkg/broker/handler/pool/wire.go
  pkg/broker/handler/pool/wire_gen.go
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
Labels: approved, cla: yes, lgtm, size/L

#1175 Pin to previous eventing nightly
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/XS

#1159 Only start the pull handler when its resource is ready
  pkg/broker/handler/pool/fanout.go
  pkg/broker/handler/pool/fanout_test.go
  pkg/broker/handler/pool/retry.go
  pkg/broker/handler/pool/retry_test.go
Labels: approved, cla: yes, lgtm, size/M
