Repository google/knative-gcp, pull requests merged in 2020-09, with the labels that each got.

#1653 Add Channel and CloudBuildSource to the migration tool of storage version v1beta1
  config/pre-install/v0.18.0/channel.yaml
  config/pre-install/v0.18.0/cloudbuildsource.yaml
  config/pre-install/v0.18.0/clusterrole.yaml
  config/pre-install/v0.18.0/storage-version-migration.yaml
Labels: approved, cla: yes, lgtm, size/L

#1655 Add Tracing Cloud Logging fields
  pkg/broker/handler/processors/filter/processor.go
  pkg/broker/ingress/handler.go
  pkg/tracing/logging.go
Labels: approved, cla: yes, lgtm, size/M

#1657 Promote CloudBuildSource to v1 API
  pkg/apis/events/v1/cloudbuildsource_defaults.go
  pkg/apis/events/v1/cloudbuildsource_defaults_test.go
  pkg/apis/events/v1/cloudbuildsource_lifecycle.go
  pkg/apis/events/v1/cloudbuildsource_lifecycle_test.go
  pkg/apis/events/v1/cloudbuildsource_types.go
  pkg/apis/events/v1/cloudbuildsource_types_test.go
  pkg/apis/events/v1/cloudbuildsource_validation.go
  pkg/apis/events/v1/cloudbuildsource_validation_test.go
  pkg/apis/events/v1/implements_test.go
  pkg/apis/events/v1/register.go
  pkg/apis/events/v1/register_test.go
  pkg/apis/events/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/events/v1/cloudbuildsource.go
  pkg/client/clientset/versioned/typed/events/v1/events_client.go
  pkg/client/clientset/versioned/typed/events/v1/fake/fake_cloudbuildsource.go
  pkg/client/clientset/versioned/typed/events/v1/fake/fake_events_client.go
  pkg/client/clientset/versioned/typed/events/v1/generated_expansion.go
  pkg/client/informers/externalversions/events/v1/cloudbuildsource.go
  pkg/client/informers/externalversions/events/v1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/injection/informers/events/v1/cloudbuildsource/cloudbuildsource.go
  pkg/client/injection/informers/events/v1/cloudbuildsource/fake/fake.go
  pkg/client/injection/reconciler/events/v1/cloudbuildsource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudbuildsource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudbuildsource/state.go
  pkg/client/listers/events/v1/cloudbuildsource.go
  pkg/client/listers/events/v1/expansion_generated.go
Labels: approved, cla: yes, lgtm, size/XXL

#1659 Add webhook conversion and defaults for CloudBuildSource v1
  cmd/webhook/main.go
  config/core/resources/cloudbuildsource.yaml
  config/pre-install/v0.18.0/cloudbuildsource.yaml
  pkg/apis/events/v1/cloudbuildsource_conversion.go
  pkg/apis/events/v1/cloudbuildsource_conversion_test.go
  pkg/apis/events/v1/cloudbuildsource_types.go
  pkg/apis/events/v1alpha1/cloudbuildsource_conversion.go
  pkg/apis/events/v1alpha1/cloudbuildsource_conversion_test.go
  pkg/apis/events/v1beta1/cloudbuildsource_conversion.go
  pkg/apis/events/v1beta1/cloudbuildsource_conversion_test.go
  pkg/testing/test_helper.go
Labels: approved, cla: yes, lgtm, size/L

#1652 Added liveness probe to Probe Helper pod
  test/test_images/probe_helper/probe_helper.go
  test/test_images/probe_helper/probe_helper.yaml
Labels: approved, cla: yes, lgtm, size/M

#1656 Adjust broker ingress parameters to support target load
  cmd/broker/ingress/main.go
  cmd/broker/ingress/wire.go
  cmd/broker/ingress/wire_gen.go
  pkg/apis/intevents/v1alpha1/brokercell_defaults.go
  pkg/apis/intevents/v1alpha1/brokercell_validation_test.go
  pkg/broker/ingress/handler_test.go
  pkg/broker/ingress/multi_topic_decouple_sink.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
  pkg/reconciler/brokercell/resources/deployments.go
  pkg/reconciler/brokercell/testingdata/ingress_deployment.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/ingress_hpa.yaml
Labels: approved, cla: yes, lgtm, size/M

#1662 Change CloudBuildSource reconciler and e2e tests to v1, add Smoke test for v1beta1 CloudBuildSource
  pkg/reconciler/events/build/build.go
  pkg/reconciler/events/build/build_test.go
  pkg/reconciler/events/build/controller.go
  pkg/reconciler/events/build/controller_test.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/v1/build.go
  pkg/reconciler/testing/v1beta1/build.go
  test/e2e/e2e_test.go
  test/e2e/lib/build.go
  test/e2e/lib/creation.go
  test/e2e/lib/deletion.go
  test/e2e/lib/get.go
  test/e2e/lib/typemetas.go
  test/e2e/test_build.go
Labels: approved, cla: yes, lgtm, size/XL

#1663 Update docs for CloudBuildSource to use v1
  docs/examples/cloudbuildsource/cloudbuildsource.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1661 Reduce Metric test flakiness caused by sender pod retry sending events
  test/e2e/lib/broker.go
Labels: approved, cla: yes, lgtm, size/XS

#1639 Extended the Probe Helper for use with CloudStorageSource probe
  test/test_images/probe_helper/main.go
  test/test_images/probe_helper/probe_helper.go
  test/test_images/probe_helper/probe_helper.yaml
  test/test_images/probe_helper/probe_helper_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1660 Use custom equality tester for TargetsConfig in ConfigMap reconciler
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/resources/configmap.go
  pkg/reconciler/brokercell/resources/configmap_test.go
  pkg/reconciler/utils/configmap.go
  pkg/reconciler/utils/configmap_test.go
Labels: approved, cla: yes, lgtm, size/L

#1666 Better ingress error message on permission denied
  pkg/broker/ingress/handler.go
Labels: approved, cla: yes, lgtm, size/S

#1668 Fix incorrect PUBLISHED_BUFFERED_BYTES_LIMIT warning
  cmd/broker/ingress/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1667 Adding schema to PubSub Source
  docs/examples/cloudpubsubsource/README.md
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/pubsub_test.go
  test/e2e/lib/constants.go
  test/e2e/lib/helpers/broker_event_transformation_test_with_source.go
  test/e2e/lib/pubsub.go
  test/e2e/test_pubsub.go
  test/e2e/test_pullsubscription.go
  test/test_images/pubsub_target/main.go
Labels: approved, cla: yes, lgtm, size/S

#1665 Use different TraceID for each retry in sender pod to reduce tracing test flakiness
  test/e2e/lib/helpers/broker_tracing.go
  test/test_images/sender/main.go
Labels: approved, cla: yes, lgtm, size/M

#1651 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/knative.dev/networking/pkg/LICENSE
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_combined_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/channel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/service.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_spec_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/bufferpool.go
  vendor/knative.dev/networking/pkg/doc.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/pkg/probe_handler.go
  vendor/knative.dev/networking/pkg/stats.go
  vendor/knative.dev/networking/pkg/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/service_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#1670 Add nlopezgi to approvers and reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1673 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1675 Fix wrong status message by changing `%w` to `%v`.
  pkg/pubsub/adapter/adapter.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/utils/pubsub/subscription.go
  pkg/reconciler/utils/pubsub/topic.go
Labels: approved, cla: yes, lgtm, size/M

#1677 update test-infra and fix the breaking change
  go.mod
  go.sum
  test/e2e-wi-tests.sh
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1669 Refactor the Probe Helper
  test/test_images/probe_helper/main.go
  test/test_images/probe_helper/probe_helper.go
  test/test_images/probe_helper/probe_helper.yaml
  test/test_images/probe_helper/probe_helper_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1676 Update v1alpha1 deprecated message to be removed in 0.19
  pkg/apis/convert/conversion_helper.go
Labels: approved, cla: yes, lgtm, size/XS

#1686 Remove unused code
  pkg/reconciler/identity/reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#1689 Extend tracing test waiting time
  test/e2e/lib/helpers/broker_tracing.go
Labels: approved, cla: yes, lgtm, size/XS

#1694 Fix obsolete comment in handler.go, add new comment to receive function
  pkg/broker/handler/handler.go
Labels: approved, cla: yes, lgtm, size/XS

#1691 Small documentation improvements
  docs/install/dataplane-service-account.md
  docs/install/install-knative-gcp.md
Labels: approved, cla: yes, lgtm, size/S

#1674 Extend the Probe Helper to work with CloudSchedulerSource probe
  test/test_images/probe_helper/main.go
  test/test_images/probe_helper/probe_helper.go
  test/test_images/probe_helper/probe_helper.yaml
  test/test_images/probe_helper/probe_helper_test.go
Labels: approved, cla: yes, lgtm, size/L

#1685 Extend the ProbeHelper for use with CloudAuditLogsSource probe
  test/test_images/probe_helper/main.go
  test/test_images/probe_helper/probe_helper.go
  test/test_images/probe_helper/probe_helper_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1705 Properly set system namespace when reconciling default brokercell
  pkg/reconciler/brokercell/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1708 [master] Format markdown
  docs/install/dataplane-service-account.md
  docs/install/install-knative-gcp.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1707 Refine ProbeHelper for CloudAuditLogsSource probe
  test/test_images/probe_helper/main.go
  test/test_images/probe_helper/probe_helper.go
  test/test_images/probe_helper/probe_helper_test.go
Labels: approved, cla: yes, lgtm, size/L

#1710 Fix release script which has been breaking auto release
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1714 set empty secret to nil
  pkg/apis/duck/v1/pubsub_defaults.go
  pkg/apis/duck/v1/pubsub_defaults_test.go
  pkg/apis/duck/v1alpha1/pubsub_defaults.go
  pkg/apis/duck/v1alpha1/pubsub_defaults_test.go
  pkg/apis/duck/v1beta1/pubsub_defaults.go
  pkg/apis/duck/v1beta1/pubsub_defaults_test.go
  pkg/apis/duck/validations.go
Labels: approved, cla: yes, lgtm, size/M

#1702 Change Ingress Decouple Sink to Use Logger from Ctx
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/multi_topic_decouple_sink.go
Labels: approved, cla: yes, lgtm, size/S

#1712 Remove additional fatalf in broker/singleton_test.go
  pkg/apis/configs/broker/singleton_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1717 Properly set system namespace when reconciling default brokercell (#1…
  pkg/reconciler/brokercell/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1690 Update broker deployments spec for better availability during upgrades
  pkg/reconciler/brokercell/resources/deployments.go
  pkg/reconciler/brokercell/testingdata/fanout_deployment.yaml
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_status.yaml
  pkg/reconciler/utils/deployment.go
  pkg/reconciler/utils/deployment_test.go
Labels: approved, cla: yes, lgtm, size/M

#1718 PullSubscription Status reflect non-creatable Deployment
  pkg/apis/intevents/v1/pullsubscription_lifecycle.go
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription.go
  pkg/reconciler/intevents/pullsubscription/reconciler.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription.go
Labels: approved, cla: yes, lgtm, size/S

#1716 Properly set system namespace when reconciling default brokercell
  pkg/reconciler/brokercell/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1720 added UT or pullsubscriptions related to failure of creating/updating…
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription.go
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/intevents/pullsubscription/reconciler.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription_test.go
  pkg/reconciler/testing/v1/pullsubscription.go
Labels: approved, cla: yes, lgtm, size/XL

#1721 fixed pullsusbcription mark deployed status
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription.go
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/intevents/pullsubscription/reconciler.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription_test.go
Labels: approved, cla: yes, lgtm, size/S

#1715 Properly set system namespace when reconciling default brokercell
  pkg/reconciler/brokercell/controller.go
Labels: approved, cla: yes, lgtm, size/S

#1723 Use custom equality tester for TargetsConfig in ConfigMap reconciler
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/resources/configmap.go
  pkg/reconciler/brokercell/resources/configmap_test.go
  pkg/reconciler/utils/configmap.go
  pkg/reconciler/utils/configmap_test.go
Labels: approved, cla: yes, lgtm, size/L

#1725 Check the decouple queue state instead of the overall broker state in ingress
  pkg/broker/config/targets.pb.go
  pkg/broker/config/targets.proto
  pkg/broker/ingress/handler_test.go
  pkg/broker/ingress/multi_topic_decouple_sink.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/testingdata/configmap.go
Labels: approved, cla: yes, lgtm, size/L

#1728 Use custom equality tester for TargetsConfig in ConfigMap reconciler (0.16)
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/resources/configmap.go
  pkg/reconciler/brokercell/resources/configmap_test.go
  pkg/reconciler/helper.go
  pkg/reconciler/helper_test.go
Labels: approved, cla: yes, lgtm, size/L

#1735 Set empty secret to nil (0.17)
  pkg/apis/duck/v1/pubsub_defaults.go
  pkg/apis/duck/v1/pubsub_defaults_test.go
  pkg/apis/duck/v1alpha1/pubsub_defaults.go
  pkg/apis/duck/v1alpha1/pubsub_defaults_test.go
  pkg/apis/duck/v1beta1/pubsub_defaults.go
  pkg/apis/duck/v1beta1/pubsub_defaults_test.go
  pkg/apis/duck/validations.go
Labels: approved, cla: yes, lgtm, size/M

#1730 Use custom equality tester for TargetsConfig in ConfigMap reconciler (0.15b)
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/resources/configmap.go
  pkg/reconciler/brokercell/resources/configmap_test.go
  pkg/reconciler/helper.go
  pkg/reconciler/helper_test.go
Labels: approved, cla: yes, lgtm, size/L

#1734 Set empty secret to nil (0.16)
  pkg/apis/duck/v1alpha1/credentials.go
  pkg/apis/duck/v1alpha1/pubsub_defaults.go
  pkg/apis/duck/v1alpha1/pubsub_defaults_test.go
  pkg/apis/duck/v1beta1/credentials.go
  pkg/apis/duck/v1beta1/pubsub_defaults.go
  pkg/apis/duck/v1beta1/pubsub_defaults_test.go
Labels: approved, cla: yes, lgtm, size/M

#1736 Allow istio sidecar injection for all broker components
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/testingdata/fanout_deployment.yaml
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_status.yaml
Labels: approved, cla: yes, lgtm, size/S

#1731 Set empty secret to nil (0.15b)
  pkg/apis/duck/v1alpha1/credentials.go
  pkg/apis/duck/v1alpha1/pubsub_defaults.go
  pkg/apis/duck/v1alpha1/pubsub_defaults_test.go
  pkg/apis/duck/v1beta1/credentials.go
  pkg/apis/duck/v1beta1/pubsub_defaults.go
  pkg/apis/duck/v1beta1/pubsub_defaults_test.go
Labels: approved, cla: yes, lgtm, size/M

#1684 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/tools/go/analysis/validate.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1724 Check the decouple queue state instead of the overall broker state in ingress
  pkg/broker/config/targets.pb.go
  pkg/broker/config/targets.proto
  pkg/broker/ingress/handler_test.go
  pkg/broker/ingress/multi_topic_decouple_sink.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/testingdata/configmap.go
Labels: approved, cla: yes, lgtm, size/L

#1743 Update opencensus to v0.22.5-0.20200714042313-af30f77c5f65 (0.15b)
  go.mod
  go.sum
  vendor/go.opencensus.io/plugin/ocgrpc/client_metrics.go
  vendor/go.opencensus.io/plugin/ocgrpc/server_metrics.go
  vendor/go.opencensus.io/stats/view/aggregation.go
  vendor/go.opencensus.io/stats/view/aggregation_data.go
  vendor/go.opencensus.io/stats/view/collector.go
  vendor/go.opencensus.io/stats/view/view_to_metric.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1742 Update opencensus to v0.22.5-0.20200714042313-af30f77c5f65 (release-0.16)
  go.mod
  go.sum
  vendor/go.opencensus.io/plugin/ocgrpc/client_metrics.go
  vendor/go.opencensus.io/plugin/ocgrpc/server_metrics.go
  vendor/go.opencensus.io/stats/view/aggregation.go
  vendor/go.opencensus.io/stats/view/aggregation_data.go
  vendor/go.opencensus.io/stats/view/collector.go
  vendor/go.opencensus.io/stats/view/view_to_metric.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1681 Add configuration for data residency
  cmd/controller/wire.go
  cmd/controller/wire_gen.go
  config/config-data-residency.yaml
  config/core/configmaps/data-residency.yaml
  hack/update-codegen.sh
  pkg/apis/configs/dataresidency/dataresidency_defaults.go
  pkg/apis/configs/dataresidency/dataresidency_defaults_test.go
  pkg/apis/configs/dataresidency/defaults.go
  pkg/apis/configs/dataresidency/doc.go
  pkg/apis/configs/dataresidency/singleton.go
  pkg/apis/configs/dataresidency/singleton_test.go
  pkg/apis/configs/dataresidency/store.go
  pkg/apis/configs/dataresidency/store_test.go
  pkg/apis/configs/dataresidency/testdata/config-dataresidency.yaml
  pkg/apis/configs/dataresidency/zz_generated.deepcopy.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
  pkg/reconciler/intevents/topic/controller.go
  pkg/reconciler/intevents/topic/controller_test.go
  pkg/reconciler/intevents/topic/topic.go
  pkg/reconciler/testing/configmap.go
  pkg/reconciler/testing/pstest.go
  pkg/reconciler/testing/store.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/controller_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1737 Return 429 when ingress if sending too man messages, instead of 500
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
Labels: approved, cla: yes, lgtm, size/M

#1752 Remove unnecessary pin of github.com/blang/semver
  go.mod
  go.sum
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/go.mod
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sql.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1733 Use wire-gen injection for all controllers
  cmd/controller/main.go
  cmd/controller/wire.go
  cmd/controller/wire_gen.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
  pkg/reconciler/brokercell/controller.go
  pkg/reconciler/brokercell/controller_test.go
  pkg/reconciler/deployment/controller.go
  pkg/reconciler/deployment/controller_test.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#1758 Use no authentication in Probe Helper test storage client
  test/test_images/probe_helper/probe_helper_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1764 Pull in fixes from cloud events upstream
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/message.go
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/write_pubsub_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/event_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/to_event.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1767 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_validation.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/tracing/setup.go
  vendor/knative.dev/eventing/test/lib/duck/resource_checks.go
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/configmap/hash-gen/main.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/logkey/constants.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1762 Adjust broker fanout resource requirements to meet default delivery attempts per second target
  cmd/broker/fanout/main.go
  pkg/apis/intevents/v1alpha1/brokercell_defaults.go
  pkg/reconciler/brokercell/testingdata/fanout_deployment.yaml
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/fanout_hpa.yaml
Labels: approved, cla: yes, lgtm, size/S

#1768 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_redelivery_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1771 Fix misspellings and update-codegen
  config/core/configmaps/br-delivery.yaml
  config/core/configmaps/gcp-auth.yaml
  docs/examples/gcpbroker/README.md
  docs/install/install-gcp-broker.md
  pkg/apis/configs/broker/testdata/config-br-delivery.yaml
  pkg/apis/configs/gcpauth/testdata/config-gcp-auth.yaml
  pkg/reconciler/identity/testdata/config-gcp-auth-empty.yaml
  pkg/reconciler/identity/testdata/config-gcp-auth.yaml
Labels: approved, cla: yes, lgtm, size/S

#1747 Add data residency validation to webhook
  cmd/webhook/main.go
  pkg/apis/configs/dataresidency/dataresidency_defaults.go
  pkg/apis/configs/dataresidency/dataresidency_defaults_test.go
Labels: approved, cla: yes, lgtm, size/M

#1750 Use errgroup to gracefully shutdown HTTP server in knockdown
  test/test_images/internal/knockdown/knockdown.go
  test/test_images/storage_target/main.go
Labels: approved, cla: yes, lgtm, size/L

#1744 Separate the Data Plane to use a new GSA
  test/e2e-wi-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1745 Use OpenCensus Resource API to Report Broker and Trigger Metrics
  pkg/broker/handler/fanout_test.go
  pkg/broker/handler/retry_test.go
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
  pkg/metrics/delivery_reporter.go
  pkg/metrics/delivery_reporter_test.go
  pkg/metrics/ingress_reporter.go
  pkg/metrics/ingress_reporter_test.go
  pkg/metrics/testing/delivery.go
Labels: approved, cla: yes, lgtm, size/L

#1773 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/broker/v1beta1/broker/controller.go
  pkg/client/injection/reconciler/broker/v1beta1/broker/reconciler.go
  pkg/client/injection/reconciler/broker/v1beta1/trigger/controller.go
  pkg/client/injection/reconciler/broker/v1beta1/trigger/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudauditlogssource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudauditlogssource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudbuildsource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudbuildsource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudpubsubsource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudpubsubsource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudschedulersource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudschedulersource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudstoragesource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudstoragesource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudauditlogssource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudauditlogssource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudbuildsource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudbuildsource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudpubsubsource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudpubsubsource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudschedulersource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudschedulersource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudstoragesource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudstoragesource/reconciler.go
  pkg/client/injection/reconciler/intevents/v1/pullsubscription/controller.go
  pkg/client/injection/reconciler/intevents/v1/pullsubscription/reconciler.go
  pkg/client/injection/reconciler/intevents/v1/topic/controller.go
  pkg/client/injection/reconciler/intevents/v1/topic/reconciler.go
  pkg/client/injection/reconciler/intevents/v1alpha1/brokercell/controller.go
  pkg/client/injection/reconciler/intevents/v1alpha1/brokercell/reconciler.go
  pkg/client/injection/reconciler/intevents/v1beta1/pullsubscription/controller.go
  pkg/client/injection/reconciler/intevents/v1beta1/pullsubscription/reconciler.go
  pkg/client/injection/reconciler/intevents/v1beta1/topic/controller.go
  pkg/client/injection/reconciler/intevents/v1beta1/topic/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/metrics/metrics.go
  vendor/knative.dev/pkg/metrics/workqueue.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1775 Add rollout restart time annotation to Brokercell and update Brokercell deployments
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/brokercell/resources/args.go
  pkg/reconciler/brokercell/resources/deployments.go
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_restart_annotation.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment_with_restart_annotation.yaml
  pkg/reconciler/brokercell/testingdata/read_yaml.go
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_restart_annotation.yaml
Labels: approved, cla: yes, lgtm, size/L

#1772 Handle requests with very large payload
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
Labels: approved, cla: yes, lgtm, size/M

#1779 Add tommyreddad to reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1783 Add zhongduo (Jimmy) as a reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1782 [master] Update pubsub to 1.8.0 with error injection
  go.mod
  go.sum
  vendor/cloud.google.com/go/pubsub/CHANGES.md
  vendor/cloud.google.com/go/pubsub/apiv1/doc.go
  vendor/cloud.google.com/go/pubsub/go.mod
  vendor/cloud.google.com/go/pubsub/go.sum
  vendor/cloud.google.com/go/pubsub/pstest/fake.go
  vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
