Repository google/knative-gcp, pull requests merged in 2020-04, with the labels that each got.

#734 Add Propagation of W3C HTTP Trace Headers
  Gopkg.lock
  pkg/kncloudevents/good_client.go
  pkg/pubsub/adapter/adapter.go
  pkg/pubsub/adapter/adapter_test.go
  pkg/pubsub/publisher/publisher.go
  test/e2e/e2e_test.go
  test/e2e/lib/secrets.go
  test/lib.sh
  vendor/knative.dev/eventing/test/test_images/recordevents/README.md
  vendor/knative.dev/eventing/test/test_images/recordevents/eventstore.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/eventing/test/test_images/recordevents/pod.yaml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XL

#737 Updating workload identity install docs
  docs/install/install-knative-gcp.md
  hack/init_control_plane_gke.sh
Labels: approved, cla: yes, lgtm, size/S

#750 Update docs and validation message for the rename change
  docs/examples/channel/README.md
  docs/examples/channel/channel.yaml
  docs/examples/cloudauditlogssource/README.md
  docs/examples/cloudauditlogssource/cloudauditlogssource.yaml
  docs/examples/cloudpubsubsource/README.md
  docs/examples/cloudpubsubsource/cloudpubsubsource.yaml
  docs/examples/cloudschedulersource/README.md
  docs/examples/cloudschedulersource/cloudschedulersource.yaml
  docs/examples/cloudstoragesource/README.md
  docs/examples/cloudstoragesource/cloudstoragesource.yaml
  docs/examples/pullsubscription/README.md
  docs/examples/pullsubscription/pullsubscription.yaml
  docs/examples/topic/README.md
  docs/examples/topic/topic.yaml
  docs/install/config-br-default-channel.yaml
  docs/install/install-knative-gcp.md
  docs/install/pubsub-service-account.md
  hack/init_control_plane_gke.sh
  pkg/apis/duck/v1alpha1/credentials.go
  pkg/apis/events/v1alpha1/cloudschedulersource_validation_test.go
  pkg/apis/events/v1alpha1/cloudstoragesource_validation_test.go
  pkg/apis/messaging/v1alpha1/channel_validation_test.go
Labels: approved, cla: yes, lgtm, size/M

#751 Improvements on broker config lib
  pkg/broker/config/config.go
  pkg/broker/config/memory/memory.go
  pkg/broker/config/memory/memory_test.go
Labels: approved, cla: yes, lgtm, size/M

#754 Update CRD for renaming spec
  config/core/resources/channel.yaml
  config/core/resources/cloudauditlogssource.yaml
  config/core/resources/cloudpubsubsource.yaml
  config/core/resources/cloudschedulersource.yaml
  config/core/resources/cloudstoragesource.yaml
  config/core/resources/pullsubscription.yaml
  config/core/resources/topic.yaml
Labels: approved, cla: yes, lgtm, size/S

#753 Add recordevents as Required Test Image
  Gopkg.lock
  Gopkg.toml
Labels: approved, cla: yes, lgtm, size/XS

#756 [master] Format markdown
  docs/install/install-knative-gcp.md
  docs/install/pubsub-service-account.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#762 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/pkg/kncloudevents/message_client.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/mock_stats_reporter.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#755 Cloud build source
  Gopkg.lock
  cmd/controller/main.go
  cmd/webhook/main.go
  config/300-cloudbuildsource.yaml
  config/core/resources/cloudbuildsource.yaml
  config/core/roles/clusterrole.yaml
  docs/examples/cloudbuildsource/cloudbuildsource.yaml
  docs/examples/cloudbuildsource/event-display.yaml
  docs/examples/cloudpubsubsource/cloudpubsubsource.yaml
  docs/examples/cloudschedulersource/cloudschedulersource.yaml
  pkg/apis/events/v1alpha1/cloudbuildsource_defaults.go
  pkg/apis/events/v1alpha1/cloudbuildsource_defaults_test.go
  pkg/apis/events/v1alpha1/cloudbuildsource_lifecycle.go
  pkg/apis/events/v1alpha1/cloudbuildsource_lifecycle_test.go
  pkg/apis/events/v1alpha1/cloudbuildsource_types.go
  pkg/apis/events/v1alpha1/cloudbuildsource_types_test.go
  pkg/apis/events/v1alpha1/cloudbuildsource_validation.go
  pkg/apis/events/v1alpha1/cloudbuildsource_validation_test.go
  pkg/apis/events/v1alpha1/cloudpubsubsource_lifecycle.go
  pkg/apis/events/v1alpha1/cloudpubsubsource_lifecycle_test.go
  pkg/apis/events/v1alpha1/register.go
  pkg/apis/events/v1alpha1/resources/pullsubscription_status.go
  pkg/apis/events/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/events/v1alpha1/cloudbuildsource.go
  pkg/client/clientset/versioned/typed/events/v1alpha1/events_client.go
  pkg/client/clientset/versioned/typed/events/v1alpha1/fake/fake_cloudbuildsource.go
  pkg/client/clientset/versioned/typed/events/v1alpha1/fake/fake_events_client.go
  pkg/client/clientset/versioned/typed/events/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/events/v1alpha1/cloudbuildsource.go
  pkg/client/informers/externalversions/events/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/injection/informers/events/v1alpha1/cloudbuildsource/cloudbuildsource.go
  pkg/client/injection/informers/events/v1alpha1/cloudbuildsource/fake/fake.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudbuildsource/controller.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudbuildsource/reconciler.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudbuildsource/stub/controller.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudbuildsource/stub/reconciler.go
  pkg/client/listers/events/v1alpha1/cloudbuildsource.go
  pkg/client/listers/events/v1alpha1/expansion_generated.go
  pkg/pubsub/adapter/converters/build.go
  pkg/pubsub/adapter/converters/build_test.go
  pkg/pubsub/adapter/converters/converters.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/build/build.go
  pkg/reconciler/events/build/build_test.go
  pkg/reconciler/events/build/controller.go
  pkg/reconciler/events/build/controller_test.go
  pkg/reconciler/events/build/doc.go
  pkg/reconciler/events/pubsub/controller.go
  pkg/reconciler/events/pubsub/pubsub.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/pubsub/reconciler_test.go
  pkg/reconciler/testing/build.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/pubsub.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/extensions/extension.pb.go
Labels: approved, cla: yes, lgtm, size/XXL

#768 Small improvement on broker memory config for easier testing.
  pkg/broker/config/memory/memory.go
  pkg/broker/config/memory/memory_test.go
Labels: approved, cla: yes, lgtm, size/M

#772 [master] golang format tools
  cmd/webhook/main.go
  pkg/apis/events/v1alpha1/cloudbuildsource_defaults_test.go
  pkg/apis/events/v1alpha1/cloudbuildsource_types.go
  pkg/apis/events/v1alpha1/cloudbuildsource_types_test.go
  pkg/apis/events/v1alpha1/resources/pullsubscription_status.go
  pkg/pubsub/adapter/converters/build_test.go
  pkg/pubsub/adapter/converters/converters.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/build/build.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/pubsub/reconciler_test.go
  pkg/reconciler/testing/build.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#770 added docs for Cloud Build Source
  README.md
  docs/examples/cloudauditlogssource/README.md
  docs/examples/cloudbuildsource/README.md
  docs/examples/cloudpubsubsource/README.md
  docs/examples/cloudschedulersource/README.md
  docs/examples/cloudstoragesource/README.md
  docs/install/install-knative-gcp.md
  hack/init_control_plane.sh
  hack/init_control_plane_gke.sh
Labels: approved, cla: yes, lgtm, size/L

#775 Remove flaky test; It will be addressed in a follow up PR.
  pkg/broker/ingress/handler_test.go
Labels: approved, cla: yes, lgtm, size/M

#776 [master] Format markdown
  docs/examples/cloudbuildsource/README.md
  docs/install/install-knative-gcp.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#778 Switch to pkg release branch to prep for 0.14 release
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/kballard/go-shellquote/LICENSE
  vendor/github.com/kballard/go-shellquote/doc.go
  vendor/github.com/kballard/go-shellquote/quote.go
  vendor/github.com/kballard/go-shellquote/unquote.go
  vendor/knative.dev/eventing/config/200-jobrunner-clusterrole.yaml
  vendor/knative.dev/eventing/config/201-jobrunner-serviceaccount.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/200-channel-clusterrole.yaml
  vendor/knative.dev/eventing/config/brokers/mt-channel-broker/201-channel-clusterrolebinding.yaml
  vendor/knative.dev/eventing/pkg/kncloudevents/message_client.go
  vendor/knative.dev/eventing/pkg/tracing/traceparent_transformer.go
  vendor/knative.dev/eventing/pkg/tracing/transformers.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/config.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/images/Knative-Duck0.png
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/monitored_resources.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
  vendor/knative.dev/pkg/testing/resource.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/setup.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/options/options.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
Labels: approved, cla: yes, lgtm, size/XXL

#782 Remove `shell`
  docs/install/install-knative-gcp.md
Labels: approved, cla: yes, lgtm, size/XS

#783 Ensure that e2e Test Cleanup Functions are Run
  test/e2e/e2e_test.go
Labels: approved, cla: yes, lgtm, size/M

#774 Route events based on path
  Gopkg.lock
  cmd/broker/ingress/main.go
  pkg/broker/ingress/errors.go
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
  pkg/broker/ingress/multi_topic_decouple_sink.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
  pkg/broker/ingress/options.go
  third_party/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/XL

#761 Initial fanout service handlers
  Gopkg.lock
  pkg/broker/config/cache.go
  pkg/broker/config/config.go
  pkg/broker/handler/context/broker.go
  pkg/broker/handler/context/broker_test.go
  pkg/broker/handler/context/errs.go
  pkg/broker/handler/context/target.go
  pkg/broker/handler/context/target_test.go
  pkg/broker/handler/handler.go
  pkg/broker/handler/handler_test.go
  pkg/broker/handler/pool/fanout/pool.go
  pkg/broker/handler/pool/fanout/pool_test.go
  pkg/broker/handler/pool/options.go
  pkg/broker/handler/pool/options_test.go
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
  pkg/broker/handler/processors/fake.go
  pkg/broker/handler/processors/fake_test.go
  pkg/broker/handler/processors/fanout/processor.go
  pkg/broker/handler/processors/fanout/processor_test.go
  pkg/broker/handler/processors/filter/processor.go
  pkg/broker/handler/processors/filter/processor_test.go
  pkg/broker/handler/processors/processor.go
  pkg/broker/handler/processors/processor_test.go
  vendor/cloud.google.com/go/internal/testutil/cmp.go
  vendor/cloud.google.com/go/internal/testutil/context.go
  vendor/cloud.google.com/go/internal/testutil/rand.go
  vendor/cloud.google.com/go/internal/testutil/server.go
  vendor/cloud.google.com/go/internal/testutil/trace.go
  vendor/cloud.google.com/go/pubsub/pstest/fake.go
Labels: approved, cla: yes, lgtm, size/XXL

#791 [master] Format markdown
  docs/install/install-knative-gcp.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#788 [master] golang format tools
  pkg/broker/ingress/handler_test.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#780 Fix flaky volume config test with atomic file write
  pkg/broker/config/volume/volume_test.go
Labels: approved, cla: yes, lgtm, size/M

#803 Hacky workaround to a bad eventing nightly release.
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/XS

#794 Structural schema for Topic and PullSubscription CRDs.
  config/core/resources/pullsubscription.yaml
  config/core/resources/topic.yaml
Labels: approved, cla: yes, lgtm, size/M

#797 [master] golang format tools
  pkg/broker/handler/context/broker_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#799 [release-0.13] Pin test-infra to release branch
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
Labels: approved, cla: yes, lgtm, size/L

#807 Testing for WI retry configuration
  pkg/reconciler/identity/reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#790 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#793 Add main and a semi-e2e test for fanout service
  Gopkg.lock
  cmd/broker/fanout/kodata/HEAD
  cmd/broker/fanout/kodata/LICENSE
  cmd/broker/fanout/kodata/VENDOR-LICENSE
  cmd/broker/fanout/kodata/refs
  cmd/broker/fanout/main.go
  pkg/broker/handler/handler.go
  pkg/broker/handler/handler_test.go
  pkg/broker/handler/pool/fanout/pool.go
  pkg/broker/handler/pool/fanout/pool_test.go
  pkg/broker/handler/pool/options.go
  pkg/broker/handler/pool/options_test.go
Labels: approved, cla: yes, lgtm, size/XL

#809 Revert "Hacky workaround to a bad eventing nightly release. (#803)"
  test/lib.sh
Labels: approved, cla: yes, lgtm

#819 Skip TestBrokerTracing due to flakiness.
  test/e2e/e2e_test.go
Labels: approved, cla: yes, lgtm, size/XS

#811 Create pkg/duck/{v1alpha1,v1beta1}
  pkg/apis/events/v1alpha1/cloudauditlogssource_types.go
  pkg/apis/events/v1alpha1/cloudbuildsource_types.go
  pkg/apis/events/v1alpha1/cloudpubsubsource_types.go
  pkg/apis/events/v1alpha1/cloudschedulersource_types.go
  pkg/apis/events/v1alpha1/cloudstoragesource_types.go
  pkg/apis/messaging/v1alpha1/channel_types.go
  pkg/duck/v1alpha1/identifiable.go
  pkg/duck/v1alpha1/pubsubable.go
  pkg/duck/v1beta1/identifiable.go
  pkg/duck/v1beta1/pubsubable.go
  pkg/reconciler/identity/reconciler.go
  pkg/reconciler/pubsub/reconciler.go
Labels: approved, cla: yes, lgtm, size/M

#820 Reduce parallel running tests for WI
  test/e2e-wi-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#810 Pool volume watcher no longer exits on Remove
  pkg/broker/config/volume/volume.go
  pkg/broker/config/volume/volume_test.go
Labels: approved, cla: yes, lgtm, size/S

#813 Follow ups from 784.
  cmd/webhook/main.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_conversion_test.go
Labels: approved, cla: yes, lgtm, size/XS

#814 Fix PullSubscription and Topic's structural status schema
  config/core/resources/pullsubscription.yaml
  config/core/resources/topic.yaml
Labels: approved, cla: yes, lgtm, size/S

#822 Point test-infra to release-0.14 in prep for 0.14 release
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#816 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/serving/third_party/istio-1.5-latest
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#823 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/serving/third_party/istio-1.4-latest
  vendor/knative.dev/serving/third_party/istio-stable
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#826 Point eventing and serving to release-0.14 branches
  Gopkg.lock
  Gopkg.toml
Labels: approved, cla: yes, lgtm, size/S

#836 Small update on doc
  docs/install/pubsub-service-account.md
Labels: approved, cla: yes, lgtm, size/XS

#817 Basic Broker Retry Implementation
  cmd/broker/retry/kodata/HEAD
  cmd/broker/retry/kodata/LICENSE
  cmd/broker/retry/kodata/VENDOR-LICENSE
  cmd/broker/retry/kodata/refs
  cmd/broker/retry/main.go
  pkg/broker/config/cache.go
  pkg/broker/config/cache_test.go
  pkg/broker/config/config.go
  pkg/broker/config/config_test.go
  pkg/broker/handler/pool/retry/pool.go
  pkg/broker/handler/pool/retry/pool_test.go
Labels: approved, cla: yes, lgtm, size/XL

#824 Structural schemas for all the sources we intend to include in release/1
  config/core/resources/cloudauditlogssource.yaml
  config/core/resources/cloudpubsubsource.yaml
  config/core/resources/cloudschedulersource.yaml
  config/core/resources/cloudstoragesource.yaml
Labels: approved, cla: yes, lgtm, size/XL

#841 Get default project ID from metadata
  cmd/broker/fanout/main.go
  pkg/broker/handler/pool/fanout/pool.go
Labels: approved, cla: yes, lgtm, size/S

#825 Using one controller to support both secret and workload identity
  cmd/controller/main.go
  config/500-controller.yaml
  config/core/deployments/controller-gke.yaml
  config/core/deployments/controller.yaml
  docs/install/install-knative-gcp.md
  test/e2e-wi-tests.sh
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/L

#868 [master] Format markdown
  docs/install/install-knative-gcp.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#864 Symlink CloudBuildSource.
  config/300-cloudbuildsource.yaml
Labels: approved, cla: yes, lgtm, size/L

#856 Remove pubsub.cloud.google.com/crd-install label selector
  docs/install/install-knative-gcp.md
Labels: approved, cla: yes, lgtm, size/XS

#872 Add myself to reviewers and approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#870 Cleanups for broker handler
  pkg/broker/config/cache_test.go
  pkg/broker/config/config.go
  pkg/broker/handler/context/broker.go
  pkg/broker/handler/context/broker_test.go
  pkg/broker/handler/context/errs.go
  pkg/broker/handler/context/target.go
  pkg/broker/handler/context/target_test.go
  pkg/broker/handler/pool/fanout/pool.go
  pkg/broker/handler/pool/fanout/pool_test.go
  pkg/broker/handler/pool/options.go
  pkg/broker/handler/pool/options_test.go
  pkg/broker/handler/pool/retry/pool.go
  pkg/broker/handler/pool/retry/pool_test.go
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
  pkg/broker/handler/processors/fanout/processor.go
  pkg/broker/handler/processors/fanout/processor_test.go
  pkg/broker/handler/processors/filter/processor.go
  pkg/broker/handler/processors/filter/processor_test.go
Labels: approved, cla: yes, lgtm, size/L

#869 Point dependencies back to master branches
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/eventing/test/conformance/helpers/channel.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_crd_name_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_test_helper.go
  vendor/knative.dev/pkg/DEVELOPMENT.md
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/serving/pkg/apis/networking/register.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#874 Unit test no longer tries to find credentials
  pkg/broker/handler/pool/retry/pool_test.go
Labels: approved, cla: yes, lgtm, size/M

#879 Inject clients to context before using it in broker retry main
  cmd/broker/retry/main.go
Labels: approved, cla: yes, lgtm, size/XS

#881 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#888 Increase coverage of non-generated broker types code
  pkg/apis/broker/v1beta1/broker_lifecycle_test.go
  pkg/apis/broker/v1beta1/broker_types_test.go
  pkg/apis/broker/v1beta1/register_test.go
  pkg/apis/broker/v1beta1/test_helper.go
  pkg/apis/broker/v1beta1/trigger_lifecycle_test.go
  pkg/apis/broker/v1beta1/trigger_types_test.go
Labels: approved, cla: yes, lgtm, size/L

#884 Remove status.ServiceAccountName from last reconcile circle in Identity reconciler
  pkg/reconciler/events/build/controller.go
  pkg/reconciler/events/pubsub/controller.go
  pkg/reconciler/identity/reconciler.go
  pkg/reconciler/identity/reconciler_test.go
Labels: approved, cla: yes, lgtm, size/S

#893 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/cached.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#827 Sources v1beta1 conversions
  cmd/webhook/main.go
  config/core/resources/cloudauditlogssource.yaml
  config/core/resources/cloudpubsubsource.yaml
  config/core/resources/cloudschedulersource.yaml
  config/core/resources/cloudstoragesource.yaml
  pkg/apis/convert/conversion_helper.go
  pkg/apis/convert/conversion_helper_test.go
  pkg/apis/events/register.go
  pkg/apis/events/v1alpha1/cloudauditlogssource_conversion.go
  pkg/apis/events/v1alpha1/cloudauditlogssource_conversion_test.go
  pkg/apis/events/v1alpha1/cloudauditlogssource_types.go
  pkg/apis/events/v1alpha1/cloudpubsubsource_conversion.go
  pkg/apis/events/v1alpha1/cloudpubsubsource_conversion_test.go
  pkg/apis/events/v1alpha1/cloudpubsubsource_types.go
  pkg/apis/events/v1alpha1/cloudschedulersource_conversion.go
  pkg/apis/events/v1alpha1/cloudschedulersource_conversion_test.go
  pkg/apis/events/v1alpha1/cloudschedulersource_types.go
  pkg/apis/events/v1alpha1/cloudstoragesource_conversion.go
  pkg/apis/events/v1alpha1/cloudstoragesource_conversion_test.go
  pkg/apis/events/v1alpha1/cloudstoragesource_types.go
  pkg/apis/events/v1beta1/cloudauditlogssource_conversion.go
  pkg/apis/events/v1beta1/cloudauditlogssource_conversion_test.go
  pkg/apis/events/v1beta1/cloudauditlogssource_types.go
  pkg/apis/events/v1beta1/cloudpubsubsource_conversion.go
  pkg/apis/events/v1beta1/cloudpubsubsource_conversion_test.go
  pkg/apis/events/v1beta1/cloudpubsubsource_types.go
  pkg/apis/events/v1beta1/cloudschedulersource_conversion.go
  pkg/apis/events/v1beta1/cloudschedulersource_conversion_test.go
  pkg/apis/events/v1beta1/cloudschedulersource_types.go
  pkg/apis/events/v1beta1/cloudstoragesource_conversion.go
  pkg/apis/events/v1beta1/cloudstoragesource_conversion_test.go
  pkg/apis/events/v1beta1/cloudstoragesource_types.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_conversion.go
  pkg/apis/pubsub/v1alpha1/topic_conversion.go
Labels: approved, cla: yes, lgtm, size/XXL

#849 Channel CRD has a structural schema
  config/core/resources/channel.yaml
Labels: approved, cla: yes, lgtm, size/L

#889 Send events to retry queue on initial delivery failure
  pkg/broker/handler/pool/fanout/pool.go
  pkg/broker/handler/pool/fanout/pool_test.go
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
  pkg/broker/handler/processors/fanout/processor.go
Labels: approved, cla: yes, lgtm, size/L

#894 Reformat installation docs to be more readable
  docs/install/authentication-machanisms-gcp.md
  docs/install/install-knative-gcp.md
  docs/install/pubsub-service-account.md
Labels: approved, cla: yes, lgtm, size/XL

#895 Properly handle io.EOF from receiver
  pkg/broker/handler/handler.go
Labels: approved, cla: yes, lgtm, size/XS

#883 Add a semi-e2e test for retry service and some refactoring
  cmd/broker/fanout/main.go
  cmd/broker/ingress/main.go
  cmd/broker/retry/main.go
  pkg/broker/handler/pool/fanout/pool.go
  pkg/broker/handler/pool/fanout/pool_test.go
  pkg/broker/handler/pool/pool.go
  pkg/broker/handler/pool/pool_test.go
  pkg/broker/handler/pool/retry/pool.go
  pkg/broker/handler/pool/retry/pool_test.go
  pkg/broker/handler/pool/testing/pool.go
Labels: approved, cla: yes, lgtm, size/XL

#833 Add IAMPolicyManager to serialize IAM policy changes
  Gopkg.lock
  pkg/gclient/iam/admin/client.go
  pkg/gclient/iam/admin/interfaces.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/auditlogs/controller.go
  pkg/reconciler/events/build/build_test.go
  pkg/reconciler/events/build/controller.go
  pkg/reconciler/events/pubsub/controller.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/events/scheduler/controller.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/controller.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/identity/iam/iam_policy.go
  pkg/reconciler/identity/iam/iam_policy_test.go
  pkg/reconciler/identity/reconciler.go
  pkg/reconciler/identity/reconciler_test.go
  pkg/reconciler/messaging/channel/channel_test.go
  pkg/reconciler/messaging/channel/controller.go
  pkg/reconciler/pubsub/pullsubscription/keda/controller.go
  pkg/reconciler/pubsub/pullsubscription/static/controller.go
  pkg/reconciler/pubsub/topic/controller.go
  pkg/reconciler/testing/identity.go
  test/e2e-wi-tests.sh
  vendor/cloud.google.com/go/iam/admin/apiv1/doc.go
  vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go
  vendor/cloud.google.com/go/iam/admin/apiv1/path_funcs.go
  vendor/cloud.google.com/go/iam/admin/apiv1/policy_methods.go
  vendor/google.golang.org/api/iam/v1/iam-gen.go
  vendor/google.golang.org/genproto/googleapis/iam/admin/v1/iam.pb.go
Labels: approved, cla: yes, lgtm, size/XXL

#902 [master] golang format tools
  pkg/broker/config/targets.pb.go
  pkg/reconciler/identity/iam/iam_policy.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#900 [master] Format markdown
  docs/install/authentication-machanisms-gcp.md
  docs/install/install-knative-gcp.md
  docs/install/pubsub-service-account.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#915 Correct Broker lifecycle test to reflect its intent
  pkg/apis/broker/v1beta1/broker_lifecycle_test.go
Labels: approved, cla: yes, lgtm, size/XS

#911 Refactor broker handler pool testing (and cleanups)
  .gitattributes
  Gopkg.lock
  cmd/broker/fanout/main.go
  cmd/broker/retry/main.go
  pkg/broker/handler/pool/fanout/pool.go
  pkg/broker/handler/pool/fanout/pool_test.go
  pkg/broker/handler/pool/options.go
  pkg/broker/handler/pool/options_test.go
  pkg/broker/handler/pool/retry/pool.go
  pkg/broker/handler/pool/retry/pool_test.go
  pkg/broker/handler/pool/testing/helper.go
  pkg/broker/handler/pool/testing/pool.go
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#907 Update broker data plane pod annotation to trigger configmap volume refresh
  Gopkg.lock
  config/core/roles/clusterrole.yaml
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
  pkg/reconciler/broker/resources/deployments.go
  pkg/reconciler/broker/resources/deployments_test.go
  pkg/reconciler/broker/resources/pods.go
  pkg/reconciler/testing/listers.go
Labels: approved, cla: yes, lgtm, size/L

#921 Make CloudBuildSource's schema structural.
  config/core/resources/cloudbuildsource.yaml
Labels: approved, cla: yes, lgtm, size/L

#903 Update docs for enabling Workload Identity on an existing cluster
  docs/install/authentication-mechanisms-gcp.md
  docs/install/install-knative-gcp.md
  docs/install/pubsub-service-account.md
  hack/init_control_plane_gke.sh
Labels: approved, cla: yes, lgtm, size/M

#926 [master] Format markdown
  docs/install/authentication-mechanisms-gcp.md
  docs/install/install-gcp-broker.md
  docs/install/install-knative-gcp.md
  docs/install/pubsub-service-account.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#925 Add filter processor to broker retry
  pkg/broker/handler/pool/retry/pool.go
  pkg/broker/handler/pool/retry/pool_test.go
Labels: approved, cla: yes, lgtm, size/M

#923 Use pstest to Test Broker Ingress
  pkg/broker/ingress/handler_test.go
  pkg/broker/ingress/multi_topic_decouple_sink.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
  pkg/broker/ingress/options.go
Labels: approved, cla: yes, lgtm, size/L

#931 Check for nil in Validate tests
  pkg/apis/broker/v1beta1/broker_validation_test.go
  pkg/apis/broker/v1beta1/trigger_validation_test.go
Labels: approved, cla: yes, lgtm, size/XS

#932 Allow unit tests to run locally
  pkg/broker/config/memory/memory_test.go
  pkg/reconciler/events/auditlogs/controller.go
  pkg/reconciler/events/auditlogs/controller_test.go
  pkg/reconciler/events/build/controller.go
  pkg/reconciler/events/build/controller_test.go
  pkg/reconciler/events/pubsub/controller.go
  pkg/reconciler/events/pubsub/controller_test.go
  pkg/reconciler/events/scheduler/controller.go
  pkg/reconciler/events/scheduler/controller_test.go
  pkg/reconciler/events/storage/controller.go
  pkg/reconciler/events/storage/controller_test.go
  pkg/reconciler/messaging/channel/controller.go
  pkg/reconciler/messaging/channel/controller_test.go
  pkg/reconciler/pubsub/pullsubscription/keda/controller.go
  pkg/reconciler/pubsub/pullsubscription/keda/controller_test.go
  pkg/reconciler/pubsub/pullsubscription/static/controller.go
  pkg/reconciler/pubsub/pullsubscription/static/controller_test.go
  pkg/reconciler/pubsub/topic/controller.go
  pkg/reconciler/pubsub/topic/controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#934 Reconcile handlers on decouple/retry subscription updates
  pkg/broker/handler/handler.go
  pkg/broker/handler/handler_test.go
  pkg/broker/handler/pool/fanout/pool.go
  pkg/broker/handler/pool/fanout/pool_test.go
  pkg/broker/handler/pool/retry/pool.go
  pkg/broker/handler/pool/retry/pool_test.go
  pkg/broker/handler/pool/testing/helper.go
Labels: approved, cla: yes, lgtm, size/L

#937 [master] Auto-update dependencies
  Gopkg.lock
  pkg/client/injection/reconciler/broker/v1beta1/broker/controller.go
  pkg/client/injection/reconciler/broker/v1beta1/broker/reconciler.go
  pkg/client/injection/reconciler/broker/v1beta1/trigger/controller.go
  pkg/client/injection/reconciler/broker/v1beta1/trigger/reconciler.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudauditlogssource/controller.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudauditlogssource/reconciler.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudbuildsource/controller.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudbuildsource/reconciler.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudpubsubsource/controller.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudpubsubsource/reconciler.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudschedulersource/controller.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudschedulersource/reconciler.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudstoragesource/controller.go
  pkg/client/injection/reconciler/events/v1alpha1/cloudstoragesource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudauditlogssource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudauditlogssource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudpubsubsource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudpubsubsource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudschedulersource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudschedulersource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudstoragesource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudstoragesource/reconciler.go
  pkg/client/injection/reconciler/intevents/v1alpha1/brokercell/controller.go
  pkg/client/injection/reconciler/intevents/v1alpha1/brokercell/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  pkg/client/injection/reconciler/policy/v1alpha1/eventpolicybinding/controller.go
  pkg/client/injection/reconciler/policy/v1alpha1/eventpolicybinding/reconciler.go
  pkg/client/injection/reconciler/policy/v1alpha1/httppolicybinding/controller.go
  pkg/client/injection/reconciler/policy/v1alpha1/httppolicybinding/reconciler.go
  pkg/client/injection/reconciler/pubsub/v1alpha1/pullsubscription/controller.go
  pkg/client/injection/reconciler/pubsub/v1alpha1/pullsubscription/reconciler.go
  pkg/client/injection/reconciler/pubsub/v1alpha1/topic/controller.go
  pkg/client/injection/reconciler/pubsub/v1alpha1/topic/reconciler.go
  pkg/client/injection/reconciler/pubsub/v1beta1/pullsubscription/controller.go
  pkg/client/injection/reconciler/pubsub/v1beta1/pullsubscription/reconciler.go
  pkg/client/injection/reconciler/pubsub/v1beta1/topic/controller.go
  pkg/client/injection/reconciler/pubsub/v1beta1/topic/reconciler.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_channelable_manipulator_cluster_role_test_helper.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#933 Add Trace Propagation Test to the Ingress Handler
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
Labels: approved, cla: yes, lgtm, size/M

#941 Add observability package with setup and teardown functions
  cmd/broker/fanout/main.go
  cmd/broker/ingress/main.go
  cmd/broker/retry/main.go
  config/broker/deployments/broker.yaml
  pkg/observability/observability.go
Labels: approved, cla: yes, lgtm, size/L

#936 Add examples for gcp broker
  docs/examples/gcpbroker/README.md
  docs/examples/gcpbroker/broker.yaml
  docs/examples/gcpbroker/event-consumers.yaml
  docs/examples/gcpbroker/event-publisher.yaml
  docs/examples/gcpbroker/namespace.yaml
  docs/examples/gcpbroker/triggers.yaml
  docs/install/install-gcp-broker.md
Labels: approved, cla: yes, lgtm, size/XL

#943 Add brokercell controller and reconciler skeleton
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/brokercell/controller.go
  pkg/reconciler/brokercell/controller_test.go
  pkg/reconciler/testing/brokercell.go
  pkg/reconciler/testing/listers.go
Labels: approved, cla: yes, lgtm, size/L

#947 [master] Format markdown
  docs/examples/gcpbroker/README.md
  docs/install/install-gcp-broker.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#948 Fix fanout and ingress due to duplicated metric views
  cmd/broker/fanout/main.go
  cmd/broker/retry/main.go
Labels: approved, cla: yes, lgtm, size/S

#957 Increase fanout concurrency in installation yaml
  config/broker/deployments/broker.yaml
Labels: approved, cla: yes, lgtm, size/XS

#965 Truncate pubsub names if greater than 255 chars
  pkg/reconciler/broker/resources/names.go
  pkg/reconciler/broker/resources/names_test.go
Labels: approved, cla: yes, lgtm, size/L

#961 Add a tiny delay in SyncPool test to avoid flakiness
  pkg/broker/handler/pool/pool_test.go
Labels: approved, cla: yes, lgtm, size/M

#960 Have broker fanout handle timeout gracefully for each individual target
  cmd/broker/fanout/main.go
  cmd/broker/retry/main.go
  pkg/broker/handler/pool/fanout/pool.go
  pkg/broker/handler/pool/fanout/pool_test.go
  pkg/broker/handler/pool/options.go
  pkg/broker/handler/pool/options_test.go
  pkg/broker/handler/pool/testing/helper.go
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
Labels: approved, cla: yes, lgtm, size/L
