Repository google/knative-gcp, pull requests merged in 2020-12, with the labels that each got.

#1956 Update out-dated installation doc for installing from a release
  docs/install/install-knative-gcp.md
Labels: approved, cla: yes, lgtm, size/S

#1962 [Automated] Format markdown
  docs/install/install-knative-gcp.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1960 [release-0.19] Upgrade trigger's serving subscriber version to v1
  .github/workflows/check-pr.yml
  cmd/webhook/main.go
  pkg/apis/broker/v1beta1/trigger_defaults.go
  pkg/apis/broker/v1beta1/trigger_defaults_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1966 [release-0.18] Upgrade trigger's serving subscriber version to v1
  .github/workflows/check-pr.yml
  cmd/webhook/main.go
  pkg/apis/broker/v1beta1/trigger_defaults.go
  pkg/apis/broker/v1beta1/trigger_defaults_test.go
Labels: approved, cla: yes, lgtm, size/M

#1965 Customize check list for disrespectful terms
  .woke.yaml
Labels: approved, cla: yes, lgtm, size/M

#1947 Use K_GCP_AUTH_TYPE to differentiate authentication mode
  pkg/apis/intevents/v1alpha1/brokercell_lifecycle.go
  pkg/apis/intevents/v1alpha1/brokercell_lifecycle_test.go
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/brokercell/controller.go
  pkg/reconciler/brokercell/controller_test.go
  pkg/reconciler/brokercell/resources/args.go
  pkg/reconciler/brokercell/resources/deployments.go
  pkg/reconciler/brokercell/testingdata/fanout_deployment.yaml
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_restart_annotation.yaml
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment_with_filtering_annotation.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment_with_restart_annotation.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_restart_annotation.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_status.yaml
  pkg/reconciler/events/build/controller.go
  pkg/reconciler/intevents/pullsubscription/keda/controller.go
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/intevents/pullsubscription/reconciler.go
  pkg/reconciler/intevents/pullsubscription/resources/receive_adapter.go
  pkg/reconciler/intevents/pullsubscription/resources/receive_adapter_test.go
  pkg/reconciler/intevents/pullsubscription/static/controller.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription_test.go
  pkg/reconciler/intevents/reconciler.go
  pkg/reconciler/intevents/topic/controller.go
  pkg/reconciler/intevents/topic/resources/publisher.go
  pkg/reconciler/intevents/topic/resources/publisher_test.go
  pkg/reconciler/intevents/topic/topic.go
  pkg/reconciler/intevents/topic/topic_test.go
  pkg/reconciler/testing/brokercell.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/secret.go
  pkg/reconciler/testing/v1/topic.go
  pkg/utils/authcheck/authtype.go
  pkg/utils/authcheck/authtype_test.go
  pkg/utils/authcheck/enqueue.go
  pkg/utils/authcheck/enqueue_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1967 Add AlexandraRoatis as reviewer and as approver
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1969 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/hack/shell/project.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1970 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1971 Revert "[Automated] Update actions"
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1968 Remove cluster-wide Secret reading permissions.
  config/core/roles/clusterrole.yaml
  pkg/reconciler/brokercell/controller.go
  pkg/reconciler/brokercell/controller_test.go
  pkg/reconciler/deployment/controller.go
  pkg/reconciler/deployment/controller_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/factory/fake/fake.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1976 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/.gitignore
  vendor/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/README.md
  vendor/github.com/blendle/zapdriver/config.go
  vendor/github.com/blendle/zapdriver/core.go
  vendor/github.com/blendle/zapdriver/encoder.go
  vendor/github.com/blendle/zapdriver/go.mod
  vendor/github.com/blendle/zapdriver/go.sum
  vendor/github.com/blendle/zapdriver/http.go
  vendor/github.com/blendle/zapdriver/label.go
  vendor/github.com/blendle/zapdriver/logger.go
  vendor/github.com/blendle/zapdriver/operation.go
  vendor/github.com/blendle/zapdriver/report.go
  vendor/github.com/blendle/zapdriver/service.go
  vendor/github.com/blendle/zapdriver/source.go
  vendor/github.com/blendle/zapdriver/trace.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#1954 Refactor probe helper to allow for multi-tenancy and easier probe development
  test/test_images/probe_helper/health.go
  test/test_images/probe_helper/main.go
  test/test_images/probe_helper/probe/broker_e2e_delivery.go
  test/test_images/probe_helper/probe/cloudauditlogs.go
  test/test_images/probe_helper/probe/cloudpubsub.go
  test/test_images/probe_helper/probe/cloudscheduler.go
  test/test_images/probe_helper/probe/cloudstorage.go
  test/test_images/probe_helper/probe/handler.go
  test/test_images/probe_helper/probe/helper.go
  test/test_images/probe_helper/probe/helper_test.go
  test/test_images/probe_helper/probe_helper.go
  test/test_images/probe_helper/probe_helper.yaml
  test/test_images/probe_helper/utils.go
  test/test_images/probe_helper/utils/liveness.go
  test/test_images/probe_helper/utils/received_events.go
  test/test_images/probe_helper/utils/sync_time.go
Labels: approved, cla: yes, lgtm, size/XXL

#1981 Remove former team members from OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1980 Configure webhook port in yaml
  cmd/webhook/main.go
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1979 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1974 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1984 Update woke setup
  .woke.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1983 Use wire to inject dependencies for probe helper
  test/test_images/probe_helper/main.go
  test/test_images/probe_helper/probe/handlers/broker_e2e_delivery.go
  test/test_images/probe_helper/probe/handlers/cloudauditlogs.go
  test/test_images/probe_helper/probe/handlers/cloudpubsub.go
  test/test_images/probe_helper/probe/handlers/cloudscheduler.go
  test/test_images/probe_helper/probe/handlers/cloudstorage.go
  test/test_images/probe_helper/probe/handlers/event_type.go
  test/test_images/probe_helper/probe/handlers/interface.go
  test/test_images/probe_helper/probe/handlers/providers.go
  test/test_images/probe_helper/probe/helper.go
  test/test_images/probe_helper/probe/helper_test.go
  test/test_images/probe_helper/probe/providers.go
  test/test_images/probe_helper/probe/test_providers.go
  test/test_images/probe_helper/probe/wire.go
  test/test_images/probe_helper/probe/wire_gen.go
  test/test_images/probe_helper/utils/extensions.go
  test/test_images/probe_helper/utils/liveness.go
  test/test_images/probe_helper/utils/received_events.go
  test/test_images/probe_helper/wire.go
  test/test_images/probe_helper/wire_gen.go
Labels: approved, cla: yes, lgtm, size/XL

#1985 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#1987 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1988 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1990 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1992 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1996 Fix typo, 'reply' -> 'replay'.
  test/upgrade/prober/verify.go
Labels: approved, cla: yes, lgtm, size/XS

#1999 feat/perf-test: Add google-broker-key secret to perf test
  test/performance/performance-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1993 Avoid overwriting eventing clusterrole
  config/core/roles/addressable-resolvers-clusterrole.yaml
  config/core/roles/clusterrolebinding.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2001 Remove redundant helper function for GCPbroker e2e test
  test/e2e/test_gcp_broker.go
  test/lib/creation.go
  test/lib/resources/knative_gcp.go
Labels: approved, cla: yes, lgtm, size/M

#2002 Make the knockdown test_image a non-internal package
  test/test_images/auditlogs_target/main.go
  test/test_images/build_target/main.go
  test/test_images/knockdown/knockdown.go
  test/test_images/pubsub_target/main.go
  test/test_images/scheduler_target/main.go
  test/test_images/storage_target/main.go
  test/test_images/target/main.go
Labels: approved, cla: yes, lgtm, size/S

#1975 Rename GSAs to be brand-agnostic
  docs/examples/cloudstoragesource/README.md
  docs/examples/keda/README.md
  docs/how-to/authentication-mechanism-troubleshooting.md
  docs/how-to/metrics.md
  docs/install/authentication-mechanisms-gcp.md
  docs/install/dataplane-service-account.md
  docs/install/install-gcp-broker.md
  hack/init_control_plane.sh
  hack/init_control_plane_gke.sh
  hack/init_data_plane.sh
  hack/init_data_plane_gke.sh
  hack/lib.sh
  test/e2e-common.sh
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, size/L

#2003 [Automated] Format markdown
  docs/how-to/authentication-mechanism-troubleshooting.md
  docs/install/authentication-mechanisms-gcp.md
  docs/install/dataplane-service-account.md
  docs/install/install-gcp-broker.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#2005 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#2004 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#2006 remove non-inclusive term
  docs/examples/keda/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2008 Add enableServiceLinks:false to webhook yaml
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2009 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/mailru/easyjson/.gitignore
  vendor/github.com/mailru/easyjson/.travis.yml
  vendor/github.com/mailru/easyjson/Makefile
  vendor/github.com/mailru/easyjson/README.md
  vendor/github.com/mailru/easyjson/go.mod
  vendor/github.com/mailru/easyjson/helpers.go
  vendor/github.com/mailru/easyjson/raw.go
  vendor/github.com/tsenart/vegeta/lib/results_easyjson.go
  vendor/github.com/tsenart/vegeta/v12/LICENSE
  vendor/github.com/tsenart/vegeta/v12/lib/attack.go
  vendor/github.com/tsenart/vegeta/v12/lib/attack_fuzz.go
  vendor/github.com/tsenart/vegeta/v12/lib/histogram.go
  vendor/github.com/tsenart/vegeta/v12/lib/metrics.go
  vendor/github.com/tsenart/vegeta/v12/lib/pacer.go
  vendor/github.com/tsenart/vegeta/v12/lib/reporters.go
  vendor/github.com/tsenart/vegeta/v12/lib/results.go
  vendor/github.com/tsenart/vegeta/v12/lib/results_easyjson.go
  vendor/github.com/tsenart/vegeta/v12/lib/results_fuzz.go
  vendor/github.com/tsenart/vegeta/v12/lib/target.schema.json
  vendor/github.com/tsenart/vegeta/v12/lib/targets.go
  vendor/github.com/tsenart/vegeta/v12/lib/targets_easyjson.go
  vendor/github.com/tsenart/vegeta/v12/lib/targets_fuzz.go
  vendor/github.com/tsenart/vegeta/v12/lib/util_fuzz.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/channel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/inmemorychannel.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/eventing/test/performance/infra/sender/http_load_generator.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/test/mako/config/slack.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XXL

#2013 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2016 feat/trigger: enable trigger to send to different namespace
  pkg/reconciler/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/XS

#2018 Remove honnef.co pin from go.mod, as we no longer use that dependency.
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2020 Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/observability/observability.go
  pkg/reconciler/reconciler.go
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2014 Authentication check: additional k8s Event check for Secret absence in source
  config/core/roles/clusterrole.yaml
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription.go
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription_test.go
  pkg/reconciler/testing/deployment.go
  pkg/utils/authcheck/list.go
  pkg/utils/authcheck/list_test.go
Labels: approved, cla: yes, lgtm, size/XL

#2021 Remove redundant tag keys from delivery metrics
  pkg/metrics/delivery_reporter.go
Labels: approved, cla: yes, lgtm, size/XS

#2022 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2026 Remove unneeded method
  pkg/broker/config/cache.go
  pkg/broker/config/cache_test.go
  pkg/broker/config/config.go
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/resources/configmap.go
Labels: approved, cla: yes, lgtm, size/M

#2027 Remove GetBroker, GetTarget, and EqualsBytes
  pkg/broker/config/cache.go
  pkg/broker/config/cache_test.go
  pkg/broker/config/config.go
  pkg/broker/config/memory/memory_test.go
  pkg/broker/ingress/multi_topic_decouple_sink.go
Labels: approved, cla: yes, lgtm, size/M

#2025 Webhook has only namespaced Secret permissions, rather than cluster-w…
  config/201-webhook-role.yaml
  config/core/roles/rolebinding.yaml
  config/core/roles/webhook-clusterrole.yaml
  config/core/roles/webhook-role.yaml
Labels: approved, cla: yes, lgtm, size/M

#1955 Mark broker failed for trigger if the broker doesn't exist
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/S

#2028 Replace string with {Broker,Target}Key structs in the Targets interfaces
  pkg/broker/config/cache.go
  pkg/broker/config/cache_test.go
  pkg/broker/config/config.go
  pkg/broker/config/config_test.go
  pkg/broker/config/key.go
  pkg/broker/config/key_test.go
  pkg/broker/config/memory/memory.go
  pkg/broker/config/memory/memory_test.go
  pkg/broker/handler/context/broker.go
  pkg/broker/handler/context/broker_test.go
  pkg/broker/handler/context/target.go
  pkg/broker/handler/context/target_test.go
  pkg/broker/handler/fanout.go
  pkg/broker/handler/fanout_test.go
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
  pkg/broker/handler/processors/fanout/processor.go
  pkg/broker/handler/processors/fanout/processor_test.go
  pkg/broker/handler/processors/filter/processor.go
  pkg/broker/handler/processors/filter/processor_test.go
  pkg/broker/handler/retry.go
  pkg/broker/handler/retry_test.go
  pkg/broker/handler/testing/helper.go
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
  pkg/broker/ingress/multi_topic_decouple_sink.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/testingdata/configmap.go
  vendor/github.com/cloudevents/sdk-go/v2/client/test/mock_client.go
  vendor/github.com/cloudevents/sdk-go/v2/client/test/test.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/gochan/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/gochan/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/gochan/receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/gochan/requester.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/gochan/responder.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/gochan/sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL
