Repository google/knative-gcp, pull requests merged in 2020-06, with the labels that each got.

#1150 [master] golang format tools
  pkg/reconciler/broker/broker_targets_test.go
  pkg/reconciler/helper_test.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/trigger.go
  test/e2e/lib/constants.go
  test/e2e/lib/gvks.go
  test/e2e/lib/helpers/broker_event_transformation_test_with_source.go
  test/e2e/lib/pubsub.go
  test/e2e/lib/resources/kube.go
  test/e2e/lib/types.go
  test/e2e/test_pubsub.go
  test/e2e/test_storage.go
  test/test_images/auditlogs_target/main.go
  test/test_images/pubsub_receiver/main.go
  test/test_images/pubsub_target/main.go
  test/test_images/scheduler_receiver/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1174 Wait until pods ready after restarting pods for secret/wi
  test/e2e-secret-tests.sh
  test/e2e-wi-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1153 Add HPA to brokercell controller
  config/core/roles/clusterrole.yaml
  hack/update-codegen.sh
  pkg/client/injection/kube/client/client.go
  pkg/client/injection/kube/client/fake/fake.go
  pkg/client/injection/kube/informers/autoscaling/v2beta2/horizontalpodautoscaler/fake/fake.go
  pkg/client/injection/kube/informers/autoscaling/v2beta2/horizontalpodautoscaler/horizontalpodautoscaler.go
  pkg/client/injection/kube/informers/factory/factory.go
  pkg/client/injection/kube/informers/factory/fake/fake.go
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/brokercell/controller.go
  pkg/reconciler/brokercell/controller_test.go
  pkg/reconciler/brokercell/resources/args.go
  pkg/reconciler/brokercell/resources/deployments.go
  pkg/reconciler/brokercell/resources/hpa.go
  pkg/reconciler/brokercell/testingdata/fanout_deployment.yaml
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/fanout_hpa.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/ingress_hpa.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/retry_hpa.yaml
  pkg/reconciler/brokercell/testingdata/util.go
  pkg/reconciler/testing/listers.go
Labels: approved, cla: yes, lgtm, size/XL

#1184 Use the new internal API group
  config/core/roles/addressable-resolvers-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1161 added or modified smoke test of four sources and gcp broker
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/build/build_test.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/intevents/reconciler.go
  pkg/reconciler/testing/auditlogs.go
  pkg/reconciler/testing/build.go
  pkg/reconciler/testing/pubsub.go
  pkg/reconciler/testing/pullsubscription.go
  pkg/reconciler/testing/scheduler.go
  pkg/reconciler/testing/storage.go
  test/e2e/e2e_test.go
  test/e2e/lib/auditlogs.go
  test/e2e/lib/creation.go
  test/e2e/lib/deletion.go
  test/e2e/lib/get.go
  test/e2e/lib/pubsub.go
  test/e2e/lib/resources/constants.go
  test/e2e/lib/resources/knative_gcp.go
  test/e2e/lib/scheduler.go
  test/e2e/lib/storage.go
  test/e2e/lib/subscription.go
  test/e2e/lib/topics.go
  test/e2e/test_auditlogs.go
  test/e2e/test_gcp_broker.go
  test/e2e/test_pubsub.go
  test/e2e/test_scheduler.go
  test/e2e/test_storage.go
Labels: approved, cla: yes, lgtm, size/XL

#1187 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/test/gcs/client.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/gcs/helpers.go
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1186 [master] golang format tools
  pkg/reconciler/testing/pullsubscription.go
  test/e2e/e2e_test.go
  test/e2e/lib/auditlogs.go
  test/e2e/lib/deletion.go
  test/e2e/lib/get.go
  test/e2e/lib/resources/constants.go
  test/e2e/lib/resources/knative_gcp.go
  test/e2e/lib/storage.go
  test/e2e/lib/subscription.go
  test/e2e/lib/topics.go
  test/e2e/test_auditlogs.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1132 Create brokercell on demand
  pkg/apis/broker/v1beta1/broker_lifecycle.go
  pkg/apis/broker/v1beta1/broker_lifecycle_test.go
  pkg/apis/broker/v1beta1/test_helper.go
  pkg/apis/intevents/v1alpha1/brokercell_types.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
  pkg/reconciler/broker/create_brokercell.go
  pkg/reconciler/broker/resources/brokercell.go
  pkg/reconciler/broker/resources/brokercell_test.go
  pkg/reconciler/brokercell/controller.go
  pkg/reconciler/testing/broker.go
Labels: approved, cla: yes, lgtm, size/L

#1170 Remove static GCP broker data plane yamls
  config/broker/200-rbac.yaml
  config/broker/400-broker-service.yaml
  config/broker/500-broker.yaml
  config/broker/500-hpa.yaml
  config/broker/deployments/broker.yaml
  config/broker/deployments/dummy.go
  config/broker/deployments/hpa.yaml
  config/broker/dummy.go
  config/broker/rbac/broker.yaml
  config/broker/rbac/dummy.go
  config/broker/services/broker.yaml
  config/broker/services/dummy.go
  config/core/roles/role.yaml
  config/core/roles/rolebinding.yaml
  config/core/serviceaccount.yaml
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/XL

#1189 Mark sub-status when GCP Broker is not ready
  pkg/reconciler/broker/broker.go
  pkg/reconciler/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/S

#1162 Garbage collect brokercell if no brokers are using it
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/brokercell/controller.go
  pkg/reconciler/brokercell/controller_test.go
  pkg/reconciler/testing/brokercell.go
Labels: approved, cla: yes, lgtm, size/L

#1188 Brokercell controller watches data plane components
  pkg/reconciler/brokercell/controller.go
  pkg/reconciler/brokercell/resources/args.go
Labels: approved, cla: yes, lgtm, size/M

#1199 Remove logging lines that are causing issues in tests
  pkg/reconciler/broker/broker.go
Labels: approved, cla: yes, lgtm, size/XS

#1179 Add broker ingress liveness probe
  pkg/broker/handler/processors/fanout/processor.go
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
  pkg/reconciler/brokercell/resources/deployments.go
  pkg/reconciler/brokercell/testingdata/ingress_deployment.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment_with_status.yaml
Labels: approved, cla: yes, lgtm, size/M

#1194 Note that GCP broker only works in GCP for now
  docs/install/install-gcp-broker.md
Labels: approved, cla: yes, lgtm, size/XS

#1200 Remove the brokers event_dispatch_latencies metric
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
  pkg/metrics/ingress_reporter.go
  pkg/metrics/ingress_reporter_test.go
Labels: approved, cla: yes, lgtm, size/M

#1172 Emit Trigger Stats in GCP Broker Fanout and Retry
  cmd/broker/fanout/main.go
  cmd/broker/fanout/wire.go
  cmd/broker/fanout/wire_gen.go
  cmd/broker/retry/main.go
  cmd/broker/retry/wire.go
  cmd/broker/retry/wire_gen.go
  pkg/broker/handler/handler.go
  pkg/broker/handler/pool/fanout.go
  pkg/broker/handler/pool/fanout_test.go
  pkg/broker/handler/pool/retry.go
  pkg/broker/handler/pool/retry_test.go
  pkg/broker/handler/pool/wire.go
  pkg/broker/handler/pool/wire_gen.go
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
  pkg/broker/handler/processors/fanout/processor.go
  pkg/metrics/delivery_reporter.go
  pkg/metrics/delivery_reporter_test.go
  pkg/metrics/testing/delivery.go
Labels: approved, cla: yes, lgtm, size/XL

#1198 added bucket exists check when reconcile and delete notification
  pkg/gclient/storage/bucket.go
  pkg/gclient/storage/interfaces.go
  pkg/gclient/storage/testing/bucket.go
  pkg/reconciler/events/storage/storage.go
  pkg/reconciler/events/storage/storage_test.go
Labels: approved, cla: yes, lgtm, size/L

#1202 [master] golang format tools
  pkg/apis/broker/v1beta1/broker_lifecycle.go
  pkg/apis/intevents/v1alpha1/brokercell_types.go
  pkg/gclient/storage/interfaces.go
  pkg/gclient/storage/testing/bucket.go
  pkg/metrics/ingress_reporter.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/resources/brokercell.go
  pkg/reconciler/broker/resources/brokercell_test.go
  pkg/reconciler/events/storage/storage.go
  pkg/reconciler/events/storage/storage_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1180 Add e2e troubleshooting tip
  docs/testing/troubleshooting-e2e.md
Labels: approved, cla: yes, lgtm, size/S

#1185 Add liveness probes for fanout and retry
  cmd/broker/fanout/main.go
  cmd/broker/retry/main.go
  pkg/broker/handler/pool/fanout.go
  pkg/broker/handler/pool/fanout_test.go
  pkg/broker/handler/pool/pool.go
  pkg/broker/handler/pool/pool_test.go
  pkg/broker/handler/pool/retry.go
  pkg/broker/handler/pool/retry_test.go
  pkg/reconciler/brokercell/resources/deployments.go
  pkg/reconciler/brokercell/testingdata/fanout_deployment.yaml
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_status.yaml
Labels: approved, cla: yes, lgtm, size/L

#1169 Update WI related docs after recent 0.15 release cut
  docs/examples/channel/README.md
  docs/examples/channel/channel.yaml
  docs/examples/cloudauditlogssource/README.md
  docs/examples/cloudauditlogssource/cloudauditlogssource.yaml
  docs/examples/cloudbuildsource/README.md
  docs/examples/cloudbuildsource/cloudbuildsource.yaml
  docs/examples/cloudpubsubsource/README.md
  docs/examples/cloudpubsubsource/cloudpubsubsource.yaml
  docs/examples/cloudschedulersource/README.md
  docs/examples/cloudschedulersource/cloudschedulersource.yaml
  docs/examples/cloudstoragesource/README.md
  docs/examples/cloudstoragesource/cloudstoragesource.yaml
  docs/examples/pullsubscription/README.md
  docs/examples/pullsubscription/pullsubscription.yaml
  docs/examples/topic/README.md
  docs/examples/topic/topic.yaml
  docs/install/authentication-mechanisms-gcp.md
  docs/install/install-gcp-broker.md
  docs/install/install-knative-gcp.md
  docs/install/pubsub-service-account.md
Labels: approved, cla: yes, lgtm, size/L

#1208 Pin to latest pubsub protocol to get bug fix
  go.mod
  go.sum
  pkg/broker/handler/handler.go
  pkg/broker/handler/handler_test.go
  pkg/broker/handler/pool/providers.go
  pkg/broker/handler/pool/testing/helper.go
  pkg/broker/handler/processors/deliver/processor_test.go
  pkg/broker/ingress/args.go
  pkg/broker/ingress/handler_test.go
  third_party/VENDOR-LICENSE/github.com/cloudevents/sdk-go/protocol/pubsub/v2/LICENSE
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/LICENSE
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/context/context.go
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/doc.go
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/go.mod
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/go.sum
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/internal/connection.go
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/message.go
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/options.go
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/protocol.go
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/write_pubsub_message.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1206 Use "trigger" prefix for fanout & retry metrics
  cmd/broker/fanout/main.go
  cmd/broker/ingress/main.go
  cmd/broker/retry/main.go
  pkg/observability/observability.go
  pkg/utils/mainhelper/init.go
  pkg/utils/mainhelper/options.go
  pkg/utils/mainhelper/options_test.go
Labels: approved, cla: yes, lgtm, size/M

#1219 Unpin and update go.opencensus.io to master
  go.mod
  go.sum
  vendor/go.opencensus.io/Gopkg.lock
  vendor/go.opencensus.io/Gopkg.toml
  vendor/go.opencensus.io/Makefile
  vendor/go.opencensus.io/README.md
  vendor/go.opencensus.io/appveyor.yml
  vendor/go.opencensus.io/go.mod
  vendor/go.opencensus.io/go.sum
  vendor/go.opencensus.io/plugin/ocgrpc/client.go
  vendor/go.opencensus.io/plugin/ocgrpc/server.go
  vendor/go.opencensus.io/plugin/ocgrpc/trace_common.go
  vendor/go.opencensus.io/plugin/ochttp/propagation/b3/b3.go
  vendor/go.opencensus.io/plugin/ochttp/server.go
  vendor/go.opencensus.io/plugin/ochttp/trace.go
  vendor/go.opencensus.io/stats/record.go
  vendor/go.opencensus.io/stats/units.go
  vendor/go.opencensus.io/stats/view/aggregation.go
  vendor/go.opencensus.io/stats/view/aggregation_data.go
  vendor/go.opencensus.io/stats/view/export.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/go.opencensus.io/stats/view/worker_commands.go
  vendor/go.opencensus.io/trace/lrumap.go
  vendor/go.opencensus.io/trace/trace.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1225 Use config-gcp-auth to default Channel auth.
  pkg/apis/messaging/v1alpha1/channel_defaults.go
  pkg/apis/messaging/v1alpha1/channel_defaults_test.go
  pkg/apis/messaging/v1alpha1/channel_validation_test.go
  pkg/apis/messaging/v1beta1/channel_defaults.go
  pkg/apis/messaging/v1beta1/channel_defaults_test.go
  pkg/apis/messaging/v1beta1/channel_validation_test.go
  pkg/reconciler/testing/channel.go
Labels: approved, cla: yes, lgtm, size/L

#1212 Drop non-event messages
  pkg/broker/handler/handler.go
  pkg/broker/handler/handler_test.go
Labels: approved, cla: yes, lgtm, size/M

#1224 wait 120 seconds for CAL
  test/e2e/lib/helpers/broker_event_transformation_test_with_source.go
  test/e2e/lib/resources/constants.go
  test/e2e/test_auditlogs.go
Labels: approved, cla: yes, lgtm, size/S

#1220 Provide the default GCP auth during the creation of the PullSubscription for E2E
  pkg/apis/events/v1alpha1/cloudpubsubsource_defaults_test.go
  pkg/apis/intevents/v1alpha1/pullsubscription_defaults_test.go
  pkg/reconciler/testing/auditlogs.go
  pkg/reconciler/testing/build.go
  pkg/reconciler/testing/pubsub.go
  pkg/reconciler/testing/pullsubscription.go
  pkg/reconciler/testing/scheduler.go
  pkg/reconciler/testing/storage.go
  pkg/reconciler/testing/topic.go
Labels: approved, cla: yes, lgtm, size/M

#1223 Add Stackdriver Tracing E2E Test
  test/e2e/e2e_test.go
  test/e2e/lib/helpers/broker_event_transformation_test_with_source.go
  test/e2e/lib/helpers/broker_tracing.go
  test/e2e/lib/resources/kube.go
  test/e2e/lib/types.go
  test/e2e/test_gcp_broker.go
  test/test_images/sender/main.go
  vendor/cloud.google.com/go/trace/apiv1/doc.go
  vendor/cloud.google.com/go/trace/apiv1/trace_client.go
  vendor/google.golang.org/genproto/googleapis/devtools/cloudtrace/v1/trace.pb.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1228 [master] Format markdown
  docs/examples/channel/README.md
  docs/examples/cloudauditlogssource/README.md
  docs/examples/cloudbuildsource/README.md
  docs/examples/cloudpubsubsource/README.md
  docs/examples/cloudschedulersource/README.md
  docs/examples/cloudstoragesource/README.md
  docs/examples/pullsubscription/README.md
  docs/examples/topic/README.md
  docs/install/authentication-mechanisms-gcp.md
  docs/install/install-gcp-broker.md
  docs/install/install-knative-gcp.md
  docs/install/pubsub-service-account.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1229 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1226 Avoid creating publishers when creating Topics from Sources
  pkg/apis/intevents/v1alpha1/pullsubscription_conversion_test.go
  pkg/apis/intevents/v1alpha1/topic_conversion.go
  pkg/apis/intevents/v1alpha1/topic_conversion_test.go
  pkg/apis/intevents/v1alpha1/topic_defaults.go
  pkg/apis/intevents/v1alpha1/topic_defaults_test.go
  pkg/apis/intevents/v1alpha1/topic_lifecycle.go
  pkg/apis/intevents/v1alpha1/topic_lifecycle_test.go
  pkg/apis/intevents/v1alpha1/topic_types.go
  pkg/apis/intevents/v1alpha1/topic_types_test.go
  pkg/apis/intevents/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/intevents/v1beta1/topic_defaults.go
  pkg/apis/intevents/v1beta1/topic_defaults_test.go
  pkg/apis/intevents/v1beta1/topic_lifecycle.go
  pkg/apis/intevents/v1beta1/topic_lifecycle_test.go
  pkg/apis/intevents/v1beta1/topic_types.go
  pkg/apis/intevents/v1beta1/topic_types_test.go
  pkg/apis/intevents/v1beta1/zz_generated.deepcopy.go
  pkg/broker/handler/handler.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/intevents/reconciler.go
  pkg/reconciler/intevents/reconciler_test.go
  pkg/reconciler/intevents/resources/topic.go
  pkg/reconciler/intevents/topic/topic.go
  pkg/reconciler/intevents/topic/topic_test.go
  pkg/reconciler/testing/topic.go
Labels: approved, cla: yes, lgtm, size/L

#1214 Update default credential and rename method
  cmd/broker/ingress/main.go
  pkg/apis/duck/v1alpha1/pubsub_defaults.go
  pkg/apis/duck/v1alpha1/pubsub_defaults_test.go
  pkg/apis/duck/v1beta1/pubsub_defaults.go
  pkg/apis/duck/v1beta1/pubsub_defaults_test.go
  pkg/apis/intevents/v1alpha1/topic_defaults.go
  pkg/apis/intevents/v1alpha1/topic_defaults_test.go
  pkg/apis/intevents/v1beta1/topic_defaults.go
  pkg/apis/intevents/v1beta1/topic_defaults_test.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/build/build_test.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/events/scheduler/resources/names_test.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/intevents/pullsubscription/resources/receive_adapter_test.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription_test.go
  pkg/reconciler/intevents/reconciler_test.go
  pkg/reconciler/testing/auditlogs.go
  pkg/reconciler/testing/build.go
  pkg/reconciler/testing/pubsub.go
  pkg/reconciler/testing/pullsubscription.go
  pkg/reconciler/testing/scheduler.go
  pkg/reconciler/testing/storage.go
  pkg/reconciler/testing/topic.go
  pkg/utils/naming/names_test.go
Labels: approved, cla: yes, lgtm, size/L

#1230 Mark conditions for broker and trigger
  pkg/apis/broker/v1beta1/broker_lifecycle.go
  pkg/apis/broker/v1beta1/broker_lifecycle_test.go
  pkg/apis/broker/v1beta1/test_helper.go
  pkg/apis/broker/v1beta1/trigger_lifecycle.go
  pkg/apis/broker/v1beta1/trigger_lifecycle_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/create_brokercell.go
  pkg/reconciler/testing/broker.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#1231 modified troubleshooting docs
  docs/testing/troubleshooting-e2e.md
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, size/M

#1213 Update gcp broker example docs
  docs/examples/gcpbroker/README.md
Labels: approved, cla: yes, lgtm, size/S

#1236 [master] Format markdown
  docs/install/pubsub-service-account.md
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1243 pin eventing to 0603 nightly
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/XS

#1240 Adding missing publisher in yaml
  config/core/resources/topic.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1242 increased the WaitDeletionTime to 40 seconds
  test/e2e/lib/resources/constants.go
  test/e2e/test_auditlogs.go
  test/e2e/test_gcp_broker.go
  test/e2e/test_pubsub.go
  test/e2e/test_scheduler.go
  test/e2e/test_storage.go
Labels: approved, cla: yes, lgtm, size/S

#1244 Update WI E2E test to use config-gcp-auth and serviceAccountName
  pkg/reconciler/testing/auditlogs.go
  pkg/reconciler/testing/channel.go
  pkg/reconciler/testing/pubsub.go
  pkg/reconciler/testing/scheduler.go
  pkg/reconciler/testing/storage.go
  test/e2e-wi-tests.sh
  test/e2e/lib/auditlogs.go
  test/e2e/lib/helpers/broker_event_transformation_test_with_source.go
  test/e2e/lib/pubsub.go
  test/e2e/lib/scheduler.go
  test/e2e/lib/storage.go
  test/e2e/lib/types.go
  test/e2e/main_test.go
  test/e2e/test_auditlogs.go
  test/e2e/test_channel.go
  test/e2e/test_pubsub.go
  test/e2e/test_pullsubscription.go
  test/e2e/test_scheduler.go
  test/e2e/test_storage.go
  test/e2e_flags.go
  test/test_configs/config-gcp-auth-wi.yaml
Labels: approved, cla: yes, lgtm, size/L

#1218 Add client side backoff retries for pubsub messages
  cmd/broker/fanout/main.go
  cmd/broker/fanout/wire.go
  cmd/broker/fanout/wire_gen.go
  cmd/broker/retry/main.go
  cmd/broker/retry/wire.go
  cmd/broker/retry/wire_gen.go
  pkg/broker/handler/fanout.go
  pkg/broker/handler/fanout_test.go
  pkg/broker/handler/handler.go
  pkg/broker/handler/handler_test.go
  pkg/broker/handler/options.go
  pkg/broker/handler/options_test.go
  pkg/broker/handler/pool.go
  pkg/broker/handler/pool_test.go
  pkg/broker/handler/providers.go
  pkg/broker/handler/retry.go
  pkg/broker/handler/retry_test.go
  pkg/broker/handler/testing/helper.go
  pkg/broker/handler/wire.go
  pkg/broker/handler/wire_gen.go
  pkg/reconciler/brokercell/resources/deployments.go
Labels: approved, cla: yes, lgtm, size/L

#1246 [master] Fix spelling errors
  pkg/broker/handler/handler.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1249 Remove spec.googleServiceAccount in v1alpha1
  config/core/resources/channel.yaml
  config/core/resources/cloudauditlogssource.yaml
  config/core/resources/cloudbuildsource.yaml
  config/core/resources/cloudpubsubsource.yaml
  config/core/resources/cloudschedulersource.yaml
  config/core/resources/cloudstoragesource.yaml
  config/core/resources/pullsubscription.yaml
  config/core/resources/topic.yaml
  pkg/apis/duck/v1alpha1/credentials.go
  pkg/apis/duck/v1alpha1/credentials_test.go
  pkg/apis/duck/v1alpha1/identity_types.go
  pkg/apis/events/v1alpha1/cloudauditlogssource_validation.go
  pkg/apis/events/v1alpha1/cloudbuildsource_validation.go
  pkg/apis/events/v1alpha1/cloudbuildsource_validation_test.go
  pkg/apis/events/v1alpha1/cloudpubsubsource_types_test.go
  pkg/apis/events/v1alpha1/cloudpubsubsource_validation.go
  pkg/apis/events/v1alpha1/cloudpubsubsource_validation_test.go
  pkg/apis/events/v1alpha1/cloudschedulersource_types_test.go
  pkg/apis/events/v1alpha1/cloudschedulersource_validation.go
  pkg/apis/events/v1alpha1/cloudschedulersource_validation_test.go
  pkg/apis/events/v1alpha1/cloudstoragesource_types_test.go
  pkg/apis/events/v1alpha1/cloudstoragesource_validation.go
  pkg/apis/events/v1alpha1/cloudstoragesource_validation_test.go
  pkg/apis/messaging/v1alpha1/channel_types_test.go
  pkg/apis/messaging/v1alpha1/channel_validation.go
  pkg/apis/messaging/v1alpha1/channel_validation_test.go
  pkg/reconciler/events/auditlogs/auditlogs.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/build/build.go
  pkg/reconciler/events/build/build_test.go
  pkg/reconciler/events/pubsub/pubsub.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/events/scheduler/scheduler.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/identity/reconciler.go
  pkg/reconciler/identity/reconciler_test.go
  pkg/reconciler/identity/resources/service_account.go
  pkg/reconciler/identity/resources/service_account_test.go
  pkg/reconciler/intevents/pullsubscription/reconciler.go
  pkg/reconciler/intevents/pullsubscription/resources/receive_adapter.go
  pkg/reconciler/intevents/pullsubscription/resources/receive_adapter_test.go
  pkg/reconciler/intevents/resources/pullsubscription.go
  pkg/reconciler/intevents/resources/topic.go
  pkg/reconciler/intevents/topic/resources/publisher.go
  pkg/reconciler/intevents/topic/resources/publisher_test.go
  pkg/reconciler/intevents/topic/topic.go
  pkg/reconciler/messaging/channel/channel.go
  pkg/reconciler/messaging/channel/channel_test.go
  pkg/reconciler/messaging/channel/resources/pullsubscription.go
  pkg/reconciler/messaging/channel/resources/topic.go
  pkg/reconciler/testing/auditlogs.go
  pkg/reconciler/testing/build.go
  pkg/reconciler/testing/channel.go
  pkg/reconciler/testing/pubsub.go
  pkg/reconciler/testing/scheduler.go
  pkg/reconciler/testing/storage.go
Labels: approved, cla: yes, lgtm, size/XL

#1241 Use wire to inject the IAMPolicyManager and gcpauth.Store.
  cmd/controller/main.go
  cmd/controller/wire.go
  cmd/controller/wire_gen.go
  pkg/apis/configs/gcpauth/singleton.go
  pkg/reconciler/events/auditlogs/controller.go
  pkg/reconciler/events/auditlogs/controller_test.go
  pkg/reconciler/events/build/controller.go
  pkg/reconciler/events/build/controller_test.go
  pkg/reconciler/events/pubsub/controller.go
  pkg/reconciler/events/pubsub/controller_test.go
  pkg/reconciler/events/scheduler/controller.go
  pkg/reconciler/events/scheduler/controller_test.go
  pkg/reconciler/events/storage/controller.go
  pkg/reconciler/events/storage/controller_test.go
  pkg/reconciler/identity/iam/iam_policy.go
  pkg/reconciler/intevents/pullsubscription/keda/controller.go
  pkg/reconciler/intevents/pullsubscription/keda/controller_test.go
  pkg/reconciler/intevents/pullsubscription/static/controller.go
  pkg/reconciler/intevents/pullsubscription/static/controller_test.go
  pkg/reconciler/intevents/topic/controller.go
  pkg/reconciler/intevents/topic/controller_test.go
  pkg/reconciler/messaging/channel/controller.go
  pkg/reconciler/messaging/channel/controller_test.go
Labels: approved, cla: yes, lgtm, size/L

#1256 Run Delivery Benchmarks with Multiple Payload Sizes
  pkg/broker/handler/processors/deliver/processor_test.go
Labels: approved, cla: yes, lgtm, size/M

#1266 Set pubsub status to true when resources already exist
  pkg/reconciler/utils/pubsub/subscription.go
  pkg/reconciler/utils/pubsub/subscription_test.go
  pkg/reconciler/utils/pubsub/testing/status_updater.go
  pkg/reconciler/utils/pubsub/topic.go
  pkg/reconciler/utils/pubsub/topic_test.go
Labels: approved, cla: yes, lgtm, size/L

#1260 Add example hashes to ConfigMaps.
  config/core/configmaps/gcp-auth.yaml
  config/core/configmaps/leader-election.yaml
  config/core/configmaps/logging.yaml
  config/core/configmaps/observability.yaml
  config/core/configmaps/tracing.yaml
  go.sum
  hack/tools.go
  hack/update-codegen.sh
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/README.md
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
  vendor/knative.dev/pkg/configmap/hash-gen/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1270 Unpin contrib.go.opencensus.io/exporter/stackdriver
  go.mod
  go.sum
  vendor/contrib.go.opencensus.io/exporter/stackdriver/go.mod
  vendor/contrib.go.opencensus.io/exporter/stackdriver/go.sum
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/aws/aws_identity_doc_utils.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/aws/monitored_resources.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/deprecated.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/gcp/gcp_metadata_config.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/gcp/monitored_resources.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/monitored_resources.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/resource.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stackdriver.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/trace.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1271 Add warning and trace event when an event is dropped to hop limit
  pkg/broker/handler/processors/deliver/processor.go
Labels: approved, cla: yes, lgtm, size/S

#1268 Recreate subscription if topic has been deleted
  pkg/reconciler/utils/pubsub/subscription.go
  pkg/reconciler/utils/pubsub/subscription_test.go
  pkg/reconciler/utils/pubsub/topic_test.go
Labels: approved, cla: yes, lgtm, size/M

#1263 Update e2e test README
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, size/S

#1276 [master] Format markdown
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1269 Tune broker components
  pkg/broker/handler/providers.go
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/resources/deployments.go
  pkg/reconciler/brokercell/testingdata/fanout_deployment.yaml
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/fanout_hpa.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/ingress_hpa.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/retry_hpa.yaml
Labels: approved, cla: yes, lgtm, size/M

#1273 Run ingress handler benchmark with multiple event payload sizes
  pkg/broker/handler/processors/deliver/processor_test.go
  pkg/broker/ingress/handler_test.go
  pkg/testing/event.go
Labels: approved, cla: yes, lgtm, size/M

#1272 Have broker ingress reject events when the broker under requesting is not ready
  pkg/broker/ingress/errors.go
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
  pkg/broker/ingress/multi_topic_decouple_sink.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
Labels: approved, cla: yes, lgtm, size/M

#1278 Use pubsub bindings in broker ingress
  cmd/broker/ingress/wire_gen.go
  go.mod
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
  pkg/broker/ingress/multi_topic_decouple_sink.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1248 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/parallel_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/sequence_test_helper.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/performance/infra/receiver/receiver.go
  vendor/knative.dev/pkg/configmap/hash-gen/main.go
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/ghutil/repo.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1277 Update authentication mechanism related docs
  docs/install/authentication-mechanisms-gcp.md
  docs/install/install-gcp-broker.md
  docs/install/install-knative-gcp.md
  docs/install/pubsub-service-account.md
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, size/L

#1283 fixed the PullSubscriptions do not recover from Topic deletion
  docs/examples/channel/subscription.yaml
  pkg/gclient/pubsub/interfaces.go
  pkg/gclient/pubsub/testing/topic.go
  pkg/gclient/pubsub/topic.go
  pkg/reconciler/intevents/pullsubscription/reconciler.go
Labels: approved, cla: yes, lgtm, size/M

#1282 Increase the time out for metrics assertions in an attempt to deflake…
  test/e2e/lib/metrics/stackdriver.go
Labels: approved, cla: yes, lgtm, size/XS

#1289 [master] Format markdown
  docs/install/authentication-mechanisms-gcp.md
  docs/install/install-knative-gcp.md
  docs/install/pubsub-service-account.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1286 Propagate RA deployment availability
  pkg/apis/intevents/v1alpha1/pullsubscription_lifecycle.go
  pkg/apis/intevents/v1alpha1/pullsubscription_lifecycle_test.go
  pkg/apis/intevents/v1beta1/pullsubscription_lifecycle.go
  pkg/apis/intevents/v1beta1/pullsubscription_lifecycle_test.go
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription.go
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/intevents/pullsubscription/reconciler.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription_test.go
  pkg/reconciler/testing/deployment.go
  pkg/reconciler/testing/pullsubscription.go
Labels: approved, cla: yes, lgtm, size/L

#1293 Update a command in e2e doc
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1281 Add troubleshooting to authentication-mechanisms doc
  docs/install/authentication-mechanisms-gcp.md
  docs/install/pubsub-service-account.md
  pkg/gclient/pubsub/testing/topic.go
Labels: approved, cla: yes, lgtm, size/L

#1297 Upgrade go.opencensus.io to v0.22.4
  go.mod
  go.sum
  vendor/go.opencensus.io/stats/view/view_to_metric.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/go.opencensus.io/stats/view/worker_commands.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1301 Disable custom metrics in GCPBrokerMetricsTest()
  test/e2e/lib/lifecycle.go
Labels: approved, cla: yes, lgtm, size/XS

#1295 Mark condition in broker/trigger finalizer when the deletion failed
  pkg/reconciler/broker/broker.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/utils/pubsub/subscription.go
  pkg/reconciler/utils/pubsub/subscription_test.go
  pkg/reconciler/utils/pubsub/topic.go
  pkg/reconciler/utils/pubsub/topic_test.go
Labels: approved, cla: yes, lgtm, size/M

#1299 Remove old test images and update deps
  config/core/configmaps/gcp-auth.yaml
  config/core/configmaps/leader-election.yaml
  config/core/configmaps/logging.yaml
  config/core/configmaps/observability.yaml
  config/core/configmaps/tracing.yaml
  go.mod
  go.sum
  hack/tools.go
  test/e2e/e2e_test.go
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_header_single_event_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/performance_image_test_helper.go
  vendor/knative.dev/eventing/test/lib/cloudevents.go
  vendor/knative.dev/eventing/test/lib/cloudevents/cloud_events.go
  vendor/knative.dev/eventing/test/lib/config.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go
  vendor/knative.dev/eventing/test/lib/resources/kube.go
  vendor/knative.dev/eventing/test/lib/resources/sender/sender.go
  vendor/knative.dev/eventing/test/lib/send_event.go
  vendor/knative.dev/eventing/test/lib/validation.go
  vendor/knative.dev/eventing/test/test_images/event-sender/main.go
  vendor/knative.dev/eventing/test/test_images/logevents/main.go
  vendor/knative.dev/eventing/test/test_images/logevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/sendevents/main.go
  vendor/knative.dev/eventing/test/test_images/sendevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/hack/tools.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/metrics/testing.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1302 Set Stackdriver as default metrics backend
  config/core/configmaps/observability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1290 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1305 Go fmt
  pkg/apis/duck/v1beta1/annotations.go
  pkg/apis/events/register.go
  pkg/apis/events/v1alpha1/cloudbuildsource_conversion.go
  pkg/apis/events/v1alpha1/cloudbuildsource_conversion_test.go
  pkg/apis/events/v1alpha1/cloudbuildsource_types.go
  pkg/apis/events/v1beta1/cloudbuildsource_conversion.go
  pkg/apis/events/v1beta1/cloudbuildsource_defaults_test.go
  pkg/apis/events/v1beta1/cloudbuildsource_types.go
  pkg/apis/events/v1beta1/cloudbuildsource_validation.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/build/build.go
  pkg/reconciler/events/build/build_test.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/events/scheduler/scheduler.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/intevents/pullsubscription/keda/resources/scaled_object_test.go
  pkg/reconciler/intevents/pullsubscription/resources/names.go
  pkg/reconciler/intevents/pullsubscription/resources/receive_adapter.go
  pkg/reconciler/intevents/pullsubscription/resources/receive_adapter_test.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription_test.go
  pkg/reconciler/intevents/reconciler_test.go
  pkg/reconciler/messaging/channel/channel.go
  pkg/reconciler/messaging/channel/channel_test.go
  pkg/reconciler/testing/topic.go
  test/e2e/lib/helpers/broker_tracing.go
Labels: approved, cla: yes, lgtm, size/M

#1304 Fix test race by saving the loop variable
  pkg/broker/handler/processors/deliver/processor_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1310 Change back storage version
  config/core/resources/cloudauditlogssource.yaml
  config/core/resources/cloudbuildsource.yaml
  config/core/resources/cloudpubsubsource.yaml
  config/core/resources/cloudschedulersource.yaml
  config/core/resources/cloudstoragesource.yaml
  config/core/resources/pullsubscription.yaml
  config/core/resources/topic.yaml
Labels: approved, cla: yes, lgtm, size/S

#1312 Registering v1beta1 types
  cmd/webhook/main.go
  config/core/resources/cloudauditlogssource.yaml
  config/core/resources/cloudbuildsource.yaml
  config/core/resources/cloudpubsubsource.yaml
  config/core/resources/cloudschedulersource.yaml
  config/core/resources/cloudstoragesource.yaml
  config/core/resources/pullsubscription.yaml
  config/core/resources/topic.yaml
Labels: approved, cla: yes, lgtm, size/M

#1298 Use CloudEvents 1.0 in docs
  docs/examples/gcpbroker/README.md
  docs/spec/pubsub-protocol-binding.md
Labels: approved, cla: yes, lgtm, size/S

#1309 Fail TestGCPBrokerMetrics test immediately if event cannot be sent
  test/e2e/lib/helpers/broker_event_transformation_test_with_source.go
Labels: approved, cla: yes, lgtm, size/XS

#1313 [master] Format markdown
  docs/install/authentication-mechanisms-gcp.md
  docs/install/pubsub-service-account.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1280 Reconcile targets config in brokercell
  go.mod
  pkg/apis/broker/v1beta1/broker_lifecycle.go
  pkg/apis/broker/v1beta1/broker_lifecycle_test.go
  pkg/apis/broker/v1beta1/test_helper.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_targets_test.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
  pkg/reconciler/broker/create_brokercell.go
  pkg/reconciler/broker/resources/brokercell.go
  pkg/reconciler/broker/resources/brokercell_test.go
  pkg/reconciler/broker/resources/deployments.go
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/brokercell/controller.go
  pkg/reconciler/brokercell/controller_test.go
  pkg/reconciler/brokercell/resources/args.go
  pkg/reconciler/brokercell/resources/configmap.go
  pkg/reconciler/brokercell/resources/deployments.go
  pkg/reconciler/brokercell/testingdata/configmap.go
  pkg/reconciler/brokercell/testingdata/fanout_deployment.yaml
  pkg/reconciler/brokercell/testingdata/fanout_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment_with_status.yaml
  pkg/reconciler/brokercell/testingdata/read_yaml.go
  pkg/reconciler/brokercell/testingdata/retry_deployment.yaml
  pkg/reconciler/brokercell/testingdata/retry_deployment_with_status.yaml
  pkg/reconciler/helper.go
  pkg/reconciler/helper_test.go
  pkg/reconciler/testing/broker.go
  pkg/reconciler/trigger/trigger_test.go
  pkg/reconciler/utils/volume/pod_annotation.go
  pkg/reconciler/utils/volume/pod_annotation_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1320 Refactor set default when creating resources for test
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/build/build_test.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/identity/reconciler_test.go
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/intevents/pullsubscription/keda/resources/scaled_object_test.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription_test.go
  pkg/reconciler/intevents/reconciler_test.go
  pkg/reconciler/intevents/topic/topic_test.go
  pkg/reconciler/messaging/channel/channel_test.go
  pkg/reconciler/testing/auditlogs.go
  pkg/reconciler/testing/broker.go
  pkg/reconciler/testing/brokercell.go
  pkg/reconciler/testing/build.go
  pkg/reconciler/testing/channel.go
  pkg/reconciler/testing/pubsub.go
  pkg/reconciler/testing/pullsubscription.go
  pkg/reconciler/testing/scheduler.go
  pkg/reconciler/testing/storage.go
  pkg/reconciler/testing/topic.go
  pkg/reconciler/testing/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1325 Add the events.cloud.google.com/initialized annotation.
  config/core/configmaps/gcp-auth.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1328 Unpin github.com/gogo/protobuf
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/encode.go
  vendor/github.com/gogo/protobuf/proto/properties.go
  vendor/github.com/gogo/protobuf/proto/table_marshal.go
  vendor/github.com/gogo/protobuf/proto/text.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1323 [master] golang format tools
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/controller.go
  pkg/reconciler/brokercell/resources/configmap.go
  pkg/reconciler/brokercell/testingdata/configmap.go
  pkg/reconciler/helper_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1330 Change view.Register to RegisterResourceView
  pkg/metrics/delivery_reporter.go
  pkg/metrics/ingress_reporter.go
  pkg/pubsub/adapter/stats_reporter.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1322 Add broker ingress readiness prober
  pkg/reconciler/brokercell/resources/deployments.go
  pkg/reconciler/brokercell/testingdata/ingress_deployment.yaml
  pkg/reconciler/brokercell/testingdata/ingress_deployment_with_status.yaml
Labels: approved, cla: yes, lgtm, size/M

#1334 Add Trigger and Filter Trace Events
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/filter/processor.go
Labels: approved, cla: yes, lgtm, size/S

#1339 differentiate between unknown, true and false when propagate deployme…
  pkg/apis/intevents/v1alpha1/brokercell_lifecycle.go
  pkg/apis/intevents/v1alpha1/brokercell_lifecycle_test.go
  pkg/apis/intevents/v1alpha1/pullsubscription_lifecycle.go
  pkg/apis/intevents/v1alpha1/pullsubscription_lifecycle_test.go
  pkg/apis/intevents/v1alpha1/test_helper.go
  pkg/apis/intevents/v1beta1/pullsubscription_lifecycle.go
  pkg/apis/intevents/v1beta1/pullsubscription_lifecycle_test.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/testing/brokercell.go
Labels: approved, cla: yes, lgtm, size/L

#1284 Verify broker retry metrics in e2e test
  test/e2e/lib/helpers/broker_event_transformation_test_with_source.go
  test/e2e/lib/resources/unstructured.go
  test/e2e/lib/trigger.go
  test/test_images/receiver/main.go
Labels: approved, cla: yes, lgtm, size/L

#1350 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/test_helper.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_crd_metadata_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/source_crd_metadata_test_helper.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/test_images/event-sender/main.go
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/benchmark.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1341 Fix the brokerCell UT to test broker targets config
  pkg/reconciler/brokercell/brokercell_test.go
Labels: approved, cla: yes, lgtm, size/L

#1347 Deleting storage bucket upon test teardown
  test/e2e/lib/helpers/broker_event_transformation_test_with_source.go
  test/e2e/lib/storage.go
  test/e2e/test_storage.go
Labels: approved, cla: yes, lgtm, size/M

#1327 set resource and requests limits for pulllsubscription receiver adapter
  pkg/reconciler/intevents/pullsubscription/resources/receive_adapter.go
  pkg/reconciler/intevents/pullsubscription/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/M

#1345 Adding UTs to new receive adapter
  pkg/pubsub/adapter/adapter.go
  pkg/pubsub/adapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1354 Update docs/examples API version to v1beta1
  docs/examples/channel/channel.yaml
  docs/examples/channel/source.yaml
  docs/examples/channel/subscription.yaml
  docs/examples/cloudauditlogssource/cloudauditlogssource.yaml
  docs/examples/cloudpubsubsource/cloudpubsubsource.yaml
  docs/examples/cloudschedulersource/README.md
  docs/examples/cloudstoragesource/README.md
  docs/examples/cloudstoragesource/cloudstoragesource.yaml
  docs/examples/keda/cloudpubsubsource-keda.yaml
  docs/examples/pullsubscription/README.md
  docs/examples/pullsubscription/pullsubscription.yaml
  docs/examples/topic/topic.yaml
  docs/install/config-br-default-channel.yaml
  docs/install/patch-default-ch-config-with-pubsub.yaml
Labels: approved, cla: yes, lgtm, size/M

#1352 Limit the values of event_type in Broker metrics
  pkg/broker/ingress/handler_test.go
  pkg/metrics/ingress_reporter.go
  pkg/metrics/ingress_reporter_test.go
  pkg/metrics/tags.go
  pkg/metrics/tags_test.go
Labels: approved, cla: yes, lgtm, size/L

#1342 Emit trace event on ingress when broker is unavailable
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/multi_topic_decouple_sink.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
Labels: approved, cla: yes, lgtm, size/M

#1348 [master] Fix spelling errors
  pkg/pubsub/adapter/converters/storage_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1361 The trigger should be tracking its dependencies, not the broker
  pkg/reconciler/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/XS

#1359 [master] golang format tools
  pkg/apis/intevents/v1alpha1/brokercell_lifecycle_test.go
  pkg/apis/intevents/v1alpha1/brokercell_types_test.go
  pkg/apis/intevents/v1alpha1/pullsubscription_lifecycle_test.go
  pkg/apis/intevents/v1beta1/pullsubscription_types.go
  pkg/metrics/tags.go
  pkg/pubsub/adapter/converters/build.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/intevents/controller.go
  pkg/reconciler/intevents/reconciler.go
  pkg/reconciler/testing/brokercell.go
  pkg/reconciler/testing/channel.go
  pkg/reconciler/trigger/trigger_test.go
  pkg/tracing/attributes.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1363 Updating the doc on the GCP Broker deployment
  docs/install/install-gcp-broker.md
Labels: approved, cla: yes, lgtm, size/S

#1365 Update docs with new event attributes (type, source, etc.)
  docs/examples/cloudauditlogssource/README.md
  docs/examples/cloudpubsubsource/README.md
  docs/examples/cloudschedulersource/README.md
  docs/examples/cloudschedulersource/cloudschedulersource.yaml
  docs/examples/cloudstoragesource/README.md
  docs/examples/keda/README.md
  docs/examples/pullsubscription/README.md
Labels: approved, cla: yes, lgtm, size/L
