Repository google/knative-gcp, pull requests merged in 2020-02, with the labels that each got.

#531 fixed init data plane script
  hack/init_data_plane.sh
Labels: approved, lgtm, size/XS

#533 Address CAL Source e2e test flakiness
  test/e2e/test_auditlogs.go
Labels: approved, lgtm, size/XS

#535 Adding documentation for Topic
  README.md
  docs/README.md
  docs/examples/channel/README.md
  docs/examples/cloudauditlogssource/README.md
  docs/examples/cloudpubsubsource/README.md
  docs/examples/cloudschedulersource/README.md
  docs/examples/cloudstoragesource/README.md
  docs/examples/pullsubscription/README.md
  docs/examples/topic/README.md
  docs/examples/topic/curl.yaml
  docs/examples/topic/topic.yaml
  docs/install/install-broker-with-pubsub-channel.md
  docs/install/install-knative-gcp.md
Labels: approved, lgtm, size/L

#537 adding CheckImmutableFields for CloudStorageSource
  pkg/apis/events/v1alpha1/cloudstoragesource_validation.go
  pkg/apis/events/v1alpha1/cloudstoragesource_validation_test.go
Labels: approved, lgtm, size/L

#538 adding CheckImmutableFields for CloudSchedulerSource
  pkg/apis/events/v1alpha1/cloudschedulersource_validation.go
  pkg/apis/events/v1alpha1/cloudschedulersource_validation_test.go
Labels: approved, lgtm, size/L

#539 Updating dependencies
  Gopkg.lock
  test/e2e/test_auditlogs.go
  test/e2e/test_broker_pubsub.go
  test/e2e/test_channel.go
  test/e2e/test_pubsub.go
  test/e2e/test_pullsubscription.go
  test/e2e/test_scheduler.go
  test/e2e/test_storage.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/tracing/traceparent.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_header_single_event_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_dls_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/eventing/test/lib/validation.go
  vendor/knative.dev/eventing/test/test_images/logevents/kodata/LICENSE
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeclient.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeduck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakefactory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeinformer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/namesystems.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
Labels: approved, lgtm, size/XXL

#543 Clean up resources for PubSub before running the tests
  test/e2e-common.sh
Labels: approved, lgtm, size/S

#542 Add labels for topics and pullsubscription
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/pubsub/pubsub.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/pubsub/reconciler_test.go
  pkg/reconciler/pubsub/resources/labels.go
  pkg/reconciler/pubsub/resources/labels_test.go
  pkg/reconciler/pubsub/resources/pullsubscription.go
  pkg/reconciler/pubsub/resources/pullsubscription_test.go
  pkg/reconciler/pubsub/resources/topic.go
  pkg/reconciler/pubsub/resources/topic_test.go
Labels: approved, lgtm, size/L

#549 fixed propagate publisher status and fixed the pubsubsecret
  pkg/apis/events/v1alpha1/cloudschedulersource_validation.go
  pkg/apis/events/v1alpha1/cloudstoragesource_validation.go
  pkg/apis/messaging/v1alpha1/channel_lifecycle_test.go
  pkg/apis/pubsub/v1alpha1/topic_lifecycle.go
  pkg/apis/pubsub/v1alpha1/topic_lifecycle_test.go
  pkg/reconciler/messaging/channel/channel_test.go
  pkg/reconciler/pubsub/resources/pullsubscription.go
  pkg/reconciler/pubsub/resources/topic.go
  pkg/reconciler/pubsub/topic/topic.go
  pkg/reconciler/pubsub/topic/topic_test.go
  pkg/reconciler/testing/topic.go
Labels: approved, lgtm, size/XL

#552 fixed secret, pubsub and publisher
  Gopkg.lock
  cmd/controller/main.go
  config/201-clusterrole.yaml
  config/300-cloudauditlogssource.yaml
  pkg/apis/duck/v1alpha1/google_cloud_secret_defaults.go
  pkg/apis/events/v1alpha1/cloudschedulersource_validation.go
  pkg/apis/events/v1alpha1/cloudstoragesource_validation.go
  pkg/apis/messaging/v1alpha1/channel_lifecycle_test.go
  pkg/apis/pubsub/v1alpha1/topic_lifecycle.go
  pkg/apis/pubsub/v1alpha1/topic_lifecycle_test.go
  pkg/reconciler/deployment/controller.go
  pkg/reconciler/deployment/controller_test.go
  pkg/reconciler/deployment/deployment.go
  pkg/reconciler/deployment/deployment_test.go
  pkg/reconciler/messaging/channel/channel_test.go
  pkg/reconciler/pubsub/resources/pullsubscription.go
  pkg/reconciler/pubsub/resources/topic.go
  pkg/reconciler/pubsub/topic/topic.go
  pkg/reconciler/pubsub/topic/topic_test.go
  pkg/reconciler/testing/topic.go
Labels: approved, lgtm, size/XL

#553 Updating dependencies
  Gopkg.lock
  third_party/VENDOR-LICENSE
  vendor/gomodules.xyz/jsonpatch/LICENSE
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_conversion.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1alpha1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1alpha1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/in_memory_channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1alpha1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_types.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/channel.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/reconciler/configstore.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/autoscaler/config/testdata/config-autoscaler.yaml
  vendor/knative.dev/serving/pkg/network/network.go
Labels: approved, lgtm, size/XXL

#547 controller should watch for changes on its secret
  Gopkg.lock
  cmd/controller/main.go
  config/201-clusterrole.yaml
  pkg/apis/duck/v1alpha1/google_cloud_secret_defaults.go
  pkg/reconciler/deployment/controller.go
  pkg/reconciler/deployment/controller_test.go
  pkg/reconciler/deployment/deployment.go
  pkg/reconciler/deployment/deployment_test.go
Labels: approved, lgtm, size/L

#554 Stop decoding json from pubsub
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/pubsub_test.go
Labels: approved, lgtm, ok-to-test, size/S

#555 Do not base64 decode PubSub messages
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/pubsub_test.go
Labels: approved, lgtm, size/S

#550 adding e2e test PubSubSource->Broker with PubSubChannel
  test/e2e/e2e_test.go
  test/e2e/lib/pubsub.go
  test/e2e/test_broker_pubsub.go
  test/e2e/test_pubsub.go
Labels: approved, lgtm, size/L

#559 Update PR template with more instructions
  .github/pull-request-template.md
Labels: approved, lgtm, size/M

#562 add e2e test for Storage>Broker with PubSub Channel
  test/e2e/e2e_test.go
  test/e2e/lib/storage.go
  test/e2e/test_broker_pubsub.go
  test/e2e/test_storage.go
Labels: approved, lgtm, size/L

#561 add e2e test for AuditLogs>Broker with PubSub Channel
  test/e2e/e2e_test.go
  test/e2e/lib/auditlogs.go
  test/e2e/lib/pubsub.go
  test/e2e/test_auditlogs.go
  test/e2e/test_broker_pubsub.go
  test/e2e/test_pubsub.go
Labels: approved, lgtm, size/L

#564 add e2e test for Scheduler>Broker with PubSub Channel
  test/e2e/e2e_test.go
  test/e2e/lib/scheduler.go
  test/e2e/test_broker_pubsub.go
  test/e2e/test_scheduler.go
Labels: approved, lgtm, size/L

#565 add ngiraldo to mako configs
  test/performance/benchmarks/broker-pubsub/dev.config
  test/performance/benchmarks/broker-pubsub/prod.config
  test/performance/benchmarks/channel-pubsub/dev.config
  test/performance/benchmarks/channel-pubsub/prod.config
Labels: approved, lgtm, size/XS

#566 Fix typo in storage doc
  docs/examples/cloudstoragesource/README.md
Labels: approved, lgtm, size/XS

#567 Removing unused pubsubSecret from sources.spec
  config/300-cloudauditlogssource.yaml
  config/300-cloudpubsubsource.yaml
  config/300-cloudschedulersource.yaml
  config/300-cloudstoragesource.yaml
  config/300-pullsubscription.yaml
  pkg/apis/duck/v1alpha1/pubsub_types.go
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/events/v1alpha1/cloudauditlogssource_validation.go
  pkg/apis/events/v1alpha1/cloudauditlogssource_validation_test.go
  pkg/apis/events/v1alpha1/cloudpubsubsource_validation.go
  pkg/apis/events/v1alpha1/cloudpubsubsource_validation_test.go
  pkg/apis/events/v1alpha1/cloudschedulersource_validation.go
  pkg/apis/events/v1alpha1/cloudschedulersource_validation_test.go
  pkg/apis/events/v1alpha1/cloudstoragesource_validation.go
  pkg/apis/events/v1alpha1/cloudstoragesource_validation_test.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_validation.go
  pkg/apis/pubsub/v1alpha1/pullsubscription_validation_test.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/pubsub/resources/pullsubscription.go
  pkg/reconciler/pubsub/resources/topic.go
  pkg/reconciler/pubsub/resources/topic_test.go
Labels: approved, lgtm, size/XL

#572 No wait in ko delete for performance testing
  test/performance/performance-tests.sh
Labels: approved, lgtm, size/XS

#573 Fail fast for e2e test and performance test
  test/e2e-common.sh
  test/lib.sh
  test/performance/performance-tests.sh
Labels: approved, lgtm, size/S

#576 Fix spelling errors
  test/test_images/scheduler_target/main.go
Labels: approved, lgtm, ok-to-test, size/XS

#578 golang format tools
  pkg/apis/duck/v1alpha1/annotations_test.go
  pkg/apis/duck/v1alpha1/pubsub_lifecycle.go
  pkg/apis/events/v1alpha1/cloudschedulersource_validation_test.go
  pkg/apis/events/v1alpha1/cloudstoragesource_validation_test.go
  pkg/apis/pubsub/v1alpha1/topic_lifecycle.go
  pkg/gclient/scheduler/client.go
  pkg/gclient/scheduler/testing/client.go
  pkg/pubsub/adapter/converters/auditlogs.go
  pkg/pubsub/adapter/converters/auditlogs_test.go
  pkg/pubsub/adapter/converters/storage.go
  pkg/pubsub/publisher/publisher.go
  pkg/reconciler/events/auditlogs/controller.go
  pkg/reconciler/pubsub/pullsubscription/keda/controller_test.go
  pkg/reconciler/pubsub/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/pubsub/pullsubscription/keda/resources/names_test.go
  pkg/reconciler/pubsub/pullsubscription/keda/resources/scaled_object.go
  pkg/reconciler/pubsub/pullsubscription/keda/resources/scaled_object_test.go
  pkg/reconciler/pubsub/pullsubscription/reconciler.go
  pkg/reconciler/pubsub/pullsubscription/resources/receive_adapter.go
  pkg/reconciler/pubsub/pullsubscription/static/pullsubscription.go
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/pubsub/topic/controller.go
  test/e2e/lib/secrets.go
  test/e2e/test_pullsubscription.go
  test/test_images/target/main.go
Labels: approved, lgtm, ok-to-test, size/M

#579 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_defaults.go
  vendor/knative.dev/serving/pkg/apis/config/store.go
  vendor/knative.dev/serving/pkg/apis/config/testdata/config-autoscaler.yaml
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/autoscaler/config/doc.go
  vendor/knative.dev/serving/pkg/autoscaler/config/zz_generated.deepcopy.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, lgtm, ok-to-test, size/L

#580 Fixing links in docs
  docs/install/pubsub-service-account.md
  test/e2e/README.md
Labels: approved, lgtm, size/XS

#577 Format markdown
  README.md
  docs/examples/channel/README.md
  docs/examples/cloudauditlogssource/README.md
  docs/examples/cloudpubsubsource/README.md
  docs/examples/cloudschedulersource/README.md
  docs/examples/cloudstoragesource/README.md
  docs/examples/pullsubscription/README.md
  docs/examples/topic/README.md
  docs/install/install-broker-with-pubsub-channel.md
  docs/install/install-knative-gcp.md
  docs/install/pubsub-service-account.md
  test/e2e/README.md
Labels: approved, lgtm, ok-to-test, size/XL
