Repository google/knative-gcp, pull requests merged in 2020-01, with the labels that each got.

#474 Update path to event-display image in examples
  docs/channel/event-display.yaml
  docs/pullsubscription/event-display.yaml
  docs/scheduler/event-display.yaml
  docs/storage/event-display.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#472 added docs for CAL source
  README.md
  docs/README.md
  docs/auditlogssource/README.md
  docs/auditlogssource/auditlogssource.yaml
  docs/auditlogssource/event-display.yaml
  docs/install/README.md
Labels: approved, lgtm, size/L

#476 Added a converter for scheduler to set up its ce-type and ce-source
  config/300-scheduler.yaml
  docs/scheduler/README.md
  pkg/apis/events/v1alpha1/scheduler_types.go
  pkg/pubsub/adapter/converters/converters.go
  pkg/pubsub/adapter/converters/scheduler_test.go
  pkg/pubsub/adapter/converters/sheduler.go
  pkg/pubsub/adapter/converters/storage.go
  pkg/reconciler/events/scheduler/resources/names.go
  pkg/reconciler/events/scheduler/scheduler.go
  pkg/reconciler/events/storage/storage.go
Labels: approved, lgtm, size/L

#465 Fixing wrong link in Channel doc
  docs/channel/README.md
Labels: approved, lgtm, size/XS

#487 Update test-infra to latest
  Gopkg.lock
  test/lib.sh
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/M

#481 Standardize True/False/Unknown status throughout knative-gcp
  pkg/apis/duck/v1alpha1/pubsub_lifecycle.go
  pkg/apis/events/v1alpha1/auditlogs_lifecycle.go
  pkg/apis/events/v1alpha1/auditlogs_lifecycle_test.go
  pkg/apis/events/v1alpha1/pubsub_lifecycle.go
  pkg/apis/events/v1alpha1/pubsub_lifecycle_test.go
  pkg/apis/events/v1alpha1/scheduler_lifecycle.go
  pkg/apis/events/v1alpha1/scheduler_lifecycle_test.go
  pkg/apis/events/v1alpha1/storage_lifecycle.go
  pkg/apis/events/v1alpha1/storage_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/channel_lifecycle.go
  pkg/apis/messaging/v1alpha1/channel_lifecycle_test.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_lifecycle.go
  pkg/apis/pubsub/v1alpha1/pull_subscription_lifecycle_test.go
  pkg/apis/pubsub/v1alpha1/topic_lifecycle.go
  pkg/apis/pubsub/v1alpha1/topic_lifecycle_test.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/pubsub/pubsub.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/messaging/channel/channel.go
  pkg/reconciler/messaging/channel/channel_test.go
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/pubsub/reconciler_test.go
  pkg/reconciler/testing/auditlogs.go
  pkg/reconciler/testing/channel.go
  pkg/reconciler/testing/pubsub.go
  pkg/reconciler/testing/pullsubscription.go
  pkg/reconciler/testing/scheduler.go
  pkg/reconciler/testing/storage.go
  pkg/reconciler/testing/topic.go
Labels: approved, lgtm, size/XXL

#489 CAL nits
  config/300-auditlogssource.yaml
  docs/auditlogssource/README.md
  docs/install/README.md
Labels: approved, lgtm, size/S

#491 fixed scheduler typo
  config/300-scheduler.yaml
  docs/scheduler/README.md
  pkg/apis/events/v1alpha1/scheduler_types.go
Labels: approved, lgtm, size/XS

#506 Specify sideEffects in the webhook
  config/500-webhook-configuration.yaml
Labels: approved, lgtm, size/XS

#505 Reenable channel related tests for release-0.12
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/XS

#498 UTs for CloudAuditLogsSource validation
  pkg/apis/events/v1alpha1/cloudauditlogssource_validation_test.go
Labels: approved, lgtm, size/L

#514 fixed CloudAuditLogs reconcile bug
  pkg/reconciler/events/auditlogs/controller.go
Labels: approved, lgtm, size/XS

#515 fixed CloudAuditLogs reconcile bug (#514)
  pkg/reconciler/events/auditlogs/controller.go
Labels: approved, lgtm, size/XS

#516 Update SDK due to critical bug found while decoding messages
  Gopkg.lock
  Gopkg.toml
  pkg/pubsub/publisher/publisher.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/pubsub/codec_v1.go
Labels: approved, lgtm, size/M

#517 Updating CloudEvents SDK to fix a critical bug in PubSub codec
  Gopkg.lock
  Gopkg.toml
  pkg/pubsub/publisher/publisher.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/pubsub/codec_v1.go
Labels: approved, lgtm, size/M

#518 Updating sdk to particular revision instead of master
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/XS

#519 Moving sdk to revision instead of master
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/XS

#512 Move ConvertToPush method to pubsub.go
  pkg/pubsub/adapter/adapter.go
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/pubsub_test.go
  pkg/pubsub/adapter/push.go
  pkg/pubsub/adapter/push_test.go
Labels: approved, lgtm, size/L

#520 Move ConvertToPush method to pubsub.go
  pkg/pubsub/adapter/adapter.go
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/pubsub_test.go
  pkg/pubsub/adapter/push.go
  pkg/pubsub/adapter/push_test.go
Labels: approved, lgtm, size/L

#521 CloudPubSubSource to Push mode
  docs/examples/cloudauditlogssource/README.md
  docs/examples/cloudpubsubsource/README.md
  docs/examples/pullsubscription/README.md
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/reconciler/events/pubsub/pubsub.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/pubsub/resources/pullsubscription.go
  pkg/reconciler/pubsub/resources/pullsubscription_test.go
  pkg/reconciler/testing/pullsubscription.go
  test/test_images/target/main.go
Labels: approved, lgtm, size/L

#522 CloudPubSubSource to Push mode
  docs/examples/cloudauditlogssource/README.md
  docs/examples/cloudpubsubsource/README.md
  docs/examples/cloudpubsubsource/cloudpubsubsource.yaml
  docs/examples/cloudpubsubsource/event-display.yaml
  docs/examples/pullsubscription/README.md
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/reconciler/events/pubsub/pubsub.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/pubsub/reconciler.go
  pkg/reconciler/pubsub/resources/pullsubscription.go
  pkg/reconciler/pubsub/resources/pullsubscription_test.go
  pkg/reconciler/testing/pullsubscription.go
  test/test_images/target/main.go
Labels: approved, lgtm, size/L

#523 Updating push format
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/pubsub_test.go
Labels: approved, lgtm, size/S

#524 Push format json tag updates
  pkg/pubsub/adapter/converters/pubsub.go
  pkg/pubsub/adapter/converters/pubsub_test.go
Labels: approved, lgtm, size/S

#508 add retries/fallbacks for update status
  Gopkg.lock
  pkg/reconciler/events/auditlogs/auditlogs.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/pubsub/pubsub.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/events/scheduler/scheduler.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/messaging/channel/channel.go
  pkg/reconciler/messaging/channel/channel_test.go
  pkg/reconciler/pubsub/pullsubscription/pullsubscription.go
  pkg/reconciler/pubsub/pullsubscription/pullsubscription_test.go
  pkg/reconciler/pubsub/topic/topic.go
  pkg/reconciler/pubsub/topic/topic_test.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/convert.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
Labels: approved, lgtm, size/XL

#525 Update pkg to solve two performance test related issues
  Gopkg.lock
  vendor/knative.dev/pkg/test/mako/alerter/alerter.go
  vendor/knative.dev/pkg/test/slackutil/message_read.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
Labels: approved, lgtm, size/S

#526 Fixing invalid CAL registry annotation
  config/300-cloudauditlogssource.yaml
  config/300-cloudschedulersource.yaml
Labels: approved, lgtm, size/XS

#528 Updated the init.sh
  hack/init.sh
  hack/shortcuts/setup_ns_broker.sh
Labels: approved, lgtm, size/L

#527 Use e2 VMs instead of n1 for performance test clusters
  test/performance/benchmarks/broker-pubsub/cluster.yaml
  test/performance/benchmarks/channel-pubsub/cluster.yaml
Labels: approved, lgtm, size/XS

#529 Splitting init scripts
  docs/examples/cloudstoragesource/README.md
  hack/init.sh
  hack/init_control_plane.sh
  hack/init_data_plane.sh
Labels: approved, lgtm, size/L

#530 Fix CAL registry
  config/300-cloudauditlogssource.yaml
Labels: approved, lgtm, size/XS
