Repository google/knative-gcp, pull requests merged in 2020-08, with the labels that each got.

#1541 Add an option to setup test cluster and skip tests
  test/e2e-tests.sh
  test/e2e-wi-tests.sh
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, size/M

#1542 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/klog/v2/LICENSE
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_windows.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/utils/pointer/README.md
  vendor/k8s.io/utils/trace/README.md
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#1538 Mark status of sub-conditions in finalizer of sources
  pkg/apis/events/v1/cloudauditlogssource_lifecycle.go
  pkg/apis/events/v1/cloudauditlogssource_lifecycle_test.go
  pkg/apis/events/v1/cloudschedulersource_lifecycle.go
  pkg/apis/events/v1/cloudschedulersource_lifecycle_test.go
  pkg/apis/events/v1/cloudstoragesource_lifecycle.go
  pkg/apis/events/v1/cloudstoragesource_lifecycle_test.go
  pkg/apis/events/v1alpha1/cloudschedulersource_lifecycle.go
  pkg/apis/events/v1alpha1/cloudschedulersource_lifecycle_test.go
  pkg/apis/events/v1beta1/cloudschedulersource_lifecycle.go
  pkg/apis/events/v1beta1/cloudschedulersource_lifecycle_test.go
  pkg/apis/events/v1beta1/cloudstoragesource_lifecycle_test.go
  pkg/reconciler/events/auditlogs/auditlogs.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/scheduler/scheduler.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/testing/v1/auditlogs.go
  pkg/reconciler/testing/v1/scheduler.go
  pkg/reconciler/testing/v1/storage.go
Labels: approved, cla: yes, lgtm, size/XL

#1549 Remove logging full event on publish errors
  pkg/broker/ingress/handler.go
Labels: approved, cla: yes, lgtm, size/XS

#1554 [master] Format markdown
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1555 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/inmemorychannel.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_header_single_event_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e-conformance-tests.sh
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_redelivery_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/parallel_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/sequence_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/trigger_no_broker_test_helper.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1557 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1556 Update PubSub and WI finalizer sub-condition mark to make them consistent with source and broker
  pkg/apis/duck/v1/identity_lifecycle.go
  pkg/apis/duck/v1/identity_lifecycle_test.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/identity/reconciler.go
  pkg/reconciler/intevents/reconciler.go
  pkg/reconciler/testing/v1/auditlogs.go
  pkg/reconciler/testing/v1/scheduler.go
  pkg/reconciler/testing/v1/storage.go
Labels: approved, cla: yes, lgtm, size/L

#1539 Update brokercell and channel CRDs API version
  config/core/resources/brokercell.yaml
  config/core/resources/channel.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1560 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/test/logstream/null.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1536 Implement the Broker delivery spec
  cmd/webhook/main.go
  docs/spec/delivery.md
  go.mod
  pkg/apis/broker/v1beta1/broker_defaults.go
  pkg/apis/broker/v1beta1/broker_lifecycle.go
  pkg/apis/broker/v1beta1/broker_lifecycle_test.go
  pkg/apis/broker/v1beta1/broker_validation.go
  pkg/apis/broker/v1beta1/broker_validation_test.go
  pkg/reconciler/broker/create_brokercell.go
  pkg/reconciler/testing/broker.go
  pkg/reconciler/testing/pstest.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1559 Add docs for perf test setup and scenarios
  docs/development/images/metrics-example.png
  docs/development/images/profile-example.png
  docs/development/images/wl-resource-example.png
  docs/development/manual-br-perf-test.md
Labels: approved, cla: yes, lgtm, size/L

#1561 Removed Sprintf from logging
  pkg/broker/ingress/handler.go
Labels: approved, cla: yes, lgtm, size/S

#1402 Define brokercell components for broker-gcp perf test
  test/performance/benchmarks/broker-gcp/100-broker-gcp-setup.yaml
  test/performance/benchmarks/broker-gcp/continuous/100-broker-gcp-setup.yaml
Labels: approved, cla: yes, lgtm, size/M

#1537 ping back to latest nightly serving
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/XS

#1563 [master] Format markdown
  docs/spec/delivery.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1562 Mark v1alpha1 source as deprecated in conversion
  pkg/apis/convert/conversion_helper.go
  pkg/apis/convert/conversion_helper_test.go
  pkg/apis/events/v1alpha1/cloudauditlogssource_conversion.go
  pkg/apis/events/v1alpha1/cloudauditlogssource_conversion_test.go
  pkg/apis/events/v1alpha1/cloudbuildsource_conversion.go
  pkg/apis/events/v1alpha1/cloudbuildsource_conversion_test.go
  pkg/apis/events/v1alpha1/cloudpubsubsource_conversion.go
  pkg/apis/events/v1alpha1/cloudpubsubsource_conversion_test.go
  pkg/apis/events/v1alpha1/cloudschedulersource_conversion.go
  pkg/apis/events/v1alpha1/cloudschedulersource_conversion_test.go
  pkg/apis/events/v1alpha1/cloudstoragesource_conversion.go
  pkg/apis/events/v1alpha1/cloudstoragesource_conversion_test.go
  pkg/apis/intevents/v1alpha1/pullsubscription_conversion.go
  pkg/apis/intevents/v1alpha1/pullsubscription_conversion_test.go
  pkg/apis/intevents/v1alpha1/topic_conversion.go
  pkg/apis/intevents/v1alpha1/topic_conversion_test.go
  pkg/apis/messaging/v1alpha1/channel_conversion.go
  pkg/apis/messaging/v1alpha1/channel_conversion_test.go
  pkg/testing/test_helper.go
Labels: approved, cla: yes, lgtm, size/XL

#1567 Add a simple release script for probe helper; add log messages for debugging
  test/test_images/probe_helper/probe_helper.go
  test/test_images/probe_helper/release.sh
Labels: approved, cla: yes, lgtm, size/S

#1569 Increase sleep time for deletion test
  test/e2e/lib/resources/constants.go
  test/e2e/test_auditlogs.go
  test/e2e/test_build.go
  test/e2e/test_gcp_broker.go
  test/e2e/test_pubsub.go
  test/e2e/test_scheduler.go
  test/e2e/test_storage.go
Labels: approved, cla: yes, lgtm, size/S

#1570 Update sender retry configuration
  test/test_images/sender/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1558 Add Delivery Retry Benchmark and Update PubSub Protocol
  go.mod
  go.sum
  pkg/broker/handler/processors/deliver/processor_test.go
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/write_pubsub_message.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1575 Pin knative/pkg and knative/test-infra to release-0.17
  go.mod
  go.sum
  hack/update-deps.sh
  test/e2e-wi-tests.sh
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_combined_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/register.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/serving/pkg/apis/config/store.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1582 Add constants and methods for brokerCell args
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/path.go
  pkg/broker/ingress/path_test.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/create_brokercell.go
Labels: approved, cla: yes, lgtm, size/L

#1571 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1alpha1/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1alpha1/pingsource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha1/expansion_generated.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha1/pingsource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/listers.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#1578 Add timeout delivery metrics
  pkg/broker/handler/fanout_test.go
  pkg/broker/handler/processors/deliver/processor.go
  pkg/metrics/delivery_reporter.go
  pkg/metrics/delivery_reporter_test.go
  pkg/metrics/testing/delivery.go
Labels: approved, cla: yes, lgtm, size/L

#1580 Add another 30 second to the CloudAuditLogSource waiting time
  test/e2e/lib/resources/constants.go
Labels: approved, cla: yes, lgtm, size/XS

#1584 Add extra ready time for sources
  test/e2e/lib/auditlogs.go
  test/e2e/lib/resources/constants.go
  test/e2e/lib/scheduler.go
  test/e2e/lib/storage.go
Labels: approved, cla: yes, lgtm, size/M

#1586 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_defaults.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/register.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1573 Extend Probe Helper for use with CloudPubSubSource probe
  test/test_images/probe_helper/probe_helper.go
  test/test_images/probe_helper/probe_helper.yaml
Labels: approved, cla: yes, lgtm, size/L

#1581 Metrics to monitor latencies on BrokerCell (#1443)
  config/core/deployments/controller.yaml
  pkg/metrics/brokercell_delay_reporter.go
  pkg/metrics/brokercell_delay_reporter_test.go
  pkg/metrics/tags.go
  pkg/metrics/testing/helper.go
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/controller.go
  pkg/reconciler/brokercell/controller_test.go
  pkg/utils/customresource/typegenerics.go
  pkg/utils/customresource/typegenerics_test.go
Labels: approved, cla: yes, lgtm, size/L

#1589 Modify e2e tests readme to contain policy binding for cloudtrace.admin role to run trace related e2e tests
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1509 #1484. Configurable CPU and memory params for BrokerCell
  cmd/webhook/main.go
  config/core/resources/brokercell.yaml
  pkg/apis/intevents/v1alpha1/brokercell_defaults.go
  pkg/apis/intevents/v1alpha1/brokercell_defaults_test.go
  pkg/apis/intevents/v1alpha1/brokercell_types.go
  pkg/apis/intevents/v1alpha1/brokercell_validation.go
  pkg/apis/intevents/v1alpha1/brokercell_validation_test.go
  pkg/apis/intevents/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/resources/args.go
  pkg/reconciler/brokercell/resources/deployments.go
  pkg/utils/resource/resource.go
  pkg/utils/resource/resource_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1585 Eliminate creating a new broker ingress span and add broker ingress attributes to the existing http span
  pkg/broker/ingress/handler.go
  test/e2e/lib/helpers/broker_tracing.go
Labels: approved, cla: yes, lgtm, size/XS

#1604 Pin knative/eventing and knative/serving to release-0.17
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1590 Add util function to ensure that a given environment variable is set and use it for e2e tests
  test/e2e/lib/auditlogs.go
  test/e2e/lib/build.go
  test/e2e/lib/pubsub.go
  test/e2e/lib/scheduler.go
  test/e2e/lib/storage.go
  test/e2e/lib/subscription.go
  test/e2e/lib/topics.go
  test/e2e/lib/utils.go
  test/e2e/test_auditlogs.go
  test/e2e/test_build.go
  test/e2e/test_gcp_broker.go
  test/e2e/test_pubsub.go
  test/e2e/test_pullsubscription.go
  test/e2e/test_storage.go
Labels: approved, cla: yes, lgtm, size/L

#1587 Setup performance test to evaluate max throughput
  test/performance/benchmarks/broker-gcp/continuous/100-broker-gcp-setup.yaml
  test/performance/benchmarks/broker-gcp/continuous/200-broker-gcp.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1607 Change the doc to indicate both serving and eventing are required
  docs/install/install-knative-gcp.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1615 Fix WI tests by using the correct project ID
  test/e2e-wi-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1614 Fix WI tests by using the correct project ID
  test/e2e-wi-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1606 Unpin release-0.17
  go.mod
  go.sum
  hack/update-deps.sh
  pkg/client/injection/reconciler/broker/v1beta1/broker/reconciler.go
  pkg/client/injection/reconciler/broker/v1beta1/trigger/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudauditlogssource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudpubsubsource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudschedulersource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudstoragesource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudauditlogssource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudbuildsource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudpubsubsource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudschedulersource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudstoragesource/reconciler.go
  pkg/client/injection/reconciler/intevents/v1/pullsubscription/reconciler.go
  pkg/client/injection/reconciler/intevents/v1/topic/reconciler.go
  pkg/client/injection/reconciler/intevents/v1alpha1/brokercell/reconciler.go
  pkg/client/injection/reconciler/intevents/v1beta1/pullsubscription/reconciler.go
  pkg/client/injection/reconciler/intevents/v1beta1/topic/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/kmp/diff.go
  vendor/knative.dev/pkg/kmp/reporters.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1617 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/reconciler/sugar/labels.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1616 [master] Format markdown
  docs/install/install-knative-gcp.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1618 Remove the no longer needed 0.16.0 upgrade binary.
  cmd/upgrade/v0.16.0/main.go
  config/upgrade/v0.16.0/README.md
  config/upgrade/v0.16.0/upgrade.yaml
  hack/release.sh
  pkg/upgrader/v0.16.0/upgrader.go
  pkg/upgrader/v0.16.0/upgrader_test.go
Labels: approved, cla: yes, lgtm, size/L

#1630 Update cloud-trace.md to work with the latest GCP
  docs/how-to/cloud-trace.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1628 Check the decouple queue state instead of the overall broker state in ingress
  pkg/broker/config/targets.pb.go
  pkg/broker/config/targets.proto
  pkg/broker/ingress/handler_test.go
  pkg/broker/ingress/multi_topic_decouple_sink.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/testingdata/configmap.go
Labels: approved, cla: yes, lgtm, size/L

#1636 Reduced flakiness in deletion and source test
  test/e2e/lib/resources/constants.go
  test/e2e/test_auditlogs.go
  test/e2e/test_build.go
  test/e2e/test_gcp_broker.go
  test/e2e/test_pubsub.go
  test/e2e/test_scheduler.go
  test/e2e/test_storage.go
Labels: approved, cla: yes, lgtm, size/S

#1626 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1637 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1633 Change EventType of CloudBuildSource
  config/core/resources/cloudbuildsource.yaml
  docs/examples/cloudbuildsource/README.md
  pkg/apis/events/v1alpha1/cloudbuildsource_types.go
  pkg/pubsub/adapter/converters/build.go
  pkg/schemas/v1/build.go
Labels: approved, cla: yes, lgtm, size/S

#1634 Fix prerequisite links in metrics/REAMD.md and install-gcp-broker.md
  docs/examples/metrics/README.md
  docs/install/install-gcp-broker.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1625 [master] Format markdown
  docs/examples/metrics/README.md
  docs/how-to/broker-priority.md
  docs/how-to/metrics.md
  docs/install/authentication-mechanisms-gcp.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1638 Metric exemplar
  pkg/metrics/delivery_reporter.go
  pkg/metrics/ingress_reporter.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#1641 Separate auth troubleshooting doc and add references
  docs/examples/channel/README.md
  docs/examples/cloudauditlogssource/README.md
  docs/examples/cloudbuildsource/README.md
  docs/examples/cloudpubsubsource/README.md
  docs/examples/cloudschedulersource/README.md
  docs/examples/cloudstoragesource/README.md
  docs/examples/pullsubscription/README.md
  docs/examples/topic/README.md
  docs/how-to/authentication-mechanism-troubleshooting.md
  docs/install/authentication-mechanisms-gcp.md
Labels: approved, cla: yes, lgtm, size/XL

#1642 [master] Format markdown
  docs/examples/channel/README.md
  docs/examples/cloudauditlogssource/README.md
  docs/examples/cloudbuildsource/README.md
  docs/examples/cloudpubsubsource/README.md
  docs/examples/cloudschedulersource/README.md
  docs/examples/cloudstoragesource/README.md
  docs/examples/pullsubscription/README.md
  docs/examples/topic/README.md
  docs/how-to/authentication-mechanism-troubleshooting.md
  docs/install/authentication-mechanisms-gcp.md
  docs/install/install-gcp-broker.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1643 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/service.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1646 Switch to a nonroot base image.
  .ko.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1648 Add pre-install storage migration jobs to release manifest
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1649 Fixing UTs and updating deps
  go.mod
  go.sum
  pkg/apis/duck/validations_test.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/deployment/controller_test.go
  pkg/reconciler/deployment/deployment_test.go
  pkg/reconciler/events/auditlogs/auditlogs_test.go
  pkg/reconciler/events/auditlogs/controller_test.go
  pkg/reconciler/events/build/build_test.go
  pkg/reconciler/events/build/controller_test.go
  pkg/reconciler/events/pubsub/controller_test.go
  pkg/reconciler/events/pubsub/pubsub_test.go
  pkg/reconciler/events/scheduler/controller_test.go
  pkg/reconciler/events/scheduler/scheduler_test.go
  pkg/reconciler/events/storage/controller_test.go
  pkg/reconciler/events/storage/storage_test.go
  pkg/reconciler/intevents/controller_test.go
  pkg/reconciler/intevents/pullsubscription/keda/controller_test.go
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/intevents/pullsubscription/static/controller_test.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription_test.go
  pkg/reconciler/intevents/reconciler_test.go
  pkg/reconciler/intevents/topic/controller_test.go
  pkg/reconciler/intevents/topic/topic_test.go
  pkg/reconciler/messaging/channel/channel_test.go
  pkg/reconciler/messaging/channel/controller_test.go
  pkg/reconciler/trigger/trigger_test.go
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/message.go
  vendor/github.com/cloudevents/sdk-go/protocol/pubsub/v2/write_pubsub_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/event_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/to_event.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/sugar/labels.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_spec_test_helper.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/system/testing/names.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1605 Improved UX for BrokerCell Configurability
  config/core/resources/brokercell.yaml
  pkg/apis/intevents/v1alpha1/brokercell_defaults.go
  pkg/apis/intevents/v1alpha1/brokercell_defaults_test.go
  pkg/apis/intevents/v1alpha1/brokercell_types.go
  pkg/apis/intevents/v1alpha1/brokercell_validation.go
  pkg/apis/intevents/v1alpha1/brokercell_validation_test.go
  pkg/apis/intevents/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/resources/args.go
  pkg/reconciler/brokercell/resources/hpa.go
  pkg/utils/resource/resource.go
  pkg/utils/resource/resource_test.go
Labels: approved, cla: yes, lgtm, size/XL
