Repository google/knative-gcp, pull requests merged in 2021-02, with the labels that each got.

#2112 Remove empty spec
  test/performance/benchmarks/broker-gcp/continuous/100-broker-gcp-setup.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2104 Split data plane GSA to broker & sources GSAs in e2e scripts
  hack/init_control_plane.sh
  hack/init_control_plane_gke.sh
  hack/init_data_plane.sh
  hack/init_data_plane_gke.sh
  hack/lib.sh
  test/e2e-common.sh
  test/e2e-secret-tests.sh
  test/e2e-wi-tests.sh
  test/performance/performance-tests.sh
  test/test_configs/config-gcp-auth-wi.yaml
Labels: approved, cla: yes, lgtm, size/L

#2099 Add filter broker class when building the routing config
  pkg/reconciler/broker/controller.go
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/utils/filter.go
Labels: approved, cla: yes, lgtm, size/L

#2116 Update PS & Topic reconcilers to use Base instead of PubSubBase
  pkg/reconciler/intevents/pullsubscription/keda/controller.go
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/intevents/pullsubscription/reconciler.go
  pkg/reconciler/intevents/pullsubscription/static/controller.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription_test.go
  pkg/reconciler/intevents/topic/controller.go
  pkg/reconciler/intevents/topic/topic.go
  pkg/reconciler/intevents/topic/topic_test.go
Labels: approved, cla: yes, lgtm, size/M

#2107 Failures to send Replies are considered delivery failures
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
Labels: approved, cla: yes, lgtm, size/L

#2115 Fix failure during serving installation in e2e test
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/XS

#2120 Change the receiver to pointer type
  pkg/reconciler/celltenant/interfaces.go
Labels: approved, cla: yes, lgtm, size/M

#2110 Extend Probe Helper to cover ApiServerSource
  pkg/schemas/v1/auditlogs_test.go
  test/test_images/probe_helper/probe/handlers/apiserver.go
  test/test_images/probe_helper/probe/handlers/cloudauditlogs.go
  test/test_images/probe_helper/probe/handlers/event_type.go
  test/test_images/probe_helper/probe/handlers/providers.go
  test/test_images/probe_helper/probe/helper_test.go
  test/test_images/probe_helper/probe/providers.go
  test/test_images/probe_helper/probe/wire.go
  test/test_images/probe_helper/probe/wire_gen.go
  test/test_images/probe_helper/wire_gen.go
Labels: approved, cla: yes, lgtm, size/L

#2080 Update namespace transition instructions
  docs/how-to/namespace-transition.md
  docs/how-to/namespace-transition.sh
  docs/how-to/namespace-transition.yaml
Labels: approved, cla: yes, lgtm, size/L

#2126 rename dummy.go to placeholder.go
  config/core/configmaps/placeholder.go
  config/core/deployments/placeholder.go
  config/core/placeholder.go
  config/core/resources/placeholder.go
  config/core/roles/placeholder.go
  config/core/services/placeholder.go
  config/core/webhooks/placeholder.go
  config/istio/placeholder.go
  config/monitoring/metrics/grafana/placeholder.go
  config/monitoring/metrics/prometheus/placeholder.go
  config/placeholder.go
  config/pre-install/v0.18.0/placeholder.go
  config/pre-install/v0.19.0/placeholder.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2127 Mark pullSubscription as empty when it is deleted
  pkg/reconciler/intevents/reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#2128 Get deployment of receive adapter by deployment's name
  pkg/reconciler/intevents/pullsubscription/keda/pullsubscription_test.go
  pkg/reconciler/intevents/pullsubscription/reconciler.go
  pkg/reconciler/intevents/pullsubscription/static/pullsubscription_test.go
Labels: approved, cla: yes, lgtm, size/M

#2130 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2032 CellTenant targets ReplyAddress
  pkg/broker/config/targets.pb.go
  pkg/broker/config/targets.proto
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/testingdata/configmap.go
Labels: approved, cla: yes, lgtm, size/L

#2131 Update docs after renaming the branch
  README.md
  docs/how-to/namespace-transition.md
  docs/install/authentication-mechanisms-gcp.md
  docs/install/dataplane-service-account.md
  docs/install/install-gcp-broker.md
  docs/install/install-knative-gcp.md
  pkg/broker/ingress/handler.go
Labels: approved, cla: yes, lgtm, size/M

#2132 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2125 Fail when there is any unavailability during upgrade
  test/upgrade/config.toml
Labels: approved, cla: yes, lgtm, size/XS

#2124 Dump more system namespace controller pods in case of failure
  test.md
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/M

#2133 Add Bharatt to Owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2129 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2134 [Automated] Format markdown
  docs/install/dataplane-service-account.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2137 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/contrib.go.opencensus.io/exporter/stackdriver/resource.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stackdriver.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/go.opencensus.io/.travis.yml
  vendor/go.opencensus.io/go.mod
  vendor/go.opencensus.io/go.sum
  vendor/go.opencensus.io/metric/metricexport/reader.go
  vendor/go.opencensus.io/trace/basetypes.go
  vendor/go.opencensus.io/trace/spanstore.go
  vendor/go.opencensus.io/trace/trace.go
  vendor/go.opencensus.io/trace/trace_api.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/google.golang.org/grpc/Makefile
  vendor/google.golang.org/grpc/SECURITY.md
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_remote_balancer.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_util.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/internal/grpcutil/target.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/metadata/metadata.go
  vendor/google.golang.org/grpc/internal/resolver/config_selector.go
  vendor/google.golang.org/grpc/internal/resolver/unix/unix.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_linux.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/test/e2e/helpers/README.md
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#2140 Remove @Harwayne from OWNERS.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2139 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_types.go
  vendor/knative.dev/eventing/test/e2e/helpers/README.md
  vendor/knative.dev/networking/pkg/stats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2136 Improve probe helper logging
  test/test_images/probe_helper/main.go
  test/test_images/probe_helper/probe/handlers/apiserver.go
  test/test_images/probe_helper/probe/handlers/broker_e2e_delivery.go
  test/test_images/probe_helper/probe/handlers/cloudauditlogs.go
  test/test_images/probe_helper/probe/handlers/cloudpubsub.go
  test/test_images/probe_helper/probe/handlers/cloudscheduler.go
  test/test_images/probe_helper/probe/handlers/cloudstorage.go
  test/test_images/probe_helper/probe/handlers/ping.go
  test/test_images/probe_helper/probe/helper.go
Labels: approved, cla: yes, lgtm, size/M

#2034 Channels are backed by BrokerCells
  cmd/controller/wire_gen.go
  config/core/resources/channel.yaml
  pkg/apis/broker/v1beta1/broker_lifecycle.go
  pkg/apis/broker/v1beta1/broker_lifecycle_test.go
  pkg/apis/broker/v1beta1/broker_validation.go
  pkg/apis/broker/v1beta1/test_helper.go
  pkg/apis/broker/v1beta1/trigger_lifecycle.go
  pkg/apis/broker/v1beta1/trigger_lifecycle_test.go
  pkg/apis/messaging/v1beta1/channel_defaults.go
  pkg/apis/messaging/v1beta1/channel_defaults_test.go
  pkg/apis/messaging/v1beta1/channel_lifecycle.go
  pkg/apis/messaging/v1beta1/channel_lifecycle_test.go
  pkg/apis/messaging/v1beta1/channel_types.go
  pkg/apis/messaging/v1beta1/channel_types_test.go
  pkg/apis/messaging/v1beta1/channel_validation.go
  pkg/apis/messaging/v1beta1/channel_validation_test.go
  pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  pkg/broker/config/key.go
  pkg/broker/config/key_test.go
  pkg/broker/config/targets.pb.go
  pkg/broker/config/targets.proto
  pkg/broker/handler/processors/deliver/processor_test.go
  pkg/reconciler/broker/resources/names_test.go
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/brokercell.go
  pkg/reconciler/brokercell/brokercell_test.go
  pkg/reconciler/brokercell/controller.go
  pkg/reconciler/brokercell/controller_test.go
  pkg/reconciler/brokercell/testingdata/configmap.go
  pkg/reconciler/celltenant/interfaces.go
  pkg/reconciler/celltenant/target.go
  pkg/reconciler/messaging/channel/channel.go
  pkg/reconciler/messaging/channel/channel_test.go
  pkg/reconciler/messaging/channel/controller.go
  pkg/reconciler/messaging/channel/controller_test.go
  pkg/reconciler/messaging/channel/resources/names.go
  pkg/reconciler/messaging/channel/resources/names_test.go
  pkg/reconciler/messaging/channel/resources/pullsubscription.go
  pkg/reconciler/messaging/channel/resources/pullsubscription_test.go
  pkg/reconciler/messaging/channel/resources/topic.go
  pkg/reconciler/messaging/channel/resources/topic_test.go
  pkg/reconciler/testing/broker.go
  pkg/reconciler/testing/channel.go
  pkg/reconciler/testing/factory.go
  pkg/reconciler/testing/pstest.go
  pkg/reconciler/testing/trigger.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/utils/pubsub/subscription.go
  pkg/reconciler/utils/pubsub/testing/status_updater.go
  pkg/reconciler/utils/pubsub/topic.go
  pkg/reconciler/utils/pubsub/types.go
  test/e2e/test_channel.go
Labels: approved, cla: yes, lgtm, size/XXL

#2142 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2138 Add a doc for multi project configuration
  docs/examples/cloudauditlogssource/README.md
  docs/examples/cloudbuildsource/README.md
  docs/examples/cloudpubsubsource/README.md
  docs/examples/cloudschedulersource/README.md
  docs/examples/cloudstoragesource/README.md
  docs/examples/pullsubscription/README.md
  docs/examples/topic/README.md
  docs/install/managing-multiple-projects.md
Labels: approved, cla: yes, lgtm, size/L

#2144 release-0.20: Add safeguards for Broker delivery spec nil pointer dereference
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#2146 backport release-0.18: Check if spec.retry is nil before dereferencing it. (#2052)
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#2147 release-0.18: Add safeguards for Broker delivery spec nil pointer dereference
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#2143 backport release-0.18: Attach broker delivery ConfigMap to controller context (#1887)
  cmd/controller/wire.go
  cmd/controller/wire_gen.go
  cmd/webhook/main.go
  cmd/webhook/wire.go
  cmd/webhook/wire_gen.go
  hack/update-codegen.sh
  pkg/apis/broker/v1beta1/broker_defaults.go
  pkg/apis/broker/v1beta1/broker_defaults_test.go
  pkg/apis/configs/brokerdelivery/br_delivery_defaults.go
  pkg/apis/configs/brokerdelivery/br_delivery_defaults_test.go
  pkg/apis/configs/brokerdelivery/defaults.go
  pkg/apis/configs/brokerdelivery/doc.go
  pkg/apis/configs/brokerdelivery/singleton.go
  pkg/apis/configs/brokerdelivery/singleton_test.go
  pkg/apis/configs/brokerdelivery/store.go
  pkg/apis/configs/brokerdelivery/store_test.go
  pkg/apis/configs/brokerdelivery/testdata/config-br-delivery.yaml
  pkg/apis/configs/brokerdelivery/zz_generated.deepcopy.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
  pkg/reconciler/testing/configmap.go
Labels: approved, cla: yes, lgtm, size/L

#2149 Remove Channel's status.topic.
  pkg/apis/broker/v1beta1/broker_lifecycle.go
  pkg/apis/broker/v1beta1/broker_lifecycle_test.go
  pkg/apis/broker/v1beta1/test_helper.go
  pkg/apis/broker/v1beta1/trigger_lifecycle.go
  pkg/apis/broker/v1beta1/trigger_lifecycle_test.go
  pkg/apis/messaging/v1beta1/channel_defaults.go
  pkg/apis/messaging/v1beta1/channel_lifecycle.go
  pkg/apis/messaging/v1beta1/channel_lifecycle_test.go
  pkg/apis/messaging/v1beta1/channel_types.go
  pkg/reconciler/celltenant/interfaces.go
  pkg/reconciler/messaging/channel/channel_test.go
  pkg/reconciler/testing/broker.go
  pkg/reconciler/testing/channel.go
  pkg/reconciler/testing/trigger.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/utils/pubsub/testing/status_updater.go
  pkg/reconciler/utils/pubsub/topic.go
  pkg/reconciler/utils/pubsub/types.go
Labels: approved, cla: yes, lgtm, size/M

#2152 Use git tag to infer latest version in upgrade test (#1911)
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/S

#2145 backport release-0.19: Check if spec.retry is nil before dereferencing it. (#2052)
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#2148 release-0.19: Add safeguards for Broker delivery spec nil pointer dereference
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#2151 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2150 [Automated] Format markdown
  docs/examples/cloudauditlogssource/README.md
  docs/examples/cloudbuildsource/README.md
  docs/examples/cloudpubsubsource/README.md
  docs/examples/cloudschedulersource/README.md
  docs/examples/cloudstoragesource/README.md
  docs/examples/pullsubscription/README.md
  docs/examples/topic/README.md
  docs/install/managing-multiple-projects.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#2153 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#2154 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#2156 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2157 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#2159 Update woke yaml
  .woke.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2160 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#2141 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2162 Revert "Always pass upgrade tests"
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2163 Fix a race condition in E2E test
  test/e2e/test_authcheck.go
  test/lib/lifecycle.go
  test/lib/utils.go
Labels: approved, cla: yes, lgtm, size/M
