Repository google/knative-gcp, pull requests merged in 2021-01, with the labels that each got.

#2033 Remove unused variable PUBSUBAPICOPY.
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/S

#2035 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2036 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2039 Update OWNERS with new team member
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2038 Fix probe helper client listener and logging
  test/test_images/probe_helper/probe/handlers/broker_e2e_delivery.go
  test/test_images/probe_helper/probe/handlers/cloudauditlogs.go
  test/test_images/probe_helper/probe/handlers/cloudpubsub.go
  test/test_images/probe_helper/probe/handlers/cloudscheduler.go
  test/test_images/probe_helper/probe/handlers/cloudstorage.go
  test/test_images/probe_helper/probe/helper.go
  test/test_images/probe_helper/probe/providers.go
  test/test_images/probe_helper/probe/test_providers.go
  test/test_images/probe_helper/probe/wire_gen.go
  test/test_images/probe_helper/probe_helper.yaml
  test/test_images/probe_helper/wire_gen.go
Labels: approved, cla: yes, lgtm, size/M

#2042 Remove myself from approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2040 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2044 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2049 Add MohamedElhawaty to approvers/reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2043 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2052 Check if spec.retry is nil before dereferencing it.
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#2046 feat/upgrade-test: Use eventing prober instead of our modified version
  go.mod
  test/e2e-upgrade-tests.sh
  test/upgrade/config.toml
  test/upgrade/continual.go
  test/upgrade/prober/prober_test.go
  vendor/knative.dev/eventing/test/upgrade/prober/config.toml
  vendor/knative.dev/eventing/test/upgrade/prober/configuration.go
  vendor/knative.dev/eventing/test/upgrade/prober/forwarder.go
  vendor/knative.dev/eventing/test/upgrade/prober/prober.go
  vendor/knative.dev/eventing/test/upgrade/prober/receiver.go
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2055 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2054 [Automated] Format markdown
  docs/how-to/authentication-mechanism-troubleshooting.md
  docs/how-to/broker-priority.md
  docs/how-to/cloud-trace.md
  docs/how-to/metrics.md
  docs/install/install-broker-with-pubsub-channel.md
  docs/install/install-gcp-broker.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2048 Documentation for migrating workloads to the new namespace
  docs/how-to/namespace-transition.md
  docs/how-to/namespace-transition.sh
  docs/how-to/namespace-transition.yaml
Labels: approved, cla: yes, lgtm, size/L

#2058 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2059 Always pass upgrade test
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2062 Always pass upgrade test (#2059)
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2063 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2064 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#2065 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/tracing/populate_span_transformer.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/traces.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1997 feat/dataresidency: use cluster region as default setting
  config/core/configmaps/data-residency.yaml
  pkg/apis/configs/dataresidency/dataresidency_defaults_test.go
  pkg/apis/configs/dataresidency/defaults.go
  pkg/apis/configs/dataresidency/testdata/config-dataresidency.yaml
  pkg/gclient/metadata/client.go
  pkg/gclient/metadata/interfaces.go
  pkg/gclient/metadata/testing/client.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/intevents/topic/topic.go
  pkg/reconciler/intevents/topic/topic_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  pkg/utils/metadata.go
  pkg/utils/metadata_test.go
Labels: approved, cla: yes, lgtm, size/L

#2061 Revert "Always pass upgrade test (#2059)"
  test/e2e-upgrade-tests.sh
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/S

#2045 Add E2E test for authentication check with Source
  go.mod
  test/e2e/e2e_test.go
  test/e2e/test_authcheck.go
  test/lib/creation.go
  test/lib/lifecycle.go
  test/lib/pubsub.go
  test/lib/utils.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2067 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/broker/v1beta1/broker/reconciler.go
  pkg/client/injection/reconciler/broker/v1beta1/trigger/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudauditlogssource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudbuildsource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudpubsubsource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudschedulersource/reconciler.go
  pkg/client/injection/reconciler/events/v1/cloudstoragesource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudauditlogssource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudbuildsource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudpubsubsource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudschedulersource/reconciler.go
  pkg/client/injection/reconciler/events/v1beta1/cloudstoragesource/reconciler.go
  pkg/client/injection/reconciler/intevents/v1/pullsubscription/reconciler.go
  pkg/client/injection/reconciler/intevents/v1/topic/reconciler.go
  pkg/client/injection/reconciler/intevents/v1alpha1/brokercell/reconciler.go
  pkg/client/injection/reconciler/intevents/v1beta1/pullsubscription/reconciler.go
  pkg/client/injection/reconciler/intevents/v1beta1/topic/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2066 Revert "Always pass upgrade test (#2059)" (#2061)
  test/e2e-upgrade-tests.sh
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/S

#2057 Add auth check into broker ingress pod
  cmd/broker/ingress/wire_gen.go
  pkg/broker/ingress/handler.go
  pkg/testing/port.go
  pkg/utils/authcheck/probechecker_test.go
  pkg/utils/clients/factories.go
  pkg/utils/clients/factories_test.go
Labels: approved, cla: yes, lgtm, size/L

#2029 Make BrokerCell's Targets support things other than Brokers.
  pkg/broker/config/README.md
  pkg/broker/config/cache.go
  pkg/broker/config/cache_test.go
  pkg/broker/config/config.go
  pkg/broker/config/key.go
  pkg/broker/config/key_test.go
  pkg/broker/config/memory/memory.go
  pkg/broker/config/memory/memory_test.go
  pkg/broker/config/targets.pb.go
  pkg/broker/config/targets.proto
  pkg/broker/config/volume/volume_test.go
  pkg/broker/handler/context/broker.go
  pkg/broker/handler/context/target_test.go
  pkg/broker/handler/fanout.go
  pkg/broker/handler/fanout_test.go
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
  pkg/broker/handler/processors/fanout/processor.go
  pkg/broker/handler/processors/fanout/processor_test.go
  pkg/broker/handler/processors/filter/processor_test.go
  pkg/broker/handler/retry_test.go
  pkg/broker/handler/testing/helper.go
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
  pkg/broker/ingress/multi_topic_decouple_sink.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
  pkg/metrics/delivery_reporter.go
  pkg/metrics/delivery_reporter_test.go
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/brokercell/resources/configmap_test.go
  pkg/reconciler/brokercell/testingdata/configmap.go
Labels: approved, cla: yes, lgtm, size/XXL

#2068 feat(broker): treat non-CloudEvent reply as successful delivery
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
Labels: approved, cla: yes, lgtm, size/M

#2071 [Automated] Format markdown
  pkg/broker/config/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2073 feat(broker): treat non-CloudEvent reply as successful delivery
  pkg/broker/handler/processors/deliver/processor.go
  pkg/broker/handler/processors/deliver/processor_test.go
Labels: approved, cla: yes, lgtm, size/M

#2072 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/broker/v1beta1/broker/controller.go
  pkg/client/injection/reconciler/broker/v1beta1/trigger/controller.go
  pkg/client/injection/reconciler/events/v1/cloudauditlogssource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudbuildsource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudpubsubsource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudschedulersource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudstoragesource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudauditlogssource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudbuildsource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudpubsubsource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudschedulersource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudstoragesource/controller.go
  pkg/client/injection/reconciler/intevents/v1/pullsubscription/controller.go
  pkg/client/injection/reconciler/intevents/v1/topic/controller.go
  pkg/client/injection/reconciler/intevents/v1alpha1/brokercell/controller.go
  pkg/client/injection/reconciler/intevents/v1beta1/pullsubscription/controller.go
  pkg/client/injection/reconciler/intevents/v1beta1/topic/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/controller.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/duck/channel.go
  vendor/knative.dev/eventing/test/lib/duck/resource_creators.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#2074 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2075 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2069 feat/broker: validate deadLetterSink with retry
  pkg/apis/broker/v1beta1/broker_validation.go
  pkg/apis/broker/v1beta1/broker_validation_test.go
Labels: approved, cla: yes, lgtm, size/S

#2078 [] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/traces.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2081 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2082 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2083 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2079 Extend Probe Helper to cover PingSource
  test/test_images/probe_helper/main.go
  test/test_images/probe_helper/probe/handlers/cloudscheduler.go
  test/test_images/probe_helper/probe/handlers/event_type.go
  test/test_images/probe_helper/probe/handlers/ping.go
  test/test_images/probe_helper/probe/handlers/providers.go
  test/test_images/probe_helper/probe/helper_test.go
  test/test_images/probe_helper/probe/wire.go
  test/test_images/probe_helper/probe/wire_gen.go
  test/test_images/probe_helper/probe_helper.yaml
  test/test_images/probe_helper/wire.go
  test/test_images/probe_helper/wire_gen.go
  test/test_images/scheduler_receiver/pod.yaml
Labels: approved, cla: yes, lgtm, size/L

#2085 add README to run perf test
  test/performance/README.md
Labels: approved, cla: yes, lgtm, size/M

#2070 Add authentication check e2e test for BrokerCell
  test/e2e-common.sh
  test/e2e-secret-tests.sh
  test/e2e-wi-tests.sh
  test/test_configs/invalid-credential.json
Labels: approved, cla: yes, lgtm, size/L

#2086 Remove stale liveliness and readiness check in broker ingress
  pkg/broker/ingress/handler.go
  pkg/broker/ingress/handler_test.go
Labels: approved, cla: yes, lgtm, size/S

#2088 Remove latest_version as change is merged upstream
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/S

#2090 [Automated] Format markdown
  test/performance/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2091 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/import-boss/generators/import_restrict.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/generators/tags.go
  vendor/k8s.io/gengo/generator/execute.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/knative.dev/eventing/test/README.md
  vendor/knative.dev/eventing/test/upload-test-images.sh
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/serving/pkg/client/listers/autoscaling/v1alpha1/metric.go
  vendor/knative.dev/serving/pkg/client/listers/autoscaling/v1alpha1/podautoscaler.go
  vendor/knative.dev/serving/pkg/client/listers/serving/v1/configuration.go
  vendor/knative.dev/serving/pkg/client/listers/serving/v1/revision.go
  vendor/knative.dev/serving/pkg/client/listers/serving/v1/route.go
  vendor/knative.dev/serving/pkg/client/listers/serving/v1/service.go
  vendor/knative.dev/serving/pkg/client/listers/serving/v1alpha1/domainmapping.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2092 feat/perftest: make throughput more stable
  test/performance/benchmarks/broker-gcp/continuous/100-broker-gcp-setup.yaml
  test/performance/benchmarks/broker-gcp/continuous/200-broker-gcp.yaml
Labels: approved, cla: yes, lgtm, size/L

#2093 Use the PublishSettings, rather than always using DefaultPublishSetti…
  pkg/broker/ingress/multi_topic_decouple_sink.go
  pkg/broker/ingress/multi_topic_decouple_sink_test.go
Labels: approved, cla: yes, lgtm, size/M

#2098 Remove magic 5 seconds in fanout
  pkg/broker/handler/fanout.go
Labels: approved, cla: yes, lgtm, size/S

#2095 Remove unused parameter from storage_admin_set_up
  hack/init_cloud_storage_source.sh
  hack/lib.sh
  test/e2e-common.sh
  test/e2e-wi-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2105 Fix typo in cloud-trace doc
  docs/how-to/cloud-trace.md
Labels: approved, cla: yes, lgtm, size/XS

#2030 Create generic CellTenant and CellTentant Target reconcilers
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/create_brokercell.go
  pkg/reconciler/broker/resources/brokercell.go
  pkg/reconciler/brokercell/broker_targets_config.go
  pkg/reconciler/celltenant/cell_tenant.go
  pkg/reconciler/celltenant/interfaces.go
  pkg/reconciler/celltenant/target.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#2109 feat/trigger: keep the BrokerDoesNotExist message same as mtbroker
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2111 Update error message verification in Auth Check
  pkg/utils/authcheck/list.go
  pkg/utils/authcheck/list_test.go
  test/e2e/test_authcheck.go
Labels: approved, cla: yes, lgtm, size/S
