Repository google/knative-gcp, pull requests merged in 2021-07, with the labels that each got.

#2246 Manually update release-0.23 branch
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/channel_spec_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_test_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2247 Pin serving and eventing e2e test versions to 0.23
  test/lib.sh
Labels: approved, cla: yes, lgtm, size/XS

#2248 manual update of deps in 0.23 branch
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
