Repository google/knative-gcp, pull requests merged in 2021-03, with the labels that each got.

#2165 [Automated] Format markdown
  docs/how-to/authentication-mechanism-troubleshooting.md
  docs/how-to/broker-priority.md
  docs/how-to/cloud-trace.md
  docs/how-to/metrics.md
  docs/install/install-broker-with-pubsub-channel.md
  docs/install/install-gcp-broker.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2167 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2171 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2172 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2176 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  pkg/client/injection/kube/client/client.go
  pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2175 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2177 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/generic_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/serving/pkg/client/injection/client/client.go
  vendor/knative.dev/serving/pkg/client/injection/client/fake/fake.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2179 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/golang.org/x/xerrors/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2180 Use CloudPubSubSource in TriggerDependencyAnnotationTest
  test/e2e/test_trigger_dependency_annotation.go
Labels: approved, cla: yes, lgtm, size/M

#2183 [Automated] Update actions
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2184 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2185 chore: remove pre-install jobs
  config/pre-install/v0.18.0/channel.yaml
  config/pre-install/v0.18.0/cloudauditlogssource.yaml
  config/pre-install/v0.18.0/cloudbuildsource.yaml
  config/pre-install/v0.18.0/cloudpubsubsource.yaml
  config/pre-install/v0.18.0/cloudschedulersource.yaml
  config/pre-install/v0.18.0/cloudstoragesource.yaml
  config/pre-install/v0.18.0/clusterrole.yaml
  config/pre-install/v0.18.0/placeholder.go
  config/pre-install/v0.18.0/pullsubscription.yaml
  config/pre-install/v0.18.0/serviceaccount.yaml
  config/pre-install/v0.18.0/storage-version-migration.yaml
  config/pre-install/v0.18.0/topic.yaml
  config/pre-install/v0.19.0/cloudbuildsource.yaml
  config/pre-install/v0.19.0/clusterrole.yaml
  config/pre-install/v0.19.0/placeholder.go
  config/pre-install/v0.19.0/serviceaccount.yaml
  config/pre-install/v0.19.0/storage-version-migration.yaml
  docs/install/install-knative-gcp.md
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XXL

#2187 Filter brokerCell resource updates by label
  pkg/reconciler/brokercell/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#2186 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2189 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2190 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2191 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/broker/v1beta1/broker/controller.go
  pkg/client/injection/reconciler/broker/v1beta1/trigger/controller.go
  pkg/client/injection/reconciler/events/v1/cloudauditlogssource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudbuildsource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudpubsubsource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudschedulersource/controller.go
  pkg/client/injection/reconciler/events/v1/cloudstoragesource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudauditlogssource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudbuildsource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudpubsubsource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudschedulersource/controller.go
  pkg/client/injection/reconciler/events/v1beta1/cloudstoragesource/controller.go
  pkg/client/injection/reconciler/intevents/v1/pullsubscription/controller.go
  pkg/client/injection/reconciler/intevents/v1/topic/controller.go
  pkg/client/injection/reconciler/intevents/v1alpha1/brokercell/controller.go
  pkg/client/injection/reconciler/intevents/v1beta1/pullsubscription/controller.go
  pkg/client/injection/reconciler/intevents/v1beta1/topic/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S
